example/hello/odp_hello.c
Core 0 might be not available and app should
ask for available core before pinning to it.
https://bugs.linaro.org/show_bug.cgi?id=2806
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
=> example: hello: ask odp for available core

platform/linux-generic/odp_schedule_sp.c
SP scheduler hangs in process mode performance test
due to global data structure were not created in shared
memory region.
Signed-off-by: Yi He <yi.he@linaro.org>
Reviewed-and-tested-by: Bill Fischofer <bill.fischofer@linaro.org>
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
=> linux-gen: sched: fix SP scheduler hang in process mode

.travis.yml
v2: define RTE_MACHINE in install stage, not on configure. There is really works.
---
1)
disable cpu optimisations for code run in Travis env.
By default dpdk uses -march=corei7-avx with generates
specific instructions and execution fails with:
Please check that RTE_MACHINE is set correctly.
More info here:
https://github.com/Linaro/odp/pull/218
2) disabling dpdk caching in Travis for now.
=> [PATCH v3] travis: build dpdk for general cpu

configure.ac, include/odp/api/spec/queue_types.h, include/odp/api/spec/schedule_types.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_scalable.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, test/validation/api/scheduler/scheduler.c
Application may do enqueues to multiple destination queues from within an ordered scheduling context. It's wasteful and sometimes not acceptable (due to potentially large reordering delay) to reorder all destination queues. E.g. application may use plain queues as temporary object storage, etc which do not benefit from enqueue operation reordering. Ordering context is released during the next schedule call (odp_schedule_release_ordered() is just a hint), so it would be complex for application to avoid unnecessary re-ordering.
=> [PATCH v4] API: queue parameter to disable reordering

platform/linux-generic/odp_ishm.c
Fixes build error ("array subscript is below array bounds") on Debian 8
(gcc 4.9.2).
Reported-by: Risto Teittinen <risto.teittinen@nokia-bell-labs.com>
=> [PATCH v2] linux-gen: shm: check proc_index value before usage

m4/odp_pthread.m4
AC_SUBST PTHREAD_CFLAGS/_LIBS variables inside ODP_PTHREAD macro
definition, so they get properly substituted when compiling.
Signed-off-by: Dmitry Eremin-Solenikov <deremin-solenikov@cavium.com>
=> [PATCH v4] m4: fix ODP_PTHREAD definition

configure.ac, include/odp/api/spec/shared_memory.h, platform/linux-generic/include/odp_shm_internal.h, platform/linux-generic/odp_ishm.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_shared_memory.c, test/validation/api/shmem/shmem.c
When set, this flag guarantees that the memory reserved by odp_shm_reserve() is allocated from huge pages. The call will fail if enough huge page memory is not available.
V2:
- ODP_SHM_HP comment wording and comment clean-up (Petri)
- Removed internal _odp_shm_reserve() function
=> [PATCH v3] api: shm: add ODP_SHM_HP flag

test/validation/api/scheduler/scheduler.c
V2:
- `schedule_retries != WAIT_1MS_RETRIES` -> `schedule_retries < WAIT_1MS_RETRIES` (Stan)
=> [PATCH v2] validation: scheduler: test fixes

platform/linux-generic/odp_crypto_openssl.c
Starting from OpenSSL versions 1.1.0 the locking callbacks are no longer
required.
Fixes: https://github.com/OpenDataPlane/odp/issues/817
Reported-by: Jussi Kerttula <jussi.kerttula@nokia.com>
=> [PATCH v2] linux-gen: crypto: disable openssl locking callbacks

platform/linux-generic/Makefile.am, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/include/odp_ring_common.h, platform/linux-generic/include/odp_ring_internal.h, platform/linux-generic/include/odp_ring_ptr_internal.h, platform/linux-generic/include/odp_ring_u32_internal.h, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_sp.c
Modify pool implementation to store buffer headers instead of indices. This removes the need for pointer <-> index conversion in buffer alloc/free functions.
=> [PATCH v2] linux-gen: pool: implement pool using pointer ring

config/odp-linux-generic.conf, scripts/ci/check.sh
Due to changes in pool implementation (linux-gen: pool: use pointer ring to
store buffer headers) additional single va memory is required for process
mode operation.
Reported-by: Carl Wallen <carl.wallen@nokia.com>
=> [PATCH v2] linux-gen: shm: increase amount of pre-reserved single va memory

configure.ac, include/odp/api/spec/queue.h, test/validation/api/queue/queue.c
Improve documentation and testing of queue context being NULL by default. It was already defined under odp_queue_param_t documentation.
This PR should be merged after #834 to maintain API version number increments in order.
=> [PATCH v2] api: queue context is null by default

.travis.yml
Travis default distribution is updated to Ubuntu Xenial (Trusty standard
support is ending). Miscellaneous comment typos have been fixed.
=> [PATCH v2] travis: update distribution to ubuntu xenial

configure.ac, example/classifier/odp_classifier.c, example/generator/odp_generator.c, example/l2fwd_simple/odp_l2fwd_simple.c, example/simple_pipeline/odp_simple_pipeline.c, example/time/time_global_test.c, helper/Makefile.am, helper/include/odp/helper/.gitignore, helper/include/odp/helper/odph_api.h, helper/include/odp/helper/threads.h, helper/include/odp/helper/version.h.in, helper/test/.gitignore, helper/test/Makefile.am, helper/test/version.c, helper/threads.c, helper/version.c, test/common/odp_cunit_common.c, test/performance/odp_l2fwd.c, test/performance/odp_scheduling.c
Current thread create and join helpers are not easy to use when threads are created/joined in multiple steps. API does not specify if it's possible and implementation is based on cpu count in cpumask and hidden "last" flag.
Added new implementations, with improved specification, parameter set and new features. Added also version number support for helper library, so that helper API changes are easy to track from application.
Old create/join helpers are not modified. Some test applications (incl. all validation test) was already moved to use the new functions, the rest will be moved soon.
=> [PATCH v3] New helpers for thread create and join

test/validation/api/ipsec/ipsec.c
The inline tests would fail if the test interface type didn't support
inline IPsec processing. Check pktio level inline IPsec support before
running tests.
=> [PATCH v2] validation: ipsec: check pktio device level inline support

test/performance/odp_sched_latency.c
Prevent pre-scheduling events to terminating threads.
=> [PATCH v2] test: sched_latency: resume scheduling only on main thread

test/performance/odp_scheduling.c
Prevents pre-scheduling events to finished threads.
=> [PATCH v2] test: scheduling: resume scheduling only after sync barrier

.travis.yml, m4/odp_pcap.m4, platform/linux-generic/m4/configure.m4
Add '--without-pcap' option to explicitly build ODP without PCAP pktio
regardless of if the library is available on the build host.
Suggested-by: Risto Reittinen <risto.teittinen@nokia-bell-labs.com>
=> [PATCH v2] configure: add option to disable pcap pktio support

configure.ac, include/odp/api/spec/time.h, include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/validation/api/time/time.c, test/validation/api/timer/timer.c
Clarifies current timer API functionality (set/reset operation and event type), adds timer resolution capability and adds time defines for minute/hour.
Timer validation test of minimum timeout needed fixing posix timer overrun issue in timer pool start. It seems Linux (scheduler) has about 15ms latency before the first posix timer signal is received on the timer pthread.
=> [PATCH v6] Timer and time API additions

platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/include/odp_queue_basic_internal.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_scalable.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_sp.c
Add separate defines (CONFIG_MAX_PLAIN_QUEUES, CONFIG_MAX_SCHED_QUEUES) for
configuring the maximum number of plain and scheduled queues.
ODP_CONFIG_QUEUES define has been renamed to CONFIG_MAX_QUEUES to clearly
separate it from API defines.
Queue IDs are now allocated consecutively per queue type (scheduled queues
[0, CONFIG_MAX_SCHED_QUEUES[ and plain queues[CONFIG_MAX_SCHED_QUEUES,
CONFIG_MAX_QUEUES[). This makes scheduler load balancing more predictable
since allocating plain queues won't affect to scheduler internal queue
mappings.
=> [PATCH v2] linux-gen: queue: configure max number of plain/scheduled queues

.travis.yml, platform/linux-generic/odp_schedule_sp.c
Build with -O3 in Ubuntu 18.04 fails. Fix the warning and add -O3 and -O0 jobs into Travis to avoid build breaking again in future.
=> [PATCH v2] Compile with -O3

configure.ac
User may set -march option with CFLAGS. Don't set -march when user has defined CFLAGS.
=> [PATCH v4] Don't set -march=native when user has set CFLAGS

test/performance/odp_pool_perf.c, test/performance/odp_queue_perf.c, test/performance/odp_sched_perf.c
Max_num capability value of zero means that only memory size
limits the pool size.
=> [PATCH v3] test: pool_perf: fix pool capability check

test/performance/odp_sched_perf.c
Group options -g and -j manage how many groups are created and how thread join into those groups. Wait time option -w specifies how much time application spends between schedule and queue enqueue calls.
=> [PATCH v2] New options to sched_perf test

example/generator/odp_generator.c, example/l2fwd_simple/odp_l2fwd_simple.c, test/performance/odp_bench_packet.c, test/performance/odp_cpu_bench.c, test/performance/odp_l2fwd.c, test/performance/odp_sched_pktio.c
Some apps and tests use SHM to hold a flag for thread termination updated by a SIGINT signal handler. This fixes a potential SEGFAULT that can happen if user sends a SIGINT after SHM is freed.
=> [PATCH v2] Fix potential segfaults on app termination

platform/linux-generic/pktio/dpdk.c
DPDK registers mempool ops named 'ops_stack' internally causing multiple
definition failure when linking DPDK with '--whole-archive' flag.
=> [PATCH v2] linux-gen: dpdk: rename mempool handler ops to avoid naming conflict

platform/linux-generic/odp_timer.c
Don't reserve any memory or perform initialization if timer feature
(odp_feature_t.feat.timer) is marked as not used.
=> [PATCH v4] linux-gen: timer: don't reserve any resources when timers are disabled

m4/odp_dpdk.m4, platform/linux-generic/pktio/dpdk.c
Link whole dpdk library with 'whole-archive' flags instead of linking each
driver individually.
Adds missing mlx5 driver dependency.
=> [PATCH v2] linux-dpdk: improve dpdk linking

example/packet/odp_pktio.c, example/switch/odp_switch.c, test/performance/odp_cpu_bench.c, test/performance/odp_pktio_ordered.c
Remove extra plus characters from short option string.
Only the first char needs to be '+' char: "If the first character
of option string is '+' then option processing stops as soon as
a nonoption argument is encountered."
=> [PATCH v2] test: correct getopt short option usage

platform/linux-generic/README, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_socket_common.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/socket_common.c, platform/linux-generic/test/validation/api/pktio/pktio_run_dpdk.sh, platform/linux-generic/test/validation/api/pktio/pktio_run_netmap.sh
Previously, the odp_pktio_open() implementation called open() for all
implementation internal pktio types in predefined order until the call
succeeded or all pktio types failed.
Add option to explicitly define the used pktio type per device. This
enables the user to use multiple pktio types within a single application.
The pktio type is selected by adding pktio_type prefix in front of device
name separated by a colon (<pktio_type>:<if_name>).
E.g.
socket:eth1
netmap:eth2
=> [PATCH v2] linux-gen: pktio: enable explicit pktio type definition

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_timer_perf.c
Added new test application to measure schedule call CPU
cycle consumption with various timer pool parameter
combinations. This measurement is mostly interesting with
software based timer implementations, where timers may be
polled from the schedule call.
=> [PATCH v6] test: timer_perf: add new timer performance test

configure.ac, example/ipfragreass/odp_ipfragreass.c, test/validation/api/ipsec/Makefile.am, test/validation/api/ipsec/ipsec_test_in.c, test/validation/api/ipsec/ipsec_test_out.c
GCC 9 includes a new warning (-Waddress-of-packed-member). Handle it only as a warning, not as an error. Enabled struct initializations warnings again and fixed some struct init issues that an old compiler complained about.
=> [PATCH v1] Fix build with GCC 9

.gitignore, configure.ac, helper/include/odp/helper/odph_debug.h, helper/test/debug.c, include/Makefile.am, include/odp/autoheader_external.h.in, include/odp/autoheader_internal.h.in, m4/odp_dpdk.m4, m4/odp_pcap.m4, m4/odp_scheduler.m4, platform/linux-generic/include/odp_debug_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/m4/odp_dpdk.m4, platform/linux-generic/m4/odp_netmap.m4, platform/linux-generic/odp_impl.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_pcapng.c, platform/linux-generic/odp_queue_if.c, platform/linux-generic/odp_schedule_if.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/dpdk_parse.c, platform/linux-generic/pktio/io_ops.c, platform/linux-generic/pktio/netmap.c
The config.h file has been split into three parts:
- autoheader_build.h: should NOT be included by ANY source file
- autoheader_external.h: can be included by any source file, including public headers
- autoheader_internal.h: can be included by any internal source file, but NOT by public headers
autoheader_external.h and autoheader_internal.h are generated based on
matching template files (*.in) and include only ODP defines.
autoheader_build.h includes all build defines and should not be included
by any source file.
=> [PATCH v2] linux-gen: include only ODP defines in autogenerated header files

example/ping/odp_ping.c
Initialize len allways to make an older compiler happy.
It complains about potentially uninitialized variable,
but this should happen only when odp_packet_l4_ptr()
returns NULL (which is checked first).
=> [PATCH v2] example: ping: initialize len allways

platform/linux-generic/odp_classification.c, test/common/odp_cunit_common.c, test/common/odp_cunit_common.h, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/comp/comp.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/ipsec/ipsec.c, test/validation/api/pktio/parser.c, test/validation/api/pktio/pktio.c, test/validation/api/scheduler/scheduler.c, test/validation/api/traffic_mngr/traffic_mngr.c
Clean up classifier and validation test code before adding new CUSTOM_L3 PMR rule into API. Classifier implementation missed reporting some capabilities, tests didn't check those capabilities and they were tested. Source IPv4 term test was missing. Also improved test result output when some tests are inactive (skipped due to missing capability). Now inactive tests are listed by default in test suite results.
=> [PATCH v2] Classifier and validation test clean up

configure.ac
Trying to build static test applications without static ODP library would
fail.
=> [PATCH v2] configure: disable static test applications without static odp lib

config/odp-linux-generic.conf, platform/linux-generic/include-abi/odp/api/abi/packet.h, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp_buffer_internal.h, platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/include/odp_packet_dpdk.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_buffer.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_pool.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/process-mode.conf, test/validation/api/packet/packet.c
Packet segmentation has been reimplemented using a linked list. The new
implementation is more simple and has the added benefit of reducing
packet and buffer header sizes:
odp_packet_hdr_t: 384B -> 256B
odp_buffer_hdr_t: 256B -> 64B
The dynamic packet reference implementation has been temporarily downgraded
to a simple packet copy.
=> [PATCH v2] linux-gen: packet: reimplement segmentation using linked list

platform/linux-generic/odp_ishm.c
Include page type (normal/huge) and filename in error messages.
=> [PATCH v2] linux-gen: shm: improve memory allocation error messages

config/odp-linux-generic.conf, platform/linux-generic/odp_timer.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/process-mode.conf, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
Added configure file option for inline timer (inline_thread_type) to select if control threads poll shared timer pools or not. When control threads still poll their private pools. With this user can configure control and worker threads to use separate timer pools.
=> [PATCH v2] Timer control thread poll configure option

test/performance/odp_bench_packet.c
Added tests for the following packet functions:
odp_packet_data_seg_len()
odp_packet_free_sp()
odp_packet_from_event_multi()
odp_packet_to_event_multi()
odp_packet_subtype()
odp_packet_parse()
odp_packet_parse_multi()
=> [PATCH v2] test: bench_packet: add tests for missing packet functions

test/validation/api/ipsec/ipsec_test_in.c, test/validation/api/ipsec/ipsec_test_out.c
Explicitly initialize ipsec_test_part structs to zero to avoid  "missing
initializer for field" warnings with old compilers (Debian 8, GCC 4.9.2).
Reported-by: Risto Teittinen <risto.teittinen@nokia-bell-labs.com>
=> [PATCH v2] validation: ipsec: memset ipsec_test_part structs to zero

include/odp/api/spec/packet.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_packet.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, test/validation/api/classification/odp_classification_common.c, test/validation/api/ipsec/ipsec.c, test/validation/api/pktio/pktio.c
An application may use this for testing or other purposes, 
when perception of the packet input interface need to be 
changed.
v4: few bugs fixed that were found during testing the patch set
=> [PATCH v7] api: packet input set function

configure.ac, example/sysinfo/odp_sysinfo.c, example/timer/odp_timer_accuracy.c, include/odp/api/spec/feature.h, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/odp_comp.c, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_init.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_events.c, platform/linux-generic/odp_ipsec_sad.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/loop.c, test/performance/odp_cpu_bench.c, test/performance/odp_l2fwd.c, test/performance/odp_pool_perf.c, test/performance/odp_queue_perf.c, test/performance/odp_sched_perf.c, test/performance/odp_sched_pktio.c, test/performance/odp_timer_perf.c, test/validation/api/Makefile.am, test/validation/api/init/.gitignore, test/validation/api/init/Makefile.am, test/validation/api/init/init_main.c
Add compression feature flag into API. Update feature disable implementation. Disabling crypto, ipsec, compression and traffic manager when not used saves over 20MB of shared memory.
=> [PATCH v3] api: compression feature disable

config/odp-linux-generic.conf, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_pool.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/process-mode.conf
Add configure file options to control data alignment in packet input. Default values keep the current data alignment (frame starts at cache line align). All packet IO drivers doing data copy use this config, other drivers (dpdk-zero-copy, loop, ipc) ignore it.
=> [PATCH v2] Pktin data alignment configuration

.travis.yml, platform/linux-generic/test/packet_align.conf, scripts/ci/check_pktio.sh
Added new options to enable testing timer reset and log test results into a file.
=> [PATCH v2] travis: add packet and packet IO align test

platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/pktio_common.c
Previously some pktio types could recv/send packets even though the pktio
was not in started state.
=> [PATCH v4] linux-gen: pktio: always check pktio state before recv/send

test/validation/api/buffer/buffer.c
Allocated buffer may be larger than what was requested in odp_pool_param_t.
Fixed a segfault in buffer_test_pool_alloc_free() if a buffer check failed.
=> [PATCH v2] validation: buffer: allow allocted buffer size to be larger than requested

example/timer/odp_timer_accuracy.c
Added option (-g) to control offset (gap) between timers within
a burst. This way many periodic (restarted) timers can be tested
with different expiration times.
=> [PATCH v2] example: timer_acc: add burst gap option

platform/linux-generic/pktio/dpdk.c
Fix build issues with DPDK v19.11. Also DPDK mempool allocation behavior has changed so that  zero copy packet IO needs MEMPOOL_F_NO_IOVA_CONTIG flag defined.
=> [PATCH v3] Enable DPDK v19.11 usage

example/packet/odp_packet_dump.c, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/pktio/socket_mmap.c
Socket may remove VLAN header in packet reception and record it into tpacket2_hdr structure. Insert VLAN header back into the packet when this happens.
=> [PATCH v2] Recreate vlan header in socket_mmap

configure.ac, include/odp/api/abi-default/align.h, include/odp/api/spec/align.h, include/odp/api/spec/version.h.in, test/validation/api/system/system.c
Added new macros into API for easier:
* API version comparison: ODP_VERSION_API_NUM, ODP_VERSION_API
* Cache line size round up in buffer size calculations, etc: ODP_CACHE_LINE_ROUNDUP()
=> [PATCH v2] API: add version and cache line round up macros

config/odp-linux-generic.conf, configure.ac, include/odp/api/spec/packet.h, include/odp/api/spec/pool.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_pool.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec_test_out.c, test/validation/api/ipsec/test_vectors.h, test/validation/api/packet/packet.c
Merged packet API modifications into a single patch set. Clarify that application cannot create zero length packets. Add packet pool parameter to control minimum alignment of packet data when application allocates packets from a pool.
=> [PATCH v2] API: packet length zero and packet pool align

test/validation/api/packet/packet.c
Test packet_test_free_sp() would end up trying to allocate invalid zero
length packets if pool_capa.pkt.max_len was zero.
The following packet_alloc_multi() call would then loop indefinitely since
error return value was not checked.
=> [PATCH v2] validation: packet: prevent test trying to allocate zero length packets

platform/linux-generic/include/odp_config_internal.h
Enable creating larger single segment packets.
Suggested-by: Jussi Kerttula <jussi.kerttula@nokia.com>
=> [PATCH v2] linux-gen: pool: increase max segment length

test/performance/odp_packet_gen.c
Ensure that destination string is null terminated by passing
size - 1 to strncpy. Strncpy copies all n chars to the destination
string if the source is longer than the destination.
error: 'strncpy' specified bound 24 equals destination size
Fixes: https://github.com/OpenDataPlane/odp/issues/930
=> [PATCH v1] test: packet_gen: fix build with GCC 9

.travis.yml, platform/linux-generic/test/validation/api/pktio/pktio_run_pcap.sh, test/validation/api/pktio/pktio.c
Enables GCC 9.2 and Clang 9 testing.
=> [PATCH v4] travis: add ubuntu 20.04 build test

test/validation/api/packet/packet.c
Some tests are missing params.pkt.max_num value and yet expect that no
more than params.pkt.num packets will be present in the pool. That is
not required by spec. Instead max_num parameter should be used for that.
Change-Id: I63901f564a634355267f1243cf7c12379945791c
=> [PATCH v2] validation: packet: fix max_num expectations

test/validation/api/pool/pool.c
Verify that enough packets (length='odp_pool_param_t.pkt.len') can be
allocated from a packet pool and the segment length matches when
'odp_pool_param_t.pkt.seg_len' is used.
=> [PATCH v2] validation: pool: add test for packet pool seg_len parameter

.travis.yml
Add new arm64 build only test for Ubuntu 20.04. Uses GCC 9 and Clang 10.
=> [PATCH v2] travis: add ubuntu 20.04 arm64 build test

test/validation/api/scheduler/scheduler.c
New scheduler stress test creates the maximum number of scheduled queues
returned by odp_schedule_config_init(), fills them with events, and runs a
number of test scheduling rounds. The test is repeated for all scheduled
queue types.
V2:
- Fixed Petri's comments
- Added odp_schedule_group_create() test improvement commit
=> [PATCH v3] validation: scheduler: add new stress test

platform/linux-generic/odp_ipsec.c
Allocate internal authentication and cipher algorithm capability arrays
dynamically. Removes the need for MAX_CAPS define, which had to be manually
increased to support more algorithms.
=> [PATCH v2] linux-gen: ipsec: allocate internal capability arrays dynamically

config/odp-linux-generic.conf, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, platform/linux-generic/arch/default/odp_sysinfo_parse.c, platform/linux-generic/arch/mips64/odp_sysinfo_parse.c, platform/linux-generic/arch/powerpc/odp_sysinfo_parse.c, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/include/odp_sysinfo_internal.h, platform/linux-generic/odp_system_info.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, test/validation/api/system/system.c
Enable setting odp_cpu_hz() and odp_cpu_hz_max() values manually usinge the
config file on platforms where frequencies aren't available using standard
Linux methods.
=> [PATCH v3] linux-gen: system: read default cpu frequency values from config file

platform/linux-generic/odp_schedule_scalable.c
The particular memory block is reserved during global init, so single VA
flags is not needed.
Reported-by: Mikko Kurikka <mikko.kurikka@nokia.com>
=> [PATCH v2] linux-gen: sched scalable: remove unnecessary single VA shm flag

m4/odp_libconfig.m4, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_libconfig.m4
Add '--with-config=FILE' configuration option for setting path to the default configuration file. The default configuration file has to include all configuration options.
V2:
- Renamed `--with-config` to `--with-config-file`. (Petri)
=> [PATCH v3] linux-gen: add configure option for setting path to the default config file

example/hello/odp_hello.c
In the existing application, -c is not honored, instead, it picks the
first available CPU from odp_cpumask_default_control().
https://github.com/OpenDataPlane/odp/pull/955 fixes the above-mentioned
problem, but hello world does not have to demonstrate CPU pinning,
instead it should demonstrate a minimum functionality application.
User can run the application with taskset command if it needs to run
on a particular CPU.
To simplify and fix the existing bug, this patch removes the -c option.
Also, it fixes a segfault issue if -n provided without any argument.
Suggested-by: Petri Savolainen <petri.savolainen@nokia.com>
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
=> example: hello: remove -c option

configure.ac, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_sp.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/test/pktio_ipc/ipc_common.c, platform/linux-generic/test/pktio_ipc/ipc_common.h, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c
GCC 10 warns if the bounds of interior zero length arrays are exceeded, but that is done intentionally in ODP in a few places. Ignore the warning in those pieces of code.
The current GCC 10 also seems to have a bug that causes bogus array-bounds and stringop-overflow warnings. As a workaround, globally exclude those warnings from -Werror. Both are in the same commit as the affected code is the same and the issue triggering the warnings appears to be the same.
=> [PATCH v3] Fix compilation with GCC 10

platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_pool.c, test/performance/odp_l2fwd.c
Added new options to control number of pools (-y) and number of packets per pool (-n). Depending on implementation these settings may have performance impacts.
-y, --pools             0: A pool per interface
1: A single pool for all interfaces (default)
-n, --num_pkt <num>     Number of packets per pool. Default is 16k or
the maximum capability. Use 0 for the default.
=> [PATCH v3] L2fwd pool options

configure.ac, platform/Makefile.inc, platform/linux-generic/Makefile.am, platform/linux-generic/m4/odp_libconfig.m4
When providing a conf file with "--with-config-file",
- In case of change in this file, rebuild was not doing anything
- In case of change in generic conf file, rebuild was using
generic conf file instead of provided one to regenerate / rebuild
- Generic conf file was installed
Signed-off-by: Thomas Pansiot <thomas.pansiot@nokia.com>
=> [PATCH v2] linux-gen: use provided conf file for install and rebuild

test/performance/odp_packet_gen.c
Added -u option to enable periodic statistics printing. Wall clock
time (since test start) is printed with per interface TX/RX
cumulative packet counts. User can calculate packet and bit rates
from these.
=> [PATCH v3] test: packet_gen: add periodic statistics

example/Makefile.inc, helper/Makefile.am
This prevents multiple inclusion of libodp-linux during builds, once as part of libodphelper and then directly by the application. This causes problems when linking statically with LTO enabled. On tested compiler (9.2.1-9ubuntu2) such duplication causes constructor symbols to be defined multiple times. This means that constructors will be run multiple times which leads to unexpected behavior.
To fix this, remove libodp from helper link list. This works when compiling applications because there is no point in using libodphelper without libodp-linux, therefore both libraries have to be provided.
After removing library order in example/Makefile.inc is required to ensure the proper linking.
Reproduction steps:
1. Add a constructor in platform/linux-generic/odp_init.c, i.e.:
```diff
diff --git …
```
=> [PATCH v4] build: do not define libodp as part of helper

include/Makefile.am, include/odp/api/abi-default/errno.h, include/odp/api/abi-default/hash.h, include/odp/api/errno.h, include/odp/api/hash.h, include/odp/arch/arm32-linux/odp/api/abi/errno.h, include/odp/arch/arm32-linux/odp/api/abi/hash.h, include/odp/arch/arm64-linux/odp/api/abi/errno.h, include/odp/arch/arm64-linux/odp/api/abi/hash.h, include/odp/arch/default-linux/odp/api/abi/errno.h, include/odp/arch/default-linux/odp/api/abi/hash.h, include/odp/arch/mips64-linux/odp/api/abi/errno.h, include/odp/arch/mips64-linux/odp/api/abi/hash.h, include/odp/arch/power64-linux/odp/api/abi/errno.h, include/odp/arch/power64-linux/odp/api/abi/hash.h, include/odp/arch/x86_32-linux/odp/api/abi/errno.h, include/odp/arch/x86_32-linux/odp/api/abi/hash.h, include/odp/arch/x86_64-linux/odp/api/abi/errno.h, include/odp/arch/x86_64-linux/odp/api/abi/hash.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/errno.h, platform/linux-generic/include-abi/odp/api/abi/hash.h
Both APIs are missing respective ABI files where inline implementation could be placed.
=> [PATCH v3] Allow inlining of hash and errno APIs

platform/linux-generic/test/pktio_ipc/ipc_common.c, test/performance/odp_packet_gen.c, test/performance/odp_sched_pktio.c, test/validation/api/packet/packet.c, test/validation/api/pktio/pktio.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c
This patchset fixes several LTO related compile errors which I've noticed when building an empty platform skeleton.
=> [PATCH v4] Fix various LTO compile errors

include/odp/api/spec/random.h, test/validation/api/random/random.c
It was implied but not explicitly stated that `odp_random_data()` may return less than requested number of bytes of data in a single call (i.e. when there was entropy missing). This patchset clarifies this and adapts unit test to expect such scenario.
=> [PATCH v7] Clarify random API return expectations

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
Various Traffic Manager objects are defined in spec as separate types defined by the implementation. However while printing in unit-tests, handles are directly printed as `PRIx64` forcing implementations to utilize uint64_t (or related) type to be used for TM handles.
This patchset proposes new APIs to introduce TM debug print APIs to allow more freedom for implementation in choosing types for TM handles.
What remains to be discussed is ODP_TM_INVALID which according to spec indicates an invalid handle for each of Traffic Manager types.
=> [PATCH v4] Create missing TM print APIs

example/timer/odp_timer_simple.c
GCC7.3 warns about uninitialized members of timer pool parameters.
Application should take care to ensure clean parameter initialization.
Signed-off-by: Stanislaw Kardach <skardach@marvell.com>
=> [PATCH v2] example: timer: fix LTO compilation

platform/linux-generic/test/pktio_ipc/pktio_ipc2.c, test/common/odp_cunit_common.h, test/validation/api/pktio/pktio.c, test/validation/api/traffic_mngr/traffic_mngr.c
Make the compiler know that CU_ASSERT_FATAL does not return if the assertion fails. This gets rid of bogus warnings from subsequent code.
Change a couple of CU_ASSERTs to CU_ASSERT_FATAL to prevent the test continuing with an uninitialized handle.
Fix shaper profile validation check by clearing the param struct before reading into it and validating the content.
Get rid of a bogus maybe-uninitialized warning in pktio test by initializing the variable.
=> [PATCH v2] Test and validation fixes that also make GCC-10 happier

configure.ac, test/performance/odp_pktio_perf.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/traffic_mngr/traffic_mngr.c
While testing compilation against gcc 10.0.1 I've noticed several issues which this patchset is trying to address:
1. GCC 10 version detection is done improperly.
2. Some tests have odp_pktout_queue_t and odp_queue_t left uninitialized in some paths detected by the compiler. For safety initialize them to known invalid values.
=> [PATCH v3] GCC10 LTO compilation fixes

example/ipsec/odp_ipsec.c, example/ipsec/odp_ipsec_stream.c, example/ipsec/odp_ipsec_stream.h, example/ipsec_api/odp_ipsec.c
The application tried to allocate packets of length zero, which is not
allowed by the API.
=> [PATCH v4] linux_gen: example: ipsec: fix stream input packet allocation

example/l2fwd_simple/odp_l2fwd_simple.c, example/l3fwd/odp_l3fwd.c, example/packet/odp_packet_dump.c, example/packet/odp_pktio.c, example/ping/odp_ping.c, example/simple_pipeline/odp_simple_pipeline.c, example/switch/odp_switch.c, test/performance/odp_bench_packet.c, test/performance/odp_cpu_bench.c, test/performance/odp_l2fwd.c, test/performance/odp_pktio_ordered.c
Currently various test and example apps use a normal variable without synchronization to communicate to worker threads that they should exit. Even though this is wrong (it is a data race and thus allows undefined behavior) it often works in practice unless the compiler performs so aggressive optimizations that the flag check moves away from the thread main loop. Something like this actually happened to me with GCC-10 and link time optimization, causing make check to never complete.
Some apps use volatile flag variable which probably always works in practice even though it is still wrong (it is still a data race as volatile does not imply synchronization or atomicity). The commits of this PR do not touch the volatile flags.
=> [PATCH v2] Use atomic flag variable to trigger thread exit

example/ping/odp_ping.c
odp_pktio_info_t.name is uninitialized if odp_pktio_info() call fails.
Fixes GCC 10 LTO build error.
=> [PATCH v3] example: ping: check odp_pktio_info() return value

bootstrap, m4/odp_atomic.m4, test/Makefile.inc
While integrating our implementations with other build-systems, such as buildroot and adding automated remote hardware testing, we've noticed several minor issues with current automake files. This patchset gathers together fixes for those issues. Related to this pull request are: https://github.com/OpenDataPlane/odp/pull/924 and https://github.com/OpenDataPlane/odp/pull/956 which I think should be handled separately.
=> [PATCH v5] Various build-system fixes

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c
Clarify that info structures (odp_tm_node_info_t, odp_tm_node_fanin_info_t,
odp_tm_queue_info_t, odp_tm_query_info_t) are only written on success.
Invalid out tags were removed from query flags.
=> [PATCH v4] api: tm: info structures are written only on success

configure.ac, include/odp/api/spec/packet_io.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_socket_common.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/null.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_common.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c, test/validation/api/pktio/parser.c, test/validation/api/pktio/pktio.c, test/validation/api/traffic_mngr/traffic_mngr.c
Add new function odp_pktio_link_info() and data structure
odp_pktio_link_info_t for reading current link status information:
- Autonegotiation mode (enabled/disabled)
- Duplex mode (unknown/half duplex/full duplex)
- Speed (Mbps)
- Link status (up/down)
=> [PATCH v6] api: pktio: enable reading link status information

platform/linux-generic/pktio/dpdk.c
Read correct rte_eth_link.link_speed field in odp_pktio_link_info().
=> [PATCH v2] linux-gen: dpdk: read correct field in odp_pktio_link_info()

example/time/time_global_test.c, helper/cuckootable.c, helper/iplookuptable.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c
Honor the odp_pool_capability_t::buf.max_align attribute while
creating the pool.
Some implementation chooses to optimize odp_buffer_t handling in
such a way that implementation-specific metadata and actual
data can be in the same cache-line as a performance optimization
while accessing the odp_buffer_t.
As a fix, except helpers, let the application uses the default
alignment from odp_pool_param_init().
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
=> validation: pool: honor max_align capability

example/ipsec/README, example/ipsec/odp_ipsec.c, example/ipsec_api/odp_ipsec.c
Previously, the IPsec example applications would close right away if no test streams were created. A signal handler is added to close the applications cleanly.
=> [PATCH v3] IPsec example fixes

configure.ac, example/Makefile.inc, m4/odp_dpdk.m4, platform/linux-generic/m4/configure.m4, test/Makefile.inc
build: explicitly list dependency libraries
Debian-based Linux distributions have introduced a while ago a very
specific patch to libtool generation which disables libtool generating
dependent libraries list to the linker (distribution libtool.m4 has
link_all_deplibs forced to no). This causes issues when cross-compiling
while using dependent libraries compiled and installed manually to
non-sysroot location (see [1]).
To reproduce the issue, one has to fetch a toolchain which does not
contain pkg-config in it. Debian/Ubuntu aarch64 toolchains do contain
version of that tool (aarch64-linux-gnu-pkg-config) which does not have
the change in question.
Reproduction steps:
1. Set env variables used throughout other steps:
```
CROSS_COMPILE=aarch64-marvell-linux-gnu …
```
=> [PATCH v9] build: explicitly list dependency libraries

test/performance/odp_packet_gen.c, test/performance/odp_packet_gen_run.sh
Add new command line option '-w <sec>' for waiting up to <sec> seconds
for all pktio links to be up before starting the worker threads. Prints
also link information.
V2:
- Mbps -> Mbit/s (Janne)
- Don't reset `link_wait` for each interface (Janne)
=> [PATCH v3] test: packet_gen: add pktio link status check option

.travis.yml
Fix Travis configurations errors/warnings by replacing/removing deprecated
configuration options. Enables using Travis' build config validation
feature.
=> [PATCH v2] travis: fix build configuration

test/validation/api/ipsec/ipsec.c
* Fix the number of iterations for which the test
expects an ODP_IPSEC_EVENT.
* When the odp_ipsec_in_enq() or odp_ipsec_out_enq()
was not successful, the implementation won't deliver
an ODP_IPSEC_EVENT corresponding to the failed packet.
=> [PATCH v3] validation: ipsec: fix async mode test

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c
Previously, build would fail on 32-bit systems since __atomic_fetch_add()
was called using a 64-bit variable.
V2:
- Updated commit message (Janne)
=> [PATCH v3] linux-gen: pktio: use odp atomics for in_discards counter

platform/linux-generic/odp_random_null.c
Fixes build failure caused by integer overflow.
Reported-by: Ville Luttinen <ville.luttinen@nokia.com>
=> [PATCH v1] linux-gen: random: null: fix integer overflow in assert check

platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, platform/linux-generic/odp_errno.c, platform/linux-generic/odp_time.c
Use internal ODP_PRINT macro instead of printf(). ODP_PRINT enables using
application specific logging function.
Reported-by: Mikko Kurikka <mikko.kurikka@nokia.com>
=> [PATCH v2] linux-gen: remove implementation internal printf() calls

configure.ac, doc/application-api-guide/Doxyfile, doc/platform-api-guide/Doxyfile, helper/include/odph_list_internal.h, include/odp/api/abi-default/event.h, include/odp/api/abi-default/packet.h, include/odp/api/abi-default/pool.h, include/odp/api/spec/packet.h, platform/linux-generic/include-abi/odp/api/abi/packet.h, platform/linux-generic/include-abi/odp/api/abi/pool.h
While running doxygen on Ubuntu 20.04 I've noticed some new warnings popping up. Some of them are quire benign (hiding structures in helper), some are real issues with API or documentation.
This patchset addresses all the warnings detected.
=> [PATCH v4] Fixup issues detected by doxygen 1.8.17

test/validation/api/ipsec/ipsec_test_out.c
This PR consists of following two fixes to IPsec validation test applications:
1.  Fix test_out_ipv4_esp_null_aes_gmac_128() test function:
Perform both outbound and inbound processing similar to test_out_ipv4_esp_aes_gcm128. This is required as AES-GMAC algorithm uses IV for ICV generation and is generated by the ODP IPsec implementation during the IPsec outbound processing. The IV value is not known to the receiver until it receives the packet, but the test function expects a predefined IV value in the resulting packet.
2. Set L3 type for a test packet in ipsec_packet()
Similar to setting the l3 offset, set the L3 type to IPv4/IPv6 in ipsec_packet()
=> [PATCH v5] IPsec validation test application fixes

helper/linux/thread.c, helper/threads.c, platform/linux-generic/odp_pcapng.c, platform/linux-generic/odp_timer.c, platform/linux-generic/odp_traffic_mngr.c
Print pthread_create() return value to error log on failure.
=> [PATCH v2] helper: thread: print pthread_create() return value to error log

.travis.yml
Docker Hub will soon start limiting anonymous users to max 100 pulls per 6
hours. Enabling user authentication increases this limit to 200 pulls per 6
hours.
To enable authentication in Travis user has to first create a Docker Hub
account and within the account settings generate a new access token for
Travis usage. Then in Travis repository settings DOCKER_USERNAME and
DOCKER_TOKEN environment variables have to be set accordingly.
=> [PATCH v2] travis: enable docker hub authentication

configure.ac, include/odp/autoheader_internal.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/include/odp_random_openssl_internal.h, platform/linux-generic/include/odp_random_std_internal.h, platform/linux-generic/odp_random.c, platform/linux-generic/odp_random_openssl.c, platform/linux-generic/odp_random_std.c
Always build both random module implementations to detect possible build
issues. Renamed random_null implementation to random_std.
=> [PATCH v3] linux-gen: random: always build both implementations

example/generator/Makefile.am, example/ipsec/Makefile.am, example/ipsec_api/Makefile.am, example/l2fwd_simple/Makefile.am, example/l3fwd/Makefile.am, example/packet/Makefile.am, example/ping/Makefile.am, example/simple_pipeline/Makefile.am, example/switch/Makefile.am, helper/test/Makefile.am, platform/linux-generic/test/Makefile.am, platform/linux-generic/test/pktio_ipc/Makefile.am, platform/linux-generic/test/validation/api/pktio/Makefile.am, test/performance/Makefile.am
It is often beneficial to run "make check" on a remote target platform.
However in order to run it, a full build-system has to be present which
may not be efficient or possible for embedded platforms.
Alternatively autotools offer a mechanism which may be used:
LOG_COMPILER environment variable. If specified, all test invocations
are prepended with its contents. This allows injecting a wrapper script
which will ensure the test is run remotely (i.e. through ssh).
Prior to that the binaries have to be transported to the remote system.
This cannot be done in the script itself as it has no knowledge on the
dependencies of the test program, only its path. Test could be relying
on some files stored in srcdir or builddir.
An issue exists that if ODP is built in out-of-tree method (builddir != …
=> [PATCH v3] build: simplify remote target testing

Makefile.am, test/Makefile.am, test/m4/configure.m4
Change test execution order during 'make check', so that
validation tests are run before other tests. Example tests
are run before performance (and platform specific) tests as
example tests are simpler and run faster (involves less
packet IO).
Makefile.am in test directory became empty and was removed.
=> [PATCH v2] test: run validation tests before other tests

doc/application-api-guide/examples.dox, example/Makefile.am, example/debug/.gitignore, example/debug/Makefile.am, example/debug/odp_debug.c, example/m4/configure.m4
This application can be used to test various debug print
functions of ODP API. Debug functions to be called are
selected with command line options. E.g. -s option reserves
a SHM area and calls odp_shm_print() to print debug
information about it.
=> [PATCH v2] example: debug: add new debug example application

platform/linux-generic/m4/odp_libconfig.m4
Use static platform name instead of $with_platform variable. Fixes build
in multiplatform repositories (e.g. odp-dpdk).
=> [PATCH v2] linux-gen: libconfig: use static platform name in config

.shippable.yml
Disable all Shippable email notifications. The test results are shown
directly in the GitHub page, so there is no need for extra notifications.
=> [PATCH v2] shippable: disable email notifications

doc/application-api-guide/api_guide_lines.dox, doc/application-api-guide/odp.dox, doc/application-api-guide/release.dox, platform/linux-generic/odp_ishm.c
I have created two patches which address the issues found in the ODP documentation. The first patch fixes a spelling mistake while the other patch corrects some errors and typos in the API documentation.
=> [PATCH v3] Fixed documentation errors/typos

test/validation/api/classification/odp_classification_common.c, test/validation/api/classification/odp_classification_test_pmr.c
TCP sample packet header used by classification has TCP
flags set to zero and IP checksum is not being calculated
properly in some cases. Flags set to zero can be generally
considered illegal and treated as a bad packet by some HW.
RFC 793 also does not have any use case as such with all the
flags clear. Hence this patch sets ACK flag in the sample pkt.
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
=> [PATCH v5] validation: cls: fix error packet generation

platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c
odp_crypto_op_enq() sends completion events to the queue specifified
in the session of the first packet, even if other packets of the
request use a different session with a different completion queue.
Fix the bug by moving session lookup into the packet handling loop.
Fix also similar lookup problem affecting asserts odp_crypto_op().
=> [PATCH v2] linux-gen: crypto: send completion events to the correct queue

test/performance/odp_crypto.c, test/performance/odp_ipsec.c, test/performance/odp_packet_gen.c, test/performance/odp_pktio_perf.c, test/performance/odp_pool_perf.c, test/performance/odp_queue_perf.c, test/performance/odp_sched_perf.c, test/performance/odp_timer_perf.c
The first patch adds the odp_sys_info_print() to all the performance tests which currently do not display this info. The ODP system info contains important information such as CPU model, frequency, cache etc. which is needed to correctly analyze and interpret the results, especially those which are given in terms of CPU cycles. As of now, this information is shown for only half of the performance tests.
The second patch fixes a spelling error found in the results of the queue performance test.
=> [PATCH v3] test: performance: add odp_sys_info_print() to all performance tests

test/validation/api/classification/odp_classification_common.c
Rearrange VLAN header building code a little bit to avoid using
address of a packed struct member in a way that loses alignment
information.
v2: fixed checkpatch complaint
v3: added reviewd-by tag
v4: removed an unrelated commit that accidentally slipped in during rebase
=> [PATCH v4] validation: cls: get rid of alignment warning

test/performance/odp_packet_gen.c, test/performance/odp_packet_gen_run.sh
Add new packet length range option (-L, --len_range <min,max,bins>) to
enable testing with random packet lengths. To reduce pool size requirement
the length range can be split into even sized bins. Min and max size
packets are always used and one size is selected from each other bin. Bin
value of 0 means that each packet length is used. This option overrides the
standard packet length command line option.
=> [PATCH v2] test: packet_gen: add random packet length option

test/README
The command to run validation and performance tests under gdb is not
quite intutive and requires the use of libtool package. It distinctly
varies with how ODP examples are run under gdb which make use of the
generic command, i.e., "gdb <example>" and is very straightforward.
Documenting this command in the README file for tests will help
developers who are not familiar with usage of libtool for gdb as
well as improve the source code documentation.
Reviewed-by: Govindarajan Mohandoss <Govindarajan.Mohandoss@arm.com>
=> [PATCH v2] test: README: document command for running tests under gdb

test/performance/odp_packet_gen.c
When using random packet lengths the pool has to be able to allocate
max length packets.
=> [PATCH v2] test: packet_gen: use correct packet length when creating packet pool

test/validation/api/ipsec/ipsec.c
The field, pkto, is used to hold packets after IPsec processing.
Performing subtype check without checking the number of packets actually
processed by the API can lead to uninitialized access.
Also, changed the checks to compare against the actual number of
expected packets (ie, 1). Comparing against the variable can lead to
added complexity and incorrect results.
=> [PATCH v3] validation: ipsec: fix uninitized access of odp_packet

test/performance/odp_bench_packet.c
Fix a bug in odp_bench_packet performance test-suite
where few of the packet manipulation test cases were
passing in invalid addresses to the api calls.
=> [PATCH v3] test: performance: fix bug in odp_bench_packet test

test/validation/api/traffic_mngr/traffic_mngr.c
In test_shaper_bw() unit test, the exact conditions to check the
inter-receive gap of received packets has been written twice. These
branches can be effectively merged into a single branch without altering
the function logic, thereby cleaning up the code and improving its
readability.
Reviewed-by: Govindarajan Mohandoss <Govindarajan.Mohandoss@arm.com>
=> [PATCH v2] validation: traffic_mngr: merge redundant branches in test_shaper_bw()

include/odp/api/spec/ipsec.h, include/odp/api/spec/packet_io.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c
Inline outbound requires pktio output queue to allow application to
control the traffic distribution and precedence. The option to specify
output queue is required to perform QoS post inline IPsec processing.
=> [PATCH v9] api: ipsec: add tm_queue as parameter for inline outbound

doc/users-guide/users-guide-pktio.adoc, example/generator/odp_generator.c, include/odp/api/spec/packet.h, include/odp/api/spec/packet_io.h, test/validation/api/pktio/pktio.c
api: pktio: change Tx checksum insertion API semantics
Existing API spec requires application to just provide L3 offset and
and L4 offset and expects platform either in SW or HW parse the packet in
Tx and identify L3 and L4 protocols and then generate checksum if
requested. Since not all platforms have support for packet parsing in HW
in Tx, they depend on software to provide L3 and L4 types in addition to
existing L3 and L4 protocol offsets. Doing the parsing in platform SW for
such cases brings down performance and is counter productive.
Since similar to L3 and L4 offsets, even L3 and L4 proto types are provided
by HW parser in packet ingress, making use of the same information in Tx is
benefitial for performance.
So this patch changes Tx checksum insertion semantics by mandating that …
=> [PATCH v7] api: pktio: change Tx checksum insertion API semantics 

include/odp/api/spec/packet_io.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_packet_io.c, test/validation/api/classification/odp_classification_tests.c
api: pktio: add pktio capability for skip offset support
Current odp_pktio_skip_set() is supposed to work on all
platforms. Since this API is HW dependent as it asks ingress
parser to skip X bytes before starting to parse packet for standard
L2/L3 protocols, it may not be supported by every platforms.
Hence adding a set_op capability in packet_io for reporting
if a given platform supports it or not.
=> [PATCH v3] api: pktio: add pktio capability for skip offset support

include/odp/api/spec/hints.h, platform/linux-generic/odp_packet.c, platform/linux-generic/pktio/socket.c
A change to the behavior of odp_likely(), and a couple of fixes to odp_likely() calls.
=> [PATCH v2] api: make odp_likely() work also with non-boolean values

include/odp/api/abi-default/packet.h, include/odp/api/spec/packet.h, platform/linux-generic/include-abi/odp/api/abi/packet.h
Move odp_packet_chksum_status_t enum from spec/packet.h
to abi/packet.h to allow platform specific header files
to make use of this enumeration. Currently this is not
possible as spec/packet.h is included after the platform
specific header files.
Fix doxygen syntax for odp_packet_color_t enum.
=> [PATCH v5] api: packet: move odp_packet_chksum_status_t enum

doc/users-guide/users-guide-pktio.adoc, example/l3fwd/odp_l3fwd.c, include/odp/api/spec/packet_io.h, platform/linux-generic/odp_packet_io.c, test/performance/odp_l2fwd.c, test/validation/api/pktio/pktio.c
Currently ODP spec provides support for holding references
to packets and thereby those packets are not freed by platform
after transmission if they have more than one reference.
This support is useful when using stack that needs retransmissions
like TCP or some fragmentation implementations.
Most of the other forwarding/pipeline applications will not be using
this support as they don't hold any references and forward traffic
after packet manipulations.
Since there is a performance hit in some platforms for supporting
ref count update and validation in odp_pktout_send(),
this patch adds support to indicate via pktio config if PKTIO
can optimize the fastpath for case where packets sent for
transmission will not have multiple references and platform/HW
can always free them post …
=> [PATCH v6] api: pktio: add pktout no packet refs

helper/eth.c
Update data type of "byte" variable to unsigned int,
to align with the sscanf format specification.
Signed-off-by: Mohammad Iqbal Ahmad <mahmad@marvell.com>
=> helper: ethernet: fix sscanf type mismatch

configure.ac, helper/chksum.c, include/odp/api/spec/std_types.h
This is one option to handle GCC9 warnings of taking a pointer to packed structure. We could introduce unaligned integer types as part of ODP API.
PR https://github.com/OpenDataPlane/odp/pull/1046 is solving the same warnings with re-write of the checksum code.
=> [PATCH v3] api: unaligned int types

DEPENDENCIES
The current instructions for cunit cross compilation cater only to
configuring arm32 binaries on x86_64 platform and are incomplete, i.e,
'make' and 'make install' commands are missing. As well as adding those
commands, the instructions are updated to also include cunit cross
compilation for arm64 binaries.
In addition to the above changes, the '/home/user/' path in OpenSSL cross
compilation has been also been updated to '/home/${USER}/' to be consistent
with the cunit cross compilation instructions. It will allow users to
simply copy-paste the commands in a terminal to build OpenSSL.
Reviewed-by: Govindarajan Mohandoss <Govindarajan.Mohandoss@arm.com>
=> [PATCH v2] DEPENDENCIES: update cunit cross compilation instructions

test/performance/odp_bench_packet.c, test/validation/api/packet/packet.c
Changing the value of packet length pool parameter as twice of
TEST_MAX_PKT_SIZE (viz 2048), so that packet of length up to
2 * 2048 can be allocated from the pool.
This change is required to honour certain test cases like
"bench_packet_ref_pkt", where for 2048 byte packet test iteration,
header packet of same length is prefixed to the base packet,
leading to the failure as with current pool configuration packets
allocated from the pool can be of maximum 2048 bytes.
Signed-off-by: Harman Kalra <hkalra@marvell.com>
Defining maximum length pool parameter while create pool
to ensure packet of length max_len will never fail.
As in default pool creation, segmented_packet_len gets the
value from pool capability to allocate maximum packet length.
So …
=> [PATCH v4] Pull request for maxlen_packet_tests

test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_async.c, test/validation/api/ipsec/ipsec_inline_in.c, test/validation/api/ipsec/ipsec_inline_out.c, test/validation/api/ipsec/ipsec_sync.c
Preiously when IPsec unit tests were initialized ODP queue
and ODP pktio were created by default however ODP queue is used
by async unit tests and pktio is used by inline unit tests. Sync
unit tests use neither ODP queue or ODP pktio. This patch updates
IPsec units test initialization so that only required elements are
created for a given mode of tests.
Signed-off-by: Lukasz Bartosik <lbartosik@marvell.com>
=> [PATCH v4] validation: ipsec: improve initialization of unit tests

include/odp/api/abi-default/atomic.h, platform/linux-generic/include-abi/odp/api/abi/atomic.h, platform/linux-generic/odp_queue_lf.c
As per the GCC documentation, the 'aligned' attribute should be added
after the 'struct' keyword. Consequently, the ODP_ALIGNED attribute has
been moved in various structs of the following files:
- include/odp/api/abi-default/atomic.h
- platform/linux-generic/include-abi/odp/api/abi/atomic.h
- platform/linux-generic/odp_queue_lf.c
From the first two files, the 'Enforce alignment' comment has also been
removed since the effect of the ODP_ALIGNED macro is easy to understand.
Also, for these files, the typedef declaration has been combined
with the struct definition which is consistent with most typedef structs
in ODP source code.
Suggested-by: Petri Savolainen <petri.savolainen@nokia.com>
Reviewed-by: Govindarajan Mohandoss …
=> [PATCH v4] linux-gen: modify structs for consistency with gcc docs and odp code

platform/linux-generic/include/odp_global_data.h, platform/linux-generic/odp_fdserver.c
ODP may have other child processes in addition to fdserver,
especially, when application uses processes as worker threads.
Wait for fdserver process termination (instead of any child
process).
=> [PATCH v2] linux-gen: shm: wait fdserver with PID

.shippable.yml
Fix Shippable cloud node build by removing a broken riak apt source.
Solution suggested here:
https://github.com/Shippable/support/issues/5172#issuecomment-726399640
=> [PATCH v3] shippable: fix cloud node build

DEPENDENCIES
The instructions for cross compiling for arm64 on x86_64 platforms has
been summarized after the Cunit instructions and currently caters to only
Ubuntu/Debian distros.
Also, the formatting for the documentation section was inconsistent with
the other sections and has been modified too.
Reviewed-by: Govindarajan Mohandoss <Govindarajan.Mohandoss@arm.com>
=> [PATCH v3] DEPENDENCIES: add instructions for cross compilation for arm64 on x86_64

platform/linux-generic/include/odp_debug_internal.h, platform/linux-generic/odp_classification.c
Added per packet classification debug prints that can be enabled using the new CONFIG_DEBUG_LEVEL option.
=> [PATCH v2] Classifier debug prints

include/odp/api/spec/system_info.h, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, platform/linux-generic/arch/arm/odp_sysinfo_parse.c, platform/linux-generic/arch/mips64/odp_sysinfo_parse.c, platform/linux-generic/arch/powerpc/odp_sysinfo_parse.c, platform/linux-generic/arch/x86/odp_sysinfo_parse.c, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/include/odp_libconfig_internal.h, platform/linux-generic/include/odp_sysinfo_internal.h, platform/linux-generic/odp_libconfig.c, platform/linux-generic/odp_system_info.c, test/validation/api/system/system.c
System info may be used to retrieve various system information
with a single call. Content of the system info structure may be
extended later, but it contains initially e.g. CPU ISA family
and version.
=> [PATCH v7] api: system info call

test/performance/odp_l2fwd.c
Currently in pktout queue mode, only negative return value
causes break from pkt enqueue loop unlike in other modes where
both negative and zero return will cause the packet to be dropped.
Some platforms always return zero which can either indicate no space
in Tx or when Tx is paused due to odp_pktio_stop()(for example in
exit sequence). In such cases, current code can become an infinite loop.
So this patch fixes the same by checking for <=0 return and
break from loop if < 0 or exit is already in progress.
=> [PATCH v3] test: l2fwd: avoid tight loop in enqueue to pktout queue

include/odp/api/spec/packet_flags.h, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c
In case of IPsec packets, odp_packet_has_error() can be used to check parse
errors after IPsec processing. All IPsec errors/warnings need to be
checked using odp_ipsec_result().
=> [PATCH v6] api: packet: specify errors returned in case of IPsec

configure.ac, include/odp/api/spec/buffer.h, include/odp/api/spec/event.h, include/odp/api/spec/packet.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/odp_event.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_vector.c, platform/linux-generic/odp_pool.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/event/event.c, test/validation/api/ipsec/ipsec.c, test/validation/api/pool/pool.c, test/validation/api/scheduler/scheduler.c
This is needed for debugging e.g. when it is suspected that scheduler returns bad event handles.
=> [PATCH v5] api: add odp_event_is_valid()

.github/workflows/ci-pipeline.yml, scripts/ci/build.sh
Run ODP CI using GitHub Actions. Due to recent Travis pricing policy changes ODP
CI will be moving to GitHub Actions.
Example test run: https://github.com/matiaselo/odp/actions/runs/379008188
The initial configuration is still missing some Travis CI's features:
- Coverage test
- GH pages integration
- Doxygen warning detection
These features will be implemented in following PRs.
=> [PATCH v4] github_ci: add initial github actions configuration

example/timer/odp_timer_simple.c, test/performance/odp_timer_perf.c
Currently, the max and min timeout are being validated against the
minimum resolution supported by the timer implementation, instead
it should be validated against the required timer resolution.
Fix missing timer pool start before allocating and setting timers.
=> [PATCH v3] Pull request for timer example fixes

platform/linux-generic/odp_ipsec.c
ICV errors need to be reported as auth errors and not alg errors. All
other crypto errors can be treated as alg errors.
=> [PATCH v2] linux-gen: ipsec: report ICV errors as auth error

platform/linux-generic/odp_ipsec.c
Discard packets that fail the anti-replay check before checking
SA lifetime and updating the packet and byte counters. Previously
such packets could have been used to prematurely age an SA, leading
to a possible denial of service.
=> [PATCH v3] linux-gen: ipsec: discard replayed packets before lifetime update

platform/linux-generic/test/Makefile.am
IPsec example applications are not part of the validation test suite.
Previously, running 'make check' failed if ODP had been built without
example applications.
=> [PATCH v2] linux-gen: build: fix ipsec example application test stage

platform/linux-generic/odp_ipsec.c
All outbound crypto failures can be treated as alg errors. ICV errors
won't happen in outbound path.
=> [PATCH v2] linux-gen: ipsec: report all outb crypto failures as alg errors

example/sysinfo/odp_sysinfo.c, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, platform/linux-generic/odp_system_info.c
Use the new odp_sys_config_print() and odp_system_info()
calls.
=> [PATCH v3] example: sysinfo: use new sysinfo APIs

platform/linux-generic/odp_ipsec_sad.c
AES-GCM and AES-GMAC do not require additional padding on top of
what is required by ESP. Reduce padding to the minimum required by
ESP from the current padding of up to 15 bytes.
=> [PATCH v2] linux-gen: ipsec: fix the amount of ESP padding in AES-GCM and -GMAC

example/sysinfo/odp_sysinfo.c, platform/linux-generic/odp_ipsec.c
- Add IPsec capability printing in sysinfo example
- Remove unsupported algorithms from capabilities. After this validation test no longer complains about "Wrong auth capabilities" for AES-CCM.
The macro trick in the latter patch does not pass checkpatch but it does not seem easy to fix without making the code worse.
=> [PATCH v3] IPsec capability fixes

test/performance/Makefile.am, test/performance/odp_scheduling_run.sh, test/performance/odp_timer_perf.c, test/performance/odp_timer_perf_run.sh
Added -m option to select test mode. Added a new mode, which runs timer cancel and set operations in a loop and measures performance. Generally, timers should not expire in this mode.
=> [PATCH v6] Timer perf: test timer cancel+set rate

platform/linux-generic/odp_ipsec.c
Inline param is per packet. So the check for pktio should be done
against all members.
=> [PATCH v4] linux-gen: ipsec: fix incorrect usage of inline_param

test/validation/api/ipsec/ipsec.c
When inline IPsec processing is not supported, suite_context.pktio is set
to ODP_PKTIO_INVALID by ipsec_suite_init(). Use odp_pktio_lookup() to get
the loop pktio device handle during test termination to properly close the
device.
=> [PATCH v2] validation: ipsec: fix termination when inline processing is not supported

test/validation/api/traffic_mngr/traffic_mngr.c
CI runs the validation suite with a small number of shared CPU cores.
Increase the wait time in traffic_mngr_test_scheduler() test to avoid
occasional failures in CI test runs caused by limited CPU capacity.
=> [PATCH v2] validation: tm: increase wait time in traffic_mngr_test_scheduler()

platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, test/validation/api/scheduler/scheduler.c
Fix max scheduler group capability in basic and scalable scheduler. Add validation test case to create max number of groups.
=> [PATCH v2] Fix max sched groups

helper/Makefile.am, helper/include/odp/helper/gtp.h, helper/include/odp/helper/igmp.h, helper/include/odp/helper/ip.h, helper/include/odp/helper/odph_api.h, include/odp/api/spec/classification.h, test/validation/api/classification/classification.h, test/validation/api/classification/odp_classification_common.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/classification/odp_classification_testsuites.h
Introduce IGMP group address term.
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
Introduce ICMP identifier, code and type terms.
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
Introduce SCTP source and destination port terms.
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
Introduce GTPU tunnel endpoint identifier term.
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
Reviewed-by: Janne Peltonen …
=> [PATCH v7] api: new_cls_terms

include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_in.c
Add API to print implementation defined information about specified SA.
When SA specified is invalid, implementation may choose to print global
IPSEC configuration and other related information.
Signed-off-by: Sachin Yaligar <syaligar@marvell.com>
=> [PATCH v5] api: ipsec: add print APIs

include/odp/api/spec/ipsec.h, platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_in.c, test/validation/api/ipsec/ipsec_test_out.c
Add support for IPsec stats collection and reporting. This would allow
applications to use ODP APIs for stats collection and retrieval. Also
implementations can optimize stats reporting, which would otherwise
involve inspecting every packet and updating stats atomically.
Stats collection can be disabled using the 'stats_en' option added in
odp_ipsec_config_t.
Signed-off-by: Vidya Velumuri <vvelumuri@marvell.com>
=> [PATCH v14] api: ipsec: add IPsec stats

include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
In some ODP implementations, plain queues might be using software
primitives such as a simple ring and the ODP timer hardware pools
can enqueue timeouts only into schedule queues.
Introducing capability `queue_type_sched` and `queue_type_plain`
which define the queue types that can be the destination of the
timeout events.
Add support for the new timer pool destination queue type
capability.
Check timer pool capability and set tests as inactive if destination
queue type is not supported.
=> [PATCH v16] api: timer: add timer pool queue capability

include/Makefile.am, include/odp/api/protocols.h, include/odp/api/spec/ipsec.h, include/odp/api/spec/protocols.h, platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec_test_out.c
The proposed API, odp_ipsec_sa_info(), allows application to check
parameters associated with an IPsec SA. Retrieved information
covers constant fields that application had provided while
creating session (like details of cipher choices) and variables
associated with IPsec (like sequence number, anti-replay parameters).
Also, this API allows application to check session constants which
implementation is allowed to update based on the support available
(like anti-replay window)
This pull request consists of:
1. The API spec update for odp_ipsec_sa_info()
2. An implementation of odp_ipsec_sa_info() for linux-generic platform
3. An oubound test function to verify the API.
=> [PATCH v13] api: ipsec: add odp_ipsec_sa_info

include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_out.c
This PR contains an updated version of the API change from PR 1137 and linux-gen implementation. A validation test would conflict with PR 1060 and is therefore left out from this PR.
@anoobj, I changed the API text as proposed by Petri and also tweaked the commit message. Please check that it is ok for you.
=> [PATCH v5] api: ipsec: allow L2 hdr to be provided in packet for inline outbound operation

configure.ac, include/odp/api/spec/pool.h, platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/include/odp_ring_internal.h, platform/linux-generic/odp_pool.c, test/validation/api/pool/pool.c
V2:
- Added new `odp_pool_stats_t.alloc_fails` counter and clarified definitions of several other counters
- Tweaked `odp_pool_stats()` and `odp_pool_stats_reset()` documentations
=> [PATCH v8] api: pool: add support for statistics and indexes

test/validation/api/classification/odp_classification_test_pmr.c
Factor out repetitive test mechanics code from individual PMR test cases so that the test cases become more readable and maintainable.
This PR introduces 1 commit on top of PR #1121 and needs to be rebased after PR 1121 has been merged.
~~This PR introduces 3 commits on top of PR #1121 and needs to be rebased after PR 1121 is done.~~
~~The first new commit (f73f0312f) could be put in before PR 1121 if PR 1121 would then absorb the last two commits (i.e. reshaping the corresponding validation commits). Or if PR 1121 goes in its current form, then the two cleanup commits in this PR can be squashed and PR 1121 could still do the changes of the middle commit (9b8a734db).~~
=> [PATCH v3] Classifier validation test cleanup

platform/linux-generic/include/odp_buffer_internal.h, platform/linux-generic/odp_buffer.c, platform/linux-generic/odp_packet.c
Packet print function used buffer_snprint, which assumed
that event type is buffer and printed an error on packets.
Re-implemented buffer and packet print functions to not
use buffer_snprint.
=> [PATCH v2] linux-gen: packet: fix packet print

test/validation/api/pktio/pktio.c
During pool creation segment length (param.pkt.seg_len) gets
initialised with max segment length possible (which could go
up to max packet length supported in case of single segmented
buffer), while packet length (param.pkt.len) value gets
initialised with PKT_BUF_SIZE. With this initialisation
seg length becomes much greater than packet length i.e.
(param.pkt.seg_len > param.pkt.len).
With given pool params, expectation is to support param.pkt.num
packets of param.pkt.len with first buffer segment size as
param.pkt.seg_len, which is not feasible.
Signed-off-by: Harman Kalra <hkalra@marvell.com>
=> validation: pktio: fix segment length pool param

platform/linux-generic/odp_packet.c
seg_len, seg_data and ref_cnt fields appear on the same line and unequally
spaced when printed. These formatting issues have been fixed so that it is
consistent with the other printed fields.
=> [PATCH v3] linux-gen: packet: fix formatting in odp_packet_print()

config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_thread.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf
Add system:thread_count_max config parameter that can be used to reduce
the maximum number of threads below the build time configured maximum.
This can be used to reduce thread related resource consumption such
as thread-local memory.
Most code still uses the build time limit, ODP_THREAD_COUNT_MAX, so this
change merely enables possible later optimizations in those cases.
ODP-DPDK will already benefit from this change as the number of queue
pairs for a crypto device can be lowered to match the actual number of
threads without ODP-DPDK having worry about possible sharing of the
queue pairs between threads.
=> [PATCH v3] linux-gen: thread: read maximum number of threads from config file

platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp_cpu.h, platform/linux-generic/arch/aarch64/odp_cpu_idling.h, platform/linux-generic/arch/arm/odp_cpu.h, platform/linux-generic/arch/arm/odp_cpu_idling.h, platform/linux-generic/arch/default/odp_cpu.h, platform/linux-generic/arch/default/odp_cpu_idling.h, platform/linux-generic/arch/x86/odp_cpu.h, platform/linux-generic/include/odp_chksum_internal.h, platform/linux-generic/odp_chksum.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_queue_scalable.c, platform/linux-generic/odp_schedule_scalable.c, test/validation/api/chksum/chksum.c
```
linux-gen: improve software checksum implementation
Improve software checksum implementation and put it in a separate
header file so that it may be easily called from multiple places.
linux-gen: packet: use new software checksum functions
Use new software checksum functions and clean up the related code.
```
v1:
- Draft.
- Probably need to revise usage of __ARM_FEATURE_UNALIGNED macro.
v2:
- Include "introduce _ODP_UNALIGNED" commit.
- Use _ODP_UNALIGNED instead of __ARM_FEATURE_UNALIGNED.
v3:
- Add arch/x86/odp_cpu.h in linux-generic/Makefile.am.
- Rebase.
v4:
- Add "linux-gen: include odp/api/cpu.h where odp_cpu_pause() is called".
v5:
- Add _ODP_UNALIGNED also for arch/arm. …
=> [PATCH v9] linux-gen: improve software checksum implementation

example/traffic_mgmt/odp_traffic_mgmt.c
Prevent failure if _GNU_SOURCE has been already defined.
Reviewed-by: Jere Leppänen <jere.leppanen@nokia.com>
=> [PATCH v1] example: tm: prevent redefinition of _GNU_SOURCE

platform/linux-generic/odp_hash_crc_gen.c
Make it explicit that unsigned integers are used with
bitwise operators. Fixes static code checker complains about:
"bitwise operators should not be applied to signed operands".
=> [PATCH v2] linux-gen: crc: unsigned integer with bitwise operators

test/performance/odp_sched_latency_run.sh, test/performance/odp_scheduling_run.sh
Scheduling performance and latency test applications are run multiple times
during 'make check' with a different number of worker threads. Skip test
runs if there are not enough CPU cores available.
=> [PATCH v2] test: performance: skip duplicate test runs

test/validation/api/pktio/pktio.c
GCC 9.3.0 on Ubuntu 20.04 doesn't recognize CU_ASSERT_FATAL() correctly in
-O1 optimization level causing build to fail on 'pktio[0] may be used
uninitialized in this function' error. Fix this by initializing pktio array
to zero.
=> [PATCH v2] validation: pktio: fix gcc -O1 build failures

DEPENDENCIES
Instructions for installing various RPM-based packages were missing and
have been added. For CentOS/Red Hat systems, some packages require the
installation of Fedora EPEL package. For CentOS 8 systems, the powertools
repository must be enabled to install the libconfig-devel, doxygen and
CUnit-devel packages. These additional steps have also been captured in the
file.
=> [PATCH v2] DEPENDENCIES: add instructions for installing RPM-based packages

.gitignore, configure.ac, doc/application-api-guide/examples.dox, example/Makefile.am, example/cli/.gitignore, example/cli/Makefile.am, example/cli/odp_cli.c, example/cli/odp_cli_run.sh, example/m4/configure.m4, helper/Makefile.am, helper/cli.c, helper/include/odp/helper/autoheader_external.h.in, helper/include/odp/helper/cli.h, helper/include/odp/helper/odph_api.h, helper/include/odp/helper/odph_debug.h, helper/libodphelper.pc.in, helper/m4/configure.m4, helper/m4/libcli.m4, helper/test/.gitignore, helper/test/Makefile.am, helper/test/cli.c, helper/test/debug.c, include/odp/autoheader_external.h.in, platform/linux-generic/m4/configure.m4
```
helper: add CLI helper API and implementation
CLI helper API allows starting and stopping ODP CLI server, which may
be connected to using a telnet client. CLI commands may be used to get
information from an ODP instance, for debugging purposes.
This implementation depends on libcli. If libcli is not available, CLI
helper is automatically excluded.
helper: test: implement CLI helper test
Test CLI helper by starting and stopping the ODP CLI server.
example: add CLI helper example
This example shows how to start and stop ODP CLI using the CLI helper
API functions.
```
v2:
- Fix missing initializer.
- Add configure option …
=> [PATCH v9] helper: add CLI helper API and implementation

include/odp/api/spec/atomic.h
Specify explicitly that atomic CAS operations are strong (do not return failure spuriously). This goes on top of PR 1080.
=> [PATCH v2] api: atomic cas strong

include/odp/api/spec/ipsec.h
Allow implementations to perform additional post-processing in
odp_ipsec_result(). If applications consumes packet data without
checking IPsec result status, the behavior is undefined.
=> [PATCH v4] api: ipsec: allow IPsec post-processing in odp_ipsec_result()

include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_out.c
With IPSEC implementations, the protocol specific fields
like sequence number is not exposed to the application.
But for debugging as well as for validation, finer control
of such fields would be required. The proposed API,
odp_ipsec_test_sa_update(), would allow access to such
fields which are not expected to be exposed in the data
path.
=> [PATCH v10] api: ipsec: test sa update

include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec_test_out.c
Define default values for more fields of odp_ipsec_sa_param_t so that applications do not always have to explicitly initialize as many fields after the odp_ipsec_sa_param_init() call.
The current validation tests do not actually set all the parameters that they should. It can cause test failures in implementations that set the implementation-defined values differently from linux-gen. This API change makes the needed fix there smaller.
=> [PATCH v6] api: ipsec: define more default values & improve SA info API

configure.ac
Backward-incompatible:
- IPsec post-processing happens in the odp_ipsec_result() function that
must be called at least once before packet data or metadata may be
accessed.
Backward-compatible:
- New 128-bit atomic operations: init, store, load, and CAS
- Clarify that atomic CAS operations are strong type
- New odp_ipsec_test_sa_update() function for SA testing
- odp_ipsec_sa_info() may return non-exact copy of SA parameters
- Specify default values for more IPsec SA parameter fields
- Changed odp_timer_alloc() user context pointer argument to const
- New odp_timer_pool_print() function for printing timer pool debug
information
- New odp_timer_print() function for printing timer debug information
- New odp_timeout_print() …
=> [PATCH v1] api: increment ODP API version to 1.27.0

platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_sp.c
Static code checker complains about empty functions. Add a line
of code or a comment into each function.
=> [PATCH v2] linux-gen: schedule: comment empty functions

test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_out.c
Add test routine to verify udp_encap with tunnel mode
for IPv4 and IPv6 for various algorithms
Signed-off-by: Narayana Prasad <pathreya@marvell.com>
=> [PATCH v6] validation: ipsec: add test routine to verify udp_encap

helper/Makefile.am, helper/check-globals.sh, platform/Makefile.inc, platform/linux-generic/Makefile.am, platform/linux-generic/check-globals.sh, platform/linux-generic/include/odp_errno_define.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/include/odp_timer_internal.h, platform/linux-generic/odp_errno.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_timer.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/io_ops.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_common.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/pktio/stats/sysfs_stats.c, platform/linux-generic/pktio/tap.c, scripts/check-globals.sh
```
check names of global symbols in static libraries
Add tests to check that global symbols in static libodp-linux and
libodphelper conform to certain prefix patterns.
linux-gen: rename remaining global symbols in the static library
Rename the rest of the global symbols in the static library that do
not have the "_odp_" prefix.
```
v2:
- Fix indentation in dpdk.c.
- Rebase.
v3:
- Log the regex being used.
- Add "fixes" tags.
v4:
- Make CHECK_GLOBALS_REGEX more legible.
- Add commit "build: make export-symbols-regex more legible".
v5:
- Add "build:" to subject line of second commit.
- Add reviewed-by tags.
- Rebase.
=> [PATCH v5] linux-gen: rename remaining global symbols in the static library

platform/linux-generic/odp_ishm.c
Conditional evaluation (right-hand side of ||) should not contain
side effects. A code checker complained about this.
=> [PATCH v2] linux-gen: shm: move index increment

platform/linux-generic/odp_ipsec_sad.c
The usage of odp_atomic_store_* APIs seems to be inconsistent in
IPsec control path during the odp_ipsec_sa_create() function,
so replaced these with odp_atomic_init_* APIs for consistency.
Signed-off-by: Mahipal Challa <mchalla@marvell.com>
=> [PATCH v3] linux-gen : ipsec: fix the usage of odp_atomic_store_* APIs

.checkpatch.conf, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_fdserver.c, platform/linux-generic/odp_init.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, platform/linux-generic/odp_ishm.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_scalable.c, platform/linux-generic/odp_rwlock.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_scalable_ordered.c, platform/linux-generic/odp_schedule_sp.c, platform/linux-generic/odp_system_info.c, platform/linux-generic/odp_timer.c, platform/linux-generic/odp_timer_wheel.c, platform/linux-generic/odp_traffic_mngr.c, scripts/checkpatch.pl, scripts/spelling.txt
Update checkpatch and spelling files from Linux. Disable C99 comment (//) tolerance. Fix various checkpatch warnings on white spaces, braces and typos platform/linux-generic C files.
=> [PATCH v2] Checkpatch update and fixes

example/ipsec_crypto/odp_ipsec_stream.c
Report failure in verifying output stream in case the received
packets are not IPsec processed as configured.
Without this, the verify succeeds even when the input stream
is directly forwarded to the output interface of the stream entry.
=> [PATCH v3] example: ipsec: fix verification of output stream

test/miscellaneous/odp_api_from_cpp.cpp
Test odp_api_from_cpp may call odp_init_[global,local] so that
platform specific initialization (eg tracing ODP API calls) can be
executed as well.
Signed-off-by: Gowrishankar Muthukrishnan <gmuthukrishn@marvell.com>
=> [PATCH v2] test: call global and local init in odp_api_from_cpp

.github/workflows/ci-pipeline.yml
Add build only tests for all compiler optimization levels. Additionally,
enable helper debug code and print (--enable-debug=full).
V3:
- Removed duplicate test for -O2
=> [PATCH v3] github_ci: add build tests for missing compiler optimization levels

platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec_test_out.c
- linux-gen: ipsec: increase the maximum number of SAs
- linux-gen: ipsec: do not alloc per-thread memory for too many threads
- validation: ipsec: test maximum number of SAs
- validation: ipsec: enable antireplay service and lifetimes
- linux-gen: crypto: increase the maximum number of sessions to 4000
Also, update copyrights in the affected files not only for this change but for earlier changes for which the update was not done.
This PR depends (logically, not textually) on PR 1188 (api: ipsec: define more default values & improve SA info API).
=> [PATCH v3] Increase the maximum number of IPsec SAs and crypto sessions

platform/linux-generic/include/odp_random_openssl_internal.h, platform/linux-generic/odp_random.c, platform/linux-generic/odp_random_openssl.c
```
Not all bits returned by _odp_random_openssl_test_data() are random,
depending on RAND_MAX. And OpenSSL doesn't seem to provide repeatable
random bits.
Remove _odp_random_openssl_test_data() and use
_odp_random_std_test_data() instead.
```
v2:
- Added reviewed-by: Petri.
=> [PATCH v2] linux-gen: random: remove _odp_random_openssl_test_data()

test/validation/api/pktio/pktio.c
On the AWS Graviton2, the reported HW frequency in MHz is not an integer
value. The ODP time APIs assume integer values for the HW frequency and
perform integer arithmetic to calculate time from the HW frequency.
Performing integer arithmetic on this floating point HW frequency value
in odp_pktio_ts_from_ns() test results in a truncated value causing an
assertion failure. The simplest solution, which avoids major changes to
the ODP time APIs and structs, is to change the value of PKTIO_TS_CMP_RES
to 2 and increase the arithmetic tolerance for the odp_pktio_ts_from_ns()
test.
=> [PATCH v3] validation: pktio: increase PKTIO_TS_CMP_RES tolerance

example/packet/Makefile.am, example/timer/Makefile.am, helper/test/Makefile.am, platform/linux-generic/test/Makefile.am, scripts/ci/distcheck.sh, test/performance/Makefile.am, test/validation/api/Makefile.am
```
ci: use multiple jobs for distcheck
Use $(nproc) jobs to run distcheck in CI.
Signed-off-by: Jere Leppä?nen <jere.leppanen@nokia.com>
don't run tests in parallel
Explicitly prevent tests from being run in parallel when the -j option
is used with make check.
Using the .NOTPARALLEL special target is the only easy way to ensure
that tests are run one by one. Unfortunately this also prevents
parallel builds for the tests.
Signed-off-by: Jere Leppä?nen <jere.leppanen@nokia.com>
```
v2:
- Add "build:" tag to subject line of first commit.
- Rebase.
- Add reviewed-by tags.
=> [PATCH v2] don't run tests in parallel

configure.ac
```
Place user provided options at the end of CFLAGS, CXXFLAGS and
LDFLAGS, so that they override other options.
This way we also don't have to refrain from using the -march option
just because user has provided some CFLAGS.
```
v2:
- Add reviewed-by tag.
- Rebase.
=> [PATCH v2] configure: allow user to override *FLAGS

platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c
Added part numbers for Cortex-A78 and Neoverse CPUs.
=> [PATCH v2] linux-gen: arch: add ARM part numbers

test/validation/api/traffic_mngr/traffic_mngr.c
The traffic_mngr_shaper_test intermittenly fails on arm64 systems. For
enabling the CI, this test has been skipped until the issue is resolved
and the shaper test no longer fails on arm64 platforms.
=> [PATCH v6] validation: traffic_mngr: skip shaper test on arm64 systems

.github/workflows/ci-pipeline.yml
Ubuntu 16.04 is reaching EOL in April. Save CI resourches by testing only
compilation with this OS.
=> [PATCH v2] github_ci: change ubuntu 16.04 test to build-only

platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp_atomic.h, platform/linux-generic/arch/default/odp_atomic.h, platform/linux-generic/arch/default/odp_cpu.h, platform/linux-generic/odp_queue_lf.c
odp_queue_lf.c and odp_bitset.h contain aarch64 specific code which causes the build to fail on arm4 systems when the --disable-host-optimization flag is enabled. These patches separate out the default and aarch64 specific code to the arch-specific files and resolve the build issues.
=> [PATCH v11] linux-gen: queue_lf: move aarch64 specific code to arch files

m4/odp_dpdk.m4
DPDK PMD driver rte_pmd_octeontx2 has dependency to libm.
=> [PATCH v2] m4: odp_dpdk: add missing libm dependency

.github/workflows/ci-pipeline.yml, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/test/sched-basic.conf
Fix max queues assert calculation. Add a CI job to build and and run ODP init (hello world) with an odd number of spread queues.
=> [PATCH v2] linux-gen: fix sched max queues assert

.github/workflows/coverity.yml, scripts/ci/coverity.sh
Add just an Ubuntu20.04 Coverity job scheduled daily, as for static analysis we don't need multiple different build. The build is without DPDK as we don't need that for static analysis.
Signed-off-by: Juraj Linkeš <juraj.linkes@pantheon.tech>
=> [PATCH v7] github_ci: add Coverity job and script

platform/linux-generic/arch/aarch64/odp_atomic.h, platform/linux-generic/arch/arm/odp_atomic.h, platform/linux-generic/arch/default/odp_atomic.h, platform/linux-generic/include/odp_bitset.h
On arm64 systems, the build fails with the --disable-host-optimization
compiler flag as it is unable to locate definitions of lockless APIs
used in atomic bit operations since these declarations are present in
arch/aarch64/odp_atomic.h files Consequently, the aarch64 specific code
has been moved to the arch-specific file while the reminder code has been
moved under the default linux-generic implementation.
=> [PATCH v5] linux-gen: bitset: move aarch64 specific code to arch files

.github/workflows/coverity.yml
Downloading the Coverity image failed due to a typo in the image path.
=> [PATCH v1] github_ci: fix typo in coverity docker image path

platform/linux-generic/pktio/loop.c, test/validation/api/pktio/pktio.c
Loop interface supports loopback mode by definition.
=> [PATCH v2] linux-gen: loop: support loopback mode in capability

CHANGELOG, configure.ac
Backward-incompatible:
- New crypto capabilities for defining if a queue type (scheduled/plain)
can be used as a crypto completion event destination
Backward-compatible:
- New TX completion event type and related functions
- New packet APIs for requesting packet TX completion events
- New packet APIS for requesting packet TX drop based on packet age
- New odp_cls_print_all() function for printing implementation specific
debug information about all classifier rules
- New enumerations for ARMv8.7-A, ARMv9.0-A, ARMv9.1-A, and ARMv9.2-A ISA
versions
=> [PATCH v4] api: increment ODP API version to 1.28.0

platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_in.c, test/validation/api/ipsec/ipsec_test_out.c
This commit has several patches that clean up the IPsec validation test code and also fix a couple of issues in there. There is also one small change in linux-gen, made possible by a fix in the validation code.
The main change is to decouple the combined output+input tests from the lower level generic test code that will now invoke and check one IPsec packet operation at a time. Combining several operations in one test is now done at the test case level.
@anoobj could you perhaps review these changes and consider rebasing your reassembly validation code on top of this if things look ok?
=> [PATCH v2] IPsec validation test cleanup

platform/linux-generic/Makefile.am, platform/linux-generic/arch/x86/odp/api/abi/hash_crc32.h, test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_crc.c
```
linux-gen: hash: use x86 crc32 instructions
Use x86 SSE 4.2 crc32 instructions via gcc builtin functions, if
available. These instructions support crc32c only.
test: perf: implement crc throughput test
This test measures megabytes per second throughput of the
odp_hash_crc32() and odp_hash_crc32c() API functions.
```
=> [PATCH v4] linux-gen: hash: use x86 crc32 instructions

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c
Increase max_segments capability to 64 segments. Increase max_payload_len capability to be closer to MTU.
=> [PATCH v1] linux-gen: pktio: update LSO capabilities

include/odp/autoheader_external.h.in, platform/linux-generic/arch/aarch64/odp/api/abi/cpu.h, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_cpu.m4, platform/linux-generic/odp_system_info.c, test/validation/api/system/system.c
Detect CPU cache line size automatically on aarch64 systems when abi-compatibility is disabled. Automatic cache line size detection is disabled when cross-compiling.
V2:
- Validation test fix
=> [PATCH v3] linux-gen: detect cpu cache line size during configure

helper/cli.c, helper/test/linux/process.c, include/odp/api/spec/init.h, platform/linux-generic/include/odp/api/plat/thread_inlines.h, platform/linux-generic/include/odp_debug_internal.h, platform/linux-generic/odp_init.c, platform/linux-generic/odp_thread.c, test/validation/api/Makefile.am, test/validation/api/init/.gitignore, test/validation/api/init/Makefile.am, test/validation/api/init/init_main.c
```
api: introduce per-thread log function
The odp_log_thread_fn_set() API allows the caller to set a per-thread
log function. This log function is called to do output when the thread
calls other API functions.
linux-gen: implement odp_thread_set_log_fn()
Implement the odp_thread_set_log_fn() API function.
helper: cli: direct prints to the CLI user instead of the log
Use the odp_log_thread_fn_set() API to direct prints from API calls to
the CLI user.
validation: init: test thread-specific log function
Test that a thread-specific log function is called if and only if it
is set.
Signed-off-by: Jere Leppänen …
```
=> [PATCH v8] api: introduce per-thread log function

test/validation/api/packet/packet.c
According to the spec packet pull head/tail may pull up to segment
length minus 1 bytes. Fix the tests to align to the spec.
=> [PATCH v3] validation: packet: fix packet head/tail pull lengths

CHANGELOG, configure.ac
- Modified packet IO statistics counters (odp_pktio_stats_t) definitions
- Deprecated packet IO statistics field odp_pktio_stats_t.in_unknown_protos
- New APIs for inline fragmentation reassembly offload for packet input and
IPsec
- New odp_log_thread_fn_set() function for setting a thread specific log
function
- New packet IO statistics counters
odp_pktio_stats_t.in_packets/out_packets
=> [PATCH v2] 1.29.0.0 release

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, scripts/ci/build.sh, scripts/ci/build_arm64.sh, scripts/ci/check.sh, scripts/ci/check_inline_timer.sh, scripts/ci/check_pktio.sh
To enable the arm64 CI, ci-pipeline-arm64.yaml file has been added
with approximately 40+ jobs. Some of the CI scripts were also
modified to add an ARCH environment variable for allowing native
arm64 builds for the jobs.
Jobs have been restricted to only run when the repo is owned by
OpenDataPlane. This is to prevent the CI triggering on forks of the
project where Graviton2 self-hosted runners are not available.
Signed-off-by: Dean Arnold <dean.arnold@arm.com>
=> [PATCH v8] github_ci: enable native arm64 ci jobs

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
Run x86_64 tests with debug build too to catch issues that e.g. trigger
asserts in the ODP implementation. Add debug build flag in the existing
--enable-deprecated test configuration to avoid increasing the number
of test runs.
The coverage test does already use debug build, but this change makes
the debug build explicitly part of the common test run and makes
possible error reports hopefully more clear.
=> [PATCH v3] github_ci: run x86_64 tests with debug build too

helper/ipsec.c
Currently, the alg check function uses odp_crypto_*_capability
API to get the number of capability entries for a specific algorithm.
This is incorrect. Replacing the use of crypto capability APIs with
the correct IPsec APIs.
=> [PATCH v2] helper: ipsec: fix capability API usage

helper/cli.c
```
helper: cli: fix odph_cli_start() error handling
When encountering an error in odph_cli_start(), close only file
descriptors that are open, and free shm.
helper: cli: remove "show" commands
"call odp_sys_info_print" command provides the same information as
"show cpu" and "show version" commands. Remove the redundant "show"
commands.
helper: cli: add command "call odp_cls_print_all"
Add a CLI command, which calls the new odp_cls_print_all() API
function.
helper: cli: add command "call odp_queue_print_all"
Add a CLI command, which calls the new odp_queue_print_all() API
function.
Signed-off-by: Jere Leppänen …
```
=> [PATCH v2] helper: cli: add commands for new *_print_all() functions

test/performance/odp_ipsec.c
This fix enables the use of -s option for odp_ipsec performance test app
=> [PATCH v4] test: performance: ipsec: Fix for ipsec schedule mode to work

.github/workflows/ci-pipeline-arm64.yml
ABI compatibility default value has been changed to disabled, so modify the
arm64 test cases accordingly. Most of the test cases are now run with ABI
compatibility disabled, as this is more common with real word applications.
=> [PATCH v2] github_ci: abi compatibility is disabled by default

test/validation/api/scheduler/scheduler.c
The default value for odp_schedule_config_t.max_flow_id should be zero.
=> [PATCH v2] validation: scheduler: add check for max_flow_id default value

example/ipfragreass/odp_ipfragreass_reassemble.c
At the time of fragmentation, packet length is increased using
odp_packet_extend_head() to make room for header in the fragments.
So during re-assembly, odp_packet_trunc_head() needs to be used
instead of odp_packet_pull_head() to strip off the header to
handle possible packet segmentation that may happen inside
odp_packet_extend_head().
=> [PATCH v2] example: ipfragreass: fix packet length adjustment during reassembly

test/validation/api/packet/packet.c
In packet test cases for headroom/tailroom, extend head/tail
APIs are always called with extend length greater than
headroom/tailroom. Also trunc head/tail APIs are always
called with truncate length greater than or equal to segment
length.
In these cases, the spec allows the implementation to change
the layout of the packet completely if required. So properties
of the output packet like segment lengths, headroom, tailroom
etc. can be entirely different from those of the input packet
and should not be compared with each other.
Also, comparison of older pointers from input packet with new
pointers from output packet should be done only if the return
value of these APIs is 0 as otherwise the older pointers are to
be considered invalid. …
=> [PATCH v4] validation: packet: fix verification for trunc/extend tests

config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Add new config file parameters to control how original input queue
order is maintained during asynchronous IPsec processing.
When asynchronous IPsec operations are started within an ordered
scheduling context, packet order is maintained in IPsec completion
queues but the order in which the sequence number gets assigned or
the anti-replay check done is not guaranteed. This commit adds a config
option to force the stateful part of IPsec processing to be done in the
correct order, at the cost of reduced parallelism.
The ordering mechanism added in this commit uses the order_lock method
of the internal scheduling API to stop the calling thread until it
is its turn (i.e the preceding scheduling contexts associated with the
same input queue have been released). Future commits may add more …
=> [PATCH v4] linux-gen: ipsec: add configurable ordering mode

example/ipsec_api/Makefile.am, example/ipsec_api/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_stream.c
example: ipsec: fix content of ESP padding bytes
Fix ESP padding so that it is filled with an increasing counter value
as specified by the ESP RFC. Incorrect (zeroed) padding caused the ESP
packets to be rejected by the IPsec offload of the linux-gen ODP.
Fixes: https://github.com/OpenDataPlane/odp/issues/1167
=> [PATCH v5] Ipsec example padding fix

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_name_table.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_traffic_mngr.c, test/common/odp_cunit_common.c, test/common/odp_cunit_common.h, test/validation/api/traffic_mngr/traffic_mngr.c
commit 03db2a3cb430937694c752581185020d2b9049ff
Date:   Sat Mar 27 14:40:44 2021 +0530
linux-generic: pktio: add internal API to configure pktout for TM
Add internal routine to support configuring pktout when in TM mode.
commit 9127eb2fd70eca739c7213ae1f188a353dd10234
Date:   Thu Nov 5 06:22:55 2020 +0530
linux-gen: tm: fix issues related to name table cleanup
Name table entry was not cleaned up properly in destroy path
of tm profile/node/system. This patch fixes the same.
commit fd3d1acb96103fd74809121788eafc1935af9007 …
=> [PATCH v4] traffic_mngr: linux-gen and validation compliance fixes.

platform/linux-generic/include/odp_debug_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_comp.c, platform/linux-generic/odp_ishm.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_scalable.c, platform/linux-generic/odp_system_info.c, platform/linux-generic/odp_timer.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/pktio_common.c
```
linux-gen: fix print formats
Fix mismatches between print formats and parameters in ODP_PRINT(),
ODP_DBG(), etc. calls.
linux-gen: debug: check print formats and parameters
Format strings and parameters in ODP_LOG(), ODP_PRINT(), etc. calls
have not been cross-checked during compilation for some time due to
commit b776ca47c0d8 ("linux-generic: debug: use global fn ptr for
logging fn"). Enable this checking.
```
=> [PATCH v3] linux-gen: fix print formats and enable compile-time checking

platform/linux-generic/odp_packet_io.c
Addition of_odp_pktio_pktout_tm_config() introduced a new print
format error, which breaks the build currently. Print format check
was merged after the new code (and bug) was merged.
=> [PATCH v1] linux-gen: pktio: fix print format

test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_in.c, test/validation/api/ipsec/ipsec_test_out.c
This PR depends on PR 992 (api: reassembly) and adds one commit on top of it. The commit reduces code duplication and makes reassembly test case code simpler as suggested in the review of PR 992. @anoobj please review.
v2: Rebased on top of latest master that now includes PR 992 commits.
=> [PATCH v7] validation: ipsec: reduce code duplication in reassembly test cases

example/debug/odp_debug.c
Currently, the max and min timeout are being configured with the
minimum resolution supported by the timer implementation, instead
retrieve the resolution and min timeout supported for the given
max timeout and configure them accordingly.
=> [PATCH v6] example: debug: fix timer pool configuration

test/validation/api/ipsec/ipsec.c
For some AH tests, esp check function is used which does not check the
AH capability. Use the ah check function which checks for AH capability.
Signed-off-by: Vidya Sagar Velumuri <vvelumuri@marvell.com>
=> [PATCH v2] validation: ipsec: fix check function for ah tests

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, scripts/ci/coverage.sh, test/common/odp_cunit_common.c, test/common/odp_cunit_common.h, test/validation/api/pktio/pktio.c
Add test where (in addition to packet input) application sends events into pktin event queue. Scalable scheduler needs bug fixes (or further development) to support this. CI is disabled to run checks on scalable until it is fixed.
=> [PATCH v3] validation: pktin event queue

example/traffic_mgmt/odp_traffic_mgmt.c, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
Depends on below series in order:
1. #1234 
commit a1a8a434f111ed1180102b82d2ced898c70bd14e
Date:   Wed Dec 30 00:02:07 2020 +0530
api: tm: deprecate shaper cir and pir bps fields
Deprecate commit_bps and peak_bps fields as they only related to
byte mode and not packet mode. Instead commit_rate and peak_rate fields
can be used in odp_tm_shaper_params_t
commit 1f641ef097927992fc41ee4099a03ba5ed5b841f
Date:   Wed Dec 30 00:16:38 2020 +0530
validation: tm: use commit_rate and peak_rate in shaper params
Use commit_rate and peak_rate in odp_tm_shaper_params_t instead of
commit_bps and peak_bps.
Signed-off-by: Nithin Dabilpuram …
=> [PATCH v3] api: tm: support shaper packet mode

example/traffic_mgmt/odp_traffic_mgmt.c, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
Depends on series in order:
1. https://github.com/OpenDataPlane/odp/pull/1234
2. https://github.com/OpenDataPlane/odp/pull/1235
commit 358c96f4d80dc71f30b71270bf3525c936525aa7
Date:   Wed Nov 4 19:36:31 2020 +0530
validation: tm: use tm start and stop API
Add tm start API after creating a TM system and TM stop API before
destroying it.
commit 3f46857434bb0922b1cc4dd80d01accdd7586642
Date:   Wed Nov 4 19:23:55 2020 +0530
example: tm: use TM start and stop
Use TM start to start the TM system after creation and
TM stop to stop it before destroying TM queues.
commit …
=> [PATCH v12] api: tm: add start and stop tm API

include/odp/api/spec/packet_io.h
Specify explicitly that application may enqueue to packet input
side event queues, and cannot dequeue from output side event
queues.
=> [PATCH v2] api: pktio: clarify event queue specification

include/odp/api/spec/ipsec.h, platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec_test_out.c
Update IPsec stats with "success bytes" representing total bytes of data processed in success cases.
=> [PATCH v3] api: ipsec: include success bytes in stats

platform/linux-generic/odp_fdserver.c, platform/linux-generic/odp_ishmpool.c, scripts/ci/coverage.sh
```
ci: fix misspelled CFLAGS in coverage.sh
linux-gen: fdserver: check unix socket path length
Make sure that path length is within the sockaddr_un::sun_path limit
when connecting unix sockets.
linux-gen: shm: avoid potential integer overflow
In _odp_ishmbud_alloc(), avoid integer overflow when calculating the
maximum allocation size.
```
=> [PATCH v2] misc fixes

include/odp/api/spec/time.h, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp/api/abi/cpu_time.h, platform/linux-generic/arch/aarch64/odp_global_time.c, platform/linux-generic/arch/default/odp/api/abi/cpu_time.h, platform/linux-generic/arch/default/odp_global_time.c, platform/linux-generic/arch/x86/odp/api/abi/cpu_time.h, platform/linux-generic/include/odp/api/plat/time_inlines.h, test/validation/api/time/time.c
I named these functions "strict" due to they maintain program order more strictly than the basic functions. Other terms like precise/exact/etc would likely promise too much about when a time stamp is actually taken. This flavor of calls use more barriers/etc instructions to maintain program order than the basic calls (and thus hurt performance more), but may not still be able to guarantee 100% program order (if ISA does not allow it, or if it is impractical).
=> [PATCH v4] api: time: add strict time stamp read functions

example/debug/odp_debug.c, example/sysinfo/odp_sysinfo.c, example/timer/odp_timer_accuracy.c, example/timer/odp_timer_simple.c, example/timer/odp_timer_test.c, include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/performance/odp_sched_pktio.c, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
I moved clock source enumeration patches into this PR from the tick info PR. I think it makes sense to add rename CPU to DEFAULT  clock source at the same time.
=> [PATCH v4] api: timer: add clock src enumerations

configure.ac, example/cli/odp_cli.c, helper/cli.c, helper/include/odp/helper/cli.h, helper/test/cli.c
```
helper: cli: try to avoid closing reused file descriptors
The only way to stop cli_loop() is to close the socket. But after
closing, cli_loop() still uses or closes the file descriptor, which is
a problem if the file descriptor has already been reused.
Try to avoid this problem by using dup2() to switch to a higher file
descriptor number. Also avoid double closes outside cli_loop() with a
couple of small tweaks.
helper: cli: add user command functions
Allow user to register CLI commands with a name, function, and an
optional help text.
helper: increment library version to 1.0.7
Increment helper library version number due to changes in CLI helper
API.
Signed-off-by: Jere …
```
=> [PATCH v9] helper: cli: add user command functions

CHANGELOG, configure.ac
- traffic manager: add option to enable packet mode shaper (packets per
second as opposed to bits per second)
- packet io: specify explicitly that an application may enqueue to packet
input side event queues, and cannot dequeue from output side event queues
- ipsec: include success bytes in stats (odp_ipsec_stats_t.success_bytes)
- time: added new time stamp read functions which read time stamp value
more strictly in the program order: odp_time_local_strict(),
odp_time_local_strict_ns(), odp_time_global_strict(),
odp_time_global_strict_ns()
- timer: added new default clock source enumeration ODP_CLOCK_DEFAULT
(=ODP_CLOCK_SRC_0) and support for multiple clock sources
(ODP_CLOCK_SRC_1, ODP_CLOCK_SRC_2...). …
=> [PATCH v1] api: increment ODP API version to 1.30.0.0

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c
Patch series adds support for larger anti-replay window sizes.
The maximum supported AR window size is limitted to 4096, where as
the minimum supported AR window size is remained the same 32.
Will send separate PR for performance related reference odp_ipsec application
changes.
Signed-off-by: Mahipal Challa <mchalla@marvell.com>
=> [PATCH v8] linux-gen: ipsec: add anti-replay larger window sizes support.

platform/linux-generic/odp_schedule_basic.c, test/validation/api/scheduler/scheduler.c
Fix linux-gen implementation and add a validation test case for predefined groups.
=> [PATCH v2] linux-gen: allow sched group info request on predefined groups

platform/linux-generic/odp_classification.c
According to the spec odp_cls_cos_queues() should return the number of
queues linked to the CoS, not the number of queue handles written to the
output.
=> [PATCH v2] linux-gen: cls: fix odp_cls_cos_queues() return value

platform/linux-generic/pktio/dpdk.c
Since there is no capability for the supported input hash protocols it's
better to just print a debug message instead of fail
odp_pktin_queue_config() if an unsupported input hash protocol was
selected.
V2:
- Added second commit which disables automatic input hashing with DPDK pktio
=> [PATCH v3] linux-gen: dpdk: don't fail on unsupported input hash protocol

platform/linux-generic/pktio/dpdk_parse.c
DPDK pktio SNAP ethtype parsing code was using incorrect pointer.
=> [PATCH v2] linux-gen: dpdk: fix snap ethtype parsing

test/performance/odp_l2fwd.c
Extended -g option value range to include -1, which selects that
queues are created to ODP_SCHED_GROUP_WORKER group. The default
is still ODP_SCHED_GROUP_ALL.
=> [PATCH v2] test: l2fwd: add ODP_SCHED_GROUP_WORKER support

include/odp/api/spec/packet_io.h, include/odp/api/spec/packet_io_stats.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_packet_io_stats.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/pktio/stats/packet_io_stats.c, platform/linux-generic/pktio/stats/sysfs_stats.c, test/validation/api/pktio/pktio.c
- Add capabilities for statistics counters
- Add statistics counter for broadcast and multicast packets
- Add input/output queue specific statistics counters
V2:
- Added new `odp_pktio_queue_t` union for passing queue handles to `odp_pktin_queue_stats()` and `odp_pktout_queue_stats()` functions instead of using queue indices 
V3:
- Added reference implementation and validation tests
V4:
- Added separate functions for direct and event packet input/output queues
V5:
- Extend `odp_pktio_stats_reset()` documentation to state that resetting other than interface level statistics is implementation defined
=> [PATCH v10] api: pktio: add statistics capabilities and new counters

include/odp/api/abi-default/packet_io.h, include/odp/api/spec/packet_io_stats.h, platform/linux-generic/include-abi/odp/api/abi/packet_io.h, platform/linux-generic/include/odp_ethtool_stats.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_packet_io_stats.h, platform/linux-generic/include/odp_sysfs_stats.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/pktio/stats/packet_io_stats.c, platform/linux-generic/pktio/stats/sysfs_stats.c, test/validation/api/pktio/pktio.c
Add new functions for reading ODP implementation specific custom packet IO
statistics counters.
V2:
- Removed mention of `odp_pktio_stats_reset()`. PR #1288 will extend `odp_pktio_stats_reset()` documentation.
V4:
- Added implementation and validation tests
- Added `odp_pktio_extra_stats_print()`function
=> [PATCH v6] api: pktio: add implementation specific extra statistics counters

include/odp/api/spec/ipsec.h, include/odp/api/spec/packet_io.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_packet_io.c, test/validation/api/ipsec/ipsec_test_out.c, test/validation/api/pktio/pktio.c
This PR specifies more default values for init functions, improves validation testing of the defaults and fixes one bug in default value setting.
Contained patches (reverse order):
validation: pktio: check default values of odp_pktio_config_t
api: pktio: make loopback mode disabled by default
validation: ipsec: check reassembly related default values
api: ipsec: specify default values for reassembly enables
linux-gen: reass: fix the default value of max_num_frags
=> [PATCH v2] api: ipsec, pktio: specify more default values for init functions

CHANGELOG, configure.ac
- packet_io: added odp_pktio_stats_capability_t struct to
odp_pktio_capability_t to inform about supported statistics counters
- packet_io: added new statistics counters and related capabilities for
received/transmitted multicast and broadcast Ethernet packets
(in_mcast_pkts, in_bcast_pkts, out_mcast_pkts, out_bcast_pkts)
- packet_io: added new pktio input/output queue specific statistics
counters and related functions and capabilities
- packet_io: added new functions for reading and printing ODP
implementation specific custom packet IO statistics counters:
odp_pktio_extra_stat_info() , odp_pktio_extra_stats(),
odp_pktio_extra_stats_print()
- packet_io: specified that loopback mode is disabled by default
- …
=> [PATCH v2] api: increment ODP API version to 1.30.1.0

helper/ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec_test_out.c
ODP IPsec API supports AES-CMAC-96 but the algorithm is missing from validation test and the capability checker in helper. This PR adds minimal IPsec validation test (the digest algorithm itself is already validated in crypto validation tests) and makes the helper aware of the algorithm.
This PR also adds AES-CMAC-96 support in linux-gen IPsec implementation. The change is a one-liner as the crypto subsystem supports the algorithm and the IPsec implementation just needs to enable its use.
=> [PATCH v2] ipsec: add support for AES-CMAC-96 auth algorithm

config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Add configuration option 'pktio_dpdk.multicast_en' for DPDK pktio to
enable/disable reception of all multicast frames.
Fixes: https://github.com/OpenDataPlane/odp/issues/1326
Reported-by: Bogdan Pricope <bogdan.pricope.2013@gmail.com>
=> [PATCH v2] linux-gen: dpdk: add configuration option for multicast frame reception

test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec_test_in.c
There is one bug fix and one minor code improvement in this PR:
validation: ipsec: fix reassembly capability checking and config
validation: ipsec: use common function for incomplete reassembly too
@anoobj could you perhaps review this?
=> [PATCH v2] validation: ipsec: fix reassembly capability checking and config

platform/linux-generic/pktio/dpdk.c
Fix build for DPDK versions earlier than 19.11, which changed
rte_eth_allmulticast_enable() prototype (added return value).
This fix has been tested with DPDK v18.11.
=> [PATCH v2] linux-gen: pktio: fix DPDK 18.11 build

include/odp/api/abi-default/traffic_mngr.h, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c
Increase sched weight parameter size to accommodate larger
sched weights. This is needed for platform that support
weights larger than 255.
=> [PATCH v3] api: tm: increase sched weight parameter size

helper/include/odp/helper/ipsec.h, helper/ipsec.c, include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec_test_out.c
AES-GCM and AES-CCM, as used with IPsec, support more than one ICV length but the current API supports only single, unspecified ICV length for each algorithm.
This PR clarifies what the default ICV lenght is and makes it possible to configure non-default ICV lengths.
Minimal linux-gen implemenation (no new ICV lenghts added) and minimal API validation tests are included.
v2: fixed doxygen comment
=> [PATCH v4] api: ipsec: add ICV length in SA configuration parameters

include/odp/api/spec/classification.h, platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/include/odp_classification_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_packet_io.c, test/validation/api/classification/odp_classification_tests.c
Add classifier queue specific statistics counters (odp_cls_queue_stats_t)
and matching capabilities (odp_cls_stats_capability_t). Statistics counters
can be reset with odp_cls_queue_stats_reset() function and read
with odp_cls_queue_stats().
V2:
- Clarified `odp_cls_queue_stats_reset()` and `odp_cls_queue_stats()` argument documentation
V3:
- Removed `odp_cls_queue_stats_reset()` and clarified `odp_cls_queue_stats()` documentation
V4:
- Added implementation and validation tests
- Removed FCS from `odp_cls_queue_stats_t.octets` specification (Sunil)
=> [PATCH v6] api: cls: add queue specific statistics counters

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/include/odp_traffic_mngr_internal.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
commit 07d45a29fdfcf90b9b3be2c1eaf00d7f81d54834
Date:   Tue Jul 6 23:41:45 2021 +0530
validation: tm: set ordered enqueue and use enq multi API
Set new field ordered_enqueue in tm_queue_params and also use
odp_tm_enq_multi() API in scheduler test as burst Tx function.
commit f2a318af9c78c955c18acbf331d9c05f0a3f46ce
Date:   Tue Jun 29 16:50:42 2021 +0530
linux-gen: tm: support unordered enqueue and enq multi
Add support for unordered enqueue and enq multi API.
commit 6c9fbeca05726e3646d2f4fccb1d5cef297ab799
Date:   Sat …
=> [PATCH v5] api: tm: add unordered enqueue and multi-packet enqueue

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/include/odp_traffic_mngr_internal.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
Add traffic manager queue specific statistics counters
(odp_tm_queue_stats_t) and matching capabilities
(odp_tm_stats_capability_t). Statistics counters can be reset with
odp_tm_queue_stats_reset() function and read with odp_tm_queue_stats().
V2:
- Removed `odp_tm_queue_stats_reset()`
V3:
- Renamed `odp_tm_stats_capability_t` -> `odp_tm_queue_stats_capability_t`
- Added implementation and validation test
V4:
- Added `odp_tm_queue_stats_t.discard_octets` and `odp_tm_queue_stats_t.discard_packets`
V5:
- Renamed `odp_tm_queue_stats_t.discard_packets` to `odp_tm_queue_stats_t.discards`
=> [PATCH v6] api: tm: add queue specific statistics counters

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
commit df6ce5a7a00d0fc61690fedba0001fa0139345f2
Date:   Mon Jun 7 18:45:39 2021 +0530
api: tm: deprecate tm capabilities API
Deprecate odp_tm_capabilities() API as odp_tm_egress_capabilities()
provides similar functionality with additional input of egress
so that egress specific capabilities can be returned. Egress specific
capabilities are more useful as each TM system should have an egress.
commit 06dda1fa4a53132a04813999f482015ec85b4b73
Date:   Tue Jul 6 22:12:58 2021 +0530
validation: tm: use egress capabability before running tests
Use egress capabilities to identify if different features are
supported before running the …
=> [PATCH v8] api:tm: add missing capabilities and egress specific capability API

doc/implementers-guide/implementers-guide.adoc, include/Makefile.am, include/odp/api/abi-default/std.h, include/odp/api/abi-default/std_types.h, include/odp/api/spec/std.h, include/odp/api/spec/std_types.h, include/odp/api/std.h, include/odp/arch/arm32-linux/odp/api/abi/std.h, include/odp/arch/arm64-linux/odp/api/abi/std.h, include/odp/arch/default-linux/odp/api/abi/std.h, include/odp/arch/mips64-linux/odp/api/abi/std.h, include/odp/arch/power64-linux/odp/api/abi/std.h, include/odp/arch/x86_32-linux/odp/api/abi/std.h, include/odp/arch/x86_64-linux/odp/api/abi/std.h, include/odp_api.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/std.h, platform/linux-generic/include/odp/api/plat/std_inlines.h, platform/linux-generic/odp_std.c, platform/linux-generic/odp_std_api.c, test/m4/configure.m4, test/validation/api/Makefile.am, test/validation/api/std/.gitignore, test/validation/api/std/Makefile.am, test/validation/api/std/std.c, test/validation/api/std_clib/.gitignore, test/validation/api/std_clib/Makefile.am
Move all generic ODP functions and data types to a common std module. Type
definitions have been moved inside std_types.h header to enable easier
function inlining.
=> [PATCH v2] api: std: rename std_clib module to std

test/validation/api/pool/pool.c
Verify that number of segments in the reassembled packet is equal to the
the number of packet buffers passed to reassemble call.
=> [PATCH v2] validation: pool: verify number of segments of reassembled packet

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
**Depends on series in order:**
1. https://github.com/OpenDataPlane/odp/pull/1234
2. https://github.com/OpenDataPlane/odp/pull/1235
3. https://github.com/OpenDataPlane/odp/pull/1236
**Commits to be ignored for this pull request:**
* f7ee3dc validation: tm: use tm start and stop API - Nithin Dabilpuram, 5 months ago
* db7b267 validation: tm: use commit_rate and peak_rate in shaper params - Nithin Dabilpuram, 3 months ago
* c7bbc8d validation: traffic_mngr: use pktout mode as TM for Tx - Nithin Dabilpuram, 2 days ago
**Commits for review:**
commit 4625b916486048466c88beade7c8b85057cde432
Date:   Tue Jul 6 22:19:04 2021 +0530
validation: tm: add five level test case suite
Current validation suite only validates 3 level TM systems.
Refactor …
=> [PATCH v9] api: tm: add support for non-global packet priority mode in TM system

include/odp/api/abi-default/packet_types.h, include/odp/api/spec/packet_types.h
Fix below doxygen warnings seen with Doxygen version 1.9.1.
* include/odp/api/abi-default/packet_types.h:82:
warning: Member odp_packet_color_t (enumeration) of group odp_packet is
not documented.
* include/odp/api/abi-default/packet_types.h:89:
warning: Member odp_packet_chksum_status_t (enumeration) of group
odp_packet is not documented.
* include/odp/api/spec/packet_types.h:71:
warning: Documentation for undefined enum 'odp_packet_color_t' found.
* include/odp/api/spec/packet_types.h:182:
warning: Documentation for undefined enum 'odp_packet_chksum_status_t'
found.
=> [PATCH v3] api: packet: fix doxygen warnings

include/Makefile.am, include/odp/api/abi-default/proto_stats.h, include/odp/api/proto_stats.h, include/odp/api/spec/packet.h, include/odp/api/spec/packet_io.h, include/odp/api/spec/proto_stats.h, include/odp/arch/arm32-linux/odp/api/abi/proto_stats.h, include/odp/arch/arm64-linux/odp/api/abi/proto_stats.h, include/odp/arch/default-linux/odp/api/abi/proto_stats.h, include/odp/arch/mips64-linux/odp/api/abi/proto_stats.h, include/odp/arch/power64-linux/odp/api/abi/proto_stats.h, include/odp/arch/x86_32-linux/odp/api/abi/proto_stats.h, include/odp/arch/x86_64-linux/odp/api/abi/proto_stats.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/proto_stats.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, test/validation/api/pktio/pktio.c
commit 192b077eb422c0064c04e6715226e579765cc086
Author: Jerin Jacob <jerinj@marvell.com>
Date:   Mon Feb 15 15:37:43 2021 +0530
api: packet: add proto stats meta data support
Add metadata operations needed on per-packet basis for Packet IO
protocol stats feature on Tx
Signed-off-by: Jerin Jacob <jerinj@marvell.com>
commit 8b2a99509e3eac33f3a435072ba7562dbfd585f0
Author: Jerin Jacob <jerinj@marvell.com>
Date:   Mon Feb 15 15:35:30 2021 +0530
api: pktio: add support for Tx proto stats
Add support for Packet IO protocol stats feature on Tx. A packet is
associated with a proto stats object and when packet reaches
terminal state in pktout queue, those stats are updated. Proto stats
needs to be requested per-packet with by default it …
=> [PATCH v18] api: packet_io: introduce generic protocol stats framework with Tx per-packet stats offload

include/Makefile.am, include/odp/api/abi-default/proto_stats.h, include/odp/api/abi-default/proto_stats_types.h, include/odp/api/proto_stats.h, include/odp/api/proto_stats_types.h, include/odp/api/spec/packet.h, include/odp/api/spec/packet_io.h, include/odp/api/spec/packet_types.h, include/odp/api/spec/proto_stats.h, include/odp/api/spec/proto_stats_types.h, include/odp/arch/arm32-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/arm64-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/default-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/mips64-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/power64-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/x86_32-linux/odp/api/abi/proto_stats_types.h, include/odp/arch/x86_64-linux/odp/api/abi/proto_stats_types.h, include/odp_api.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/proto_stats.h, platform/linux-generic/include-abi/odp/api/abi/proto_stats_types.h
Packet type definitions belong to packet_types.h header.
V2:
- Added separate header for proto_stats  type definitions
=> [PATCH v3] api: packet: move odp_packet_proto_stats_opt_t definition

CHANGELOG, configure.ac
- classifier: added odp_cls_queue_stats() for reading queue specific
statistics counters
- ipsec: added ICV length into SA configuration parameters
- packet: added odp_packet_disassemble(), odp_packet_reassemble(), and
other new functions for packets allocated from external memory pools
- pool: added new concept of external memory pools, which are populated
with application provided memory
- pool: added new odp_pool_type_t enumeration
- traffic manager: increased scheduling weight parameter size (uint8_t to
uint32_t)
- traffic manager: added odp_tm_queue_stats() for reading queue specific
statistics counters
- traffic manager: added odp_tm_enq_multi() function for enqueueing
multiple packets at a time
- …
=> [PATCH v4] api: increment ODP API version to 1.31.0.0

test/validation/api/crypto/odp_crypto_test_inp.c
The test case for AES_GCM algorithm incorrectly uses 3DES_CBC algorithm in
the description. Also, many test case descriptions had missing full stops
at the end of the sentence.
Reviewed-by: Govindarajan <govindrajan.mohandoss@arm.com>
=> [PATCH v3] validation: crypto: remove test descriptions

.github/workflows/ci-pipeline.yml, .github/workflows/gh-pages.yml
Run 'apt update' before installing new packages. Fixes CI failures where
packages were not found due to outdated information.
=> [PATCH v2] ci: update apt packages

DEPENDENCIES
CLI helper depends on libcli. Added instructions to install it.
=> [PATCH v2] dependencies: add libcli install instructions

platform/linux-generic/pktio/dpdk.c
Fix the check in mbuf_update() which detects if mbuf data offset needs to
be updated. The previous check didn't detect a scenario where data offset
was not at default value (caused by e.g. odp_packet_push_head()).
Reported-and-tested-by: Christian Hong <guochun.hgc@alibaba-inc.com>
=> [PATCH v2] linux-gen: dpdk: fix invalid mbuf data offset

platform/linux-generic/odp_schedule_basic.c
Fixes two issues in scheduler:
- Group create did not increment per spread thread statistics. Dynamic load balance uses these, and did not balance load when thread did not join to groups, but were added there already in group create time.
- Queue create used always the first spread with min number of queues, which caused the same spread to be used when there is a low number of queues per group/prio.
=> [PATCH v2] linux-gen: sched: queue and group create fixes

platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c
odp_crypto_operation() calls odp_crypto_op() but incorrectly interprets
zero return value as success when it actually means that zero packets
were successfully processed. Consequently the result structure gets filled
with data that was not set by the failed odp_crypto_op(), input packet may
leak and output packet may not exists or contain incorrect data.
Fix the problem by returning an error if odp_crypto_op() returns zero.
Also, do not return a failure when odp_crypto_result() fails. At that
point odp_crypto_op() has already done the processing, including freeing
or overwriting the input packet. Indicate failure through the result
structure instead. Currently odp_crypto_result() never fails, but it may
not stay that way (and this piece of code seems to get reused elsewhere). …
=> [PATCH v2] linux-gen: crypto: fix error handling in odp_crypto_operation()

platform/linux-generic/include/odp_pool_internal.h
Fix cache alignment definition in pool_t. The correct definition
to use is ODP_ALIGNED_CACHE (not ODP_CACHE_ALIGNED).
=> [PATCH v2] linux-gen: pool: fix cache alignment definition

platform/linux-generic/include/odp_libconfig_internal.h, platform/linux-generic/odp_libconfig.c
adds new function to get the size of the string array and its
elements
=> [PATCH v4] linux-gen: config: add string array lookup function

platform/linux-generic/odp_packet.c, platform/linux-generic/pktio/loop.c
Various fixes for packet parsing, mostly for segmented packets that get parsed when requested through odp_packet_parse() or after going through loop.
=> [PATCH v3] Fix parsing of segmented packets

.github/workflows/gh-pages.yml
Use Ubuntu 20.04 to build documentation and bump ghaction-github-pages
version to v2.5.0.
=> [PATCH v3] github_ci: update gh pages build workflow

platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c
In bit mode the crypto and auth ranges are supposed to be given in bits,
not in bytes. Fix the linux-gen implementation that interpreted crypto and
auth offset in bytes in AES EEA2 and AES EIA2, respectively. Fix crypto
validation test to provide the offsets in bits as specified by the API.
=> [PATCH v2] crypto: fix crypto and auth range offset in bit mode

example/ipsec_api/odp_ipsec.c, include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, test/performance/odp_ipsec.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_async.c, test/validation/api/ipsec/ipsec_inline_in.c, test/validation/api/ipsec/ipsec_inline_out.c, test/validation/api/ipsec/ipsec_sync.c
In some ODP implementations, plain queues might be using software
primitives such as a simple ring and the ODP IPsec hardware
can enqueue completion events only into schedule queues.
Introducing capability queue_type_sched and queue_type_plain
which define the queue types that can be the destination of the
IPsec events.
=> [PATCH v12] api: ipsec: add destination queue capability

include/odp/api/spec/ipsec.h
Specify that the output packet of an errored IPsec operation is not
the unmodified input packet but a packet with undefined content. This
is already the case in the linux-gen implementation and is basically
required by implementations that use in-place crypto operations which
modify the packet (with combined mode algorithms) before checking for
authentication error.
Still promise the original input packet back after sa_lookup and mtu
errors since in those cases the application is expected to continue
processing the packet.
=> [PATCH v2] api: ipsec: do not promise original packet back after all errors

include/odp/api/spec/ipsec.h, platform/linux-generic/odp_ipsec.c, test/validation/api/ipsec/ipsec.c
Provide the original ESP/AH packet length before inbound IPsec processing
in odp_ipsec_packet_result_t. An application may use it for statistics
purposes.
This can be useful since post-IPsec reassemly offload makes it difficult
to deduce the original octet count that went into the creation of the
result packet. Even without reassembly offload, possible extra padding
cannot be deduced from the result packet.
=> [PATCH v3] api: ipsec: provide original ESP/AH packet length in IPsec packet result

include/odp/api/spec/packet.h, include/odp/api/spec/packet_types.h, platform/linux-generic/odp_packet.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_in.c
Intoroduce odp_packet_reass_info() that provides information on
a completed reassemly. The number of fragments that were reassembled
is useful for statistics and the IP length of the longest fragment
is useful for path MTU handling purposes if reassembly offload if used
for forwarded traffic.
=> [PATCH v5] api: packet: add odp_packet_reass_info() for reassembly details

example/cli/odp_cli.c, helper/cli.c, helper/include/odp/helper/cli.h, helper/test/cli.c
Add odph_cli_run() and remove odph_cli_start().
Don't create a thread in the CLI helper. Instead, the caller may
create a thread and call odph_cli_run() to run the CLI.
v2:
- Update implementation.
v3:
- Helper API: Minor rewording of odph_cli_run() and odph_cli_stop() descriptions.
- odph_cli_stop(): Wait for server to exit.
- Fix cli_server() error handling.
- Some renaming (SP_*) and cleanup.
v4:
- Helper API: In process mode, odph_cli_init() must be called before creating the thread.
- Fix odph_cli_stop() in process mode.
v5:
- Rebase on PR #1355.
- Use odph_thread_param_init() and odph_thread_common_param_init().
- Add review and cc tags.
v6:
- Rebase on master.
=> [PATCH v6] helper: cli: don't create the server thread

CHANGELOG, configure.ac
* ipsec: added destination queue capabilities
odp_ipsec_capability_t.queue_type_sched and
odp_ipsec_capability_t.queue_type_plain
* ipsec: modified specification to not promise the original packet back
after all error cases
- ipsec: added original ESP/AH packet length into IPsec packet result
(odp_ipsec_packet_result_t.orig_ip_len)
- packet: added odp_packet_reass_info() function for reading completed
reassembly details
- std: moved all contents of support and feature modules into ODP Std
module
Helper library (1.2.0):
- cli: replaced odph_cli_start() function with odph_cli_run(), which
doesn't automatically create a separate thread for running the CLI
server. …
=> [PATCH v2] api: increment ODP API version to 1.32.0.0

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, platform/linux-generic/arch/aarch64/odp/api/abi/atomic_inlines.h, platform/linux-generic/arch/default/odp/api/abi/atomic_generic.h, platform/linux-generic/include/odp/api/plat/atomic_inlines.h
Following performance gains were observed for the atomic add/sub/inc/dec APIs in the atomic perf test:
```
_______________________________________
|   odp_atomic_add_u32   |     7-8%   |
|   odp_atomic_sub_u32    |     7-8%   |
|   odp_atomic_inc_u32     |     5-6%   |
|   odp_atomic_dec_u32    |     4-5%   |
|   odp_atomic_add_u64    |     4-5%   |
|   odp_atomic_sub_u64    |     5-6%   |
|   odp_atomic_inc_u64     |     5-6%   |
|   odp_atomic_dec_u64    |     4-5%   |
|___________________________|__________ |
```
For the pool performance test, no significant performance improvement was observed with this change.
=> [PATCH v11] linux-gen: atomic: emit STADD explicitly for __atomic_fetch_add operation

test/validation/api/ipsec/ipsec.c
The API specifies that zero odp_ipsec_packet_result_t::orig_ip_len means
that the length is not available. Check orig_ip_len against the original
packet length only when it is available.
=> [PATCH v2] validation: ipsec: allow orig_ip_len to be unavailable

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c
Add support for extended sequence numbers, except with the AES-GMAC
algorithm.
Signed-off-by: Mahipal Challa <mchalla@marvell.com>
Signed-off-by: Sachin Yaligar <syaligar@marvell.com>
=> [PATCH v1] linux-gen: ipsec: add esn feature support

doc/images/pktio_fsm.gv, doc/images/timeout_fsm.gv, doc/images/timer_fsm.gv
Remove 'size' option from DOT images, which was causing SVG images to be
rendered incorrectly.
Reported-by: Baofeng Wang <baofeng.wang@nokia.com>
=> [PATCH v2] doc: user-guide: fix DOT image format

platform/linux-generic/include/odp_libconfig_internal.h, platform/linux-generic/odp_libconfig.c
Adds a new function to get a string from config
=> [PATCH v1] linux-gen: config: add string lookup function

platform/linux-generic/odp_ipsec.c
Copy read-only 'status' struct into local memory. Removes a load
instruction from each if-branch on aarch64.
=> [PATCH v2] linux-gen: ipsec: optimize ipsec_sa_err_stats_update()

platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/cpu_flags.c, platform/linux-generic/arch/aarch64/cpu_flags.h, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c
CPU specific hardware/software features are exposed by the kernel to the
userspace through a set of flags called hwcaps, exposed in the auxiliary
vector. Userspace software can test for features by acquiring the AT_HWCAP
and AT_HWCAP2 entry of the auxiliary vector.
These hwcaps are defined in terms of architected system register fields
and those exposed in AT_HWCAP and AT_HWCAP2 typically have feature flags
associated with them. The mapped feature flags and their description
are printed as a part of the odp_sys_info_print() API.
Reviewed-by: Govindarajan <govindarajan.mohandoss@arm.com>
=> [PATCH v6] linux-gen: sysinfo: dump aarch64 cpu hardware flags

platform/linux-generic/odp_packet.c
Add missing asserts for invalid event defines and add explanation why this
is required.
=> [PATCH v2] linux-gen: packet: add missing asserts for invalid event defines

platform/linux-generic/odp_packet_vector.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_timer.c
Add asserts for checking that buffers are allocated from the right type
of pool.
=> [PATCH v3] linux-gen: pool: add pool type checks to alloc functions

include/odp/api/spec/stash.h, platform/linux-generic/Makefile.am, platform/linux-generic/include/odp_ring_common.h, platform/linux-generic/include/odp_ring_internal.h, platform/linux-generic/include/odp_ring_u64_internal.h, platform/linux-generic/odp_stash.c, test/validation/api/stash/stash.c
The new functions are safer to use compared to the generic versions due to strict typing and the implementation may be
more optimized.
New functions:
- `odp_stash_put_u32()`
- `odp_stash_get_u32()`
- `odp_stash_put_u64()`
- `odp_stash_get_u64()`
- `odp_stash_put_ptr()`
- `odp_stash_get_ptr()`
V2:
- Squashed the 64-bit implementation commits (Petri)
- API "... with 'obj_size' of" wording (Petri)
V3:
- Fixed cast types (Petri)
V4:
- Rebase
- Added Reviewed-by tags
=> [PATCH v4] api: stash: add type specific put/get functions

platform/linux-generic/odp_pool.c, test/validation/api/packet/packet.c
Allocate enough packet buffers in case a single 'params->pkt.len' packet
consists of multiple segments. Add new validation test for this.
V2:
- Added `params->pkt.max_num` check to `pool_create()`
=> [PATCH v2] linux-gen: pool: allocate enough packets for multi-segment usage

helper/test/odpthreads.c, include/odp/api/spec/init.h, include/odp/api/spec/protocols.h, include/odp/api/spec/version.h.in, platform/linux-generic/odp_init.c, test/validation/api/init/init_main.c
Add odp_instance() function for reading the current ODP instance handle.
Includes additional minor API changes to fix Doxygen output.
V2:
- Use `memcpm()` in validation test (Petri)
V3:
- Added output parameter for the instance handle
=> [PATCH v4] api: init: add function for reading current instance handle

include/odp/api/spec/pool.h, platform/linux-generic/odp_pool.c, test/validation/api/pool/pool.c
Add new odp_pool_print_all() function for printing implementation defined
information about all created pools to the ODP log. The information is
intended to be used for debugging.
V2:
- Implementation optimization (Petri)
=> [PATCH v3] api: pool: add odp_pool_print_all() function

include/odp/api/spec/pool_types.h, test/validation/api/packet/packet.c
Clarify odp_pool_param_t.pkt.seg_len documentation to state that 'seg_len'
is valid only for new packets and that this data starts from
odp_packet_data() (i.e. headroom is not included in this value).
=> [PATCH v5] api: pool: clarify odp_pool_param_t.pkt.seg_len documentation

example/cli/odp_cli.c, helper/cli.c, helper/include/odp/helper/cli.h, helper/test/cli.c
Now that the CLI helper no longer creates a thread, the ODP instance is not needed by odph_cli_init().
v2:
=> [PATCH v2] helper: cli: remove unused instance parameter from odph_cli_init()

CHANGELOG, configure.ac
- init: added odp_instance() function for reading the current ODP instance
handle
- ipsec: clarified bit field unions' 'all' member intended usage
- packet: clarified odp_proto_chksums_t.all_chksum intended usage
- packet IO: Clarified odp_pktin_hash_proto_t.all_bits intended usage
- pool: added odp_pool_print_all() function for printing implementation
defined information about all created pools to the ODP log
- pool: clarified odp_pool_param_t.pkt.seg_len documentation
- stash: added 64-bit only odp_stash_put_u64() and odp_stash_get_u64()
functions
- stash: added 32-bit only odp_stash_put_u32() and odp_stash_get_u32()
functions
- stash: added pointer only odp_stash_put_ptr() and odp_stash_get_ptr() …
=> [PATCH v2] api: increment ODP API version to 1.32.1.0

platform/linux-generic/include/odp_global_data.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c
IPsec requires unpredictable IVs with several algorithms and the current
implementation uses the ODP random number generator for the generation
of such IVs. The implementation tries to use ODP_RANDOM_CRYPTO kind of
random data but settles for weaker kinds if ODP_RANDOM_CRYPTO is not
available. This can make the IVs predictable.
Fix the problem by using only cryptographically strong random data and by
disabling all algorithms that require it if it is not available.
=> [PATCH v2] linux-gen: ipsec: fix handling of poor quality random data

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec_sad.c
Do not store a copy of the SA parameter structure in the SA. Derive
the SA creation parameters to be returned by odp_ipsec_sa_info() from
other SA fields. Store additional data ín the SA for the sa_info
only when necessary.
=> [PATCH v3] linux-gen: ipsec: do not store duplicate data for the sa_info call

platform/linux-generic/odp_schedule_basic.c
Add scheduler group names to the output of odp_schedule_print() function to
provide additional debug information.
=> [PATCH v2] linux-gen: sched: add scheduler group names to odp_schedule_print() output

platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c
Added part number enumerations for ARM V1, N2, A510 and
A710 CPUs.
=> [PATCH v3] linux-gen: arch: add new aarch64 CPU enumerations

configure.ac, include/odp/api/spec/random.h, include/odp/autoheader_internal.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/README, platform/linux-generic/arch/default/odp_random.c, platform/linux-generic/arch/default/odp_random.h, platform/linux-generic/arch/x86/odp_random.h, platform/linux-generic/include/odp_random_openssl_internal.h, platform/linux-generic/include/odp_random_std_internal.h, platform/linux-generic/odp_random.c, platform/linux-generic/odp_random_openssl.c, platform/linux-generic/odp_random_std.c, test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_random.c
```
linux-gen: random: implement crypto random and true random data on x86
Implement crypto random data using rdrand, and true random data using
rdseed, via compiler builtin functions.
Add architecture-specific file for crypto random and true random
functions.
configure: add option to disable openssl random
Add configure option --disable-openssl-rand, which disables the use of
OpenSSL RAND_bytes() to generate basic random and crypto random data.
test: perf: implement random data throughput test
This test measures megabytes per second throughput of the random data
generation API functions.
linux-gen: README: add note about …
```
=> [PATCH v5] linux-gen: random: implement crypto random and true random data on x86

test/performance/Makefile.am, test/performance/odp_sched_perf.c, test/performance/odp_sched_perf_run.sh
Add command line option '-p, --pool_type' for using a packet pool instead
of buffer pool for allocating test events.
=> [PATCH v4] test: sched_perf: add option to use packet pool

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_lock_perf.c
```
Test lock performance by measuring the time it takes to do a number of
rounds, where a round is a set of counter and lock operations specific
to the lock type. At the end, the resulting counter values are
compared against expected values.
```
v2:
- Number of CPUs default is 10 instead of all.
v3:
- Remove volatile.
v4:
- The rest of Petri's comments.
v5:
=> [PATCH v5] test: performance: add lock performance test

config/odp-linux-generic.conf, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/include/odp_sysinfo_internal.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_system_info.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Add 'system:cpu_hz_static' configuration option for using a static CPU
frequency value. When enabled, CPU frequency values returned by
odp_cpu_hz() and odp_cpu_hz_id() calls are read from the OS only once
during ODP initialization. Enabling this option removes system calls from
odp_cpu_hz() and odp_cpu_hz_id() implementations.
NOTE: This option should only be used on systems where CPU frequency
scaling is disabled.
=> [PATCH v2] linux-gen: cpu: add configuration option to use static cpu frequency

test/validation/api/cpumask/cpumask.c
Add new check which requests a large control/worker CPU mask and validates
that the returned mask is smaller or equal than the mask previously
returned when 'num' was zero.
=> [PATCH v2] validation: cpumask: add new check for default control/worker masks

configure.ac, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_openssl.m4
OpenSSL crypto and random implementations are platform specific, so move
the configuration options under linux-genec platform.
=> [PATCH v2] configure: move openssl options under linux-gen platform

.checkpatch.conf
```
The checkpatch ignore option is ARRAY_SIZE, not
PREFER_ARRAY_SIZE. Also, PREFER_PRINTF and PREFER_SCANF don't exist
anymore, remove those.
```
=> [PATCH v2] checkpatch: fix ARRAY_SIZE ignore option

platform/linux-generic/odp_cpumask_task.c
Previously, odp_cpumask_default_control() function implementation returned
only one control thread if 'num' parameter was zero. According to the spec,
the function should return all available worker CPUs in this case.
=> [PATCH v2] linux-gen: cpumask: fix odp_cpumask_default_control() parameter handling

doc/users-guide/users-guide.adoc, helper/cli.c, helper/cuckootable.c, helper/hashtable.c, helper/iplookuptable.c, helper/lineartable.c, include/odp/api/spec/shared_memory.h, platform/linux-generic/odp_ishm.c, platform/linux-generic/odp_shared_memory.c, platform/linux-generic/odp_timer.c, test/validation/api/atomic/atomic.c, test/validation/api/barrier/barrier.c, test/validation/api/lock/lock.c, test/validation/api/shmem/shmem.c, test/validation/api/thread/thread.c, test/validation/api/timer/timer.c
V2:
- Removed `odp_shm_addr_pa()` API
- `ODP_SHM_NO_HP` documentation clarification
- State that some flag combinations may not be supported
V3:
- Rebase
=> [PATCH v5] api: shm: introduce flags capability and ODP_SHM_NO_HP flag

include/odp/api/spec/ipsec.h, include/odp/api/spec/packet_io.h, test/validation/api/classification/odp_classification_common.c, test/validation/api/ipsec/ipsec_test_out.c, test/validation/api/pktio/pktio.c
The first API patch tweaks the existing pktin packet vector spec so that when packet vectors are enabled, plain packet events will not be generated by the pktin. The second API patch adds packet vector support to packet completion events in the IPsec API.
This PR also adds more default value checks for the pktio related init functions (except lso). There seem to be an inconsistency or an ambiquity in the ODP API regrading the default value of queue mode, which I will try to handle separately.
=> [PATCH v4] api: add packet vectors to ipsec and clarify packet vector API

include/odp/api/spec/crypto.h, include/odp/api/spec/ipsec.h, test/validation/api/crypto/odp_crypto_test_inp.c
Clarify the API that session/SA creation parameters, including memory buffers pointed to be pointers in the parameter structure, can be freed after the creation call. This has been the intention of the API already. If an ODP implementation needs to remember some parameters after session creation, it must to copy them. Linux-gen already works this way.
Made crypto API validation test clear the parameters, including key data, after session creation to better catch non-compliant implementations. The PR does not have a similar patch for IPsec API validation tests as it is not as trivial to add there.
=> [PATCH v3] api: crypto session and IPsec SA creation parameters can be fully freed afterwards

include/odp/api/spec/classification.h, include/odp/api/spec/packet_io.h, test/validation/api/classification/odp_classification_basic.c, test/validation/api/pktio/pktio.c
Specify that odp_pktin_queue_config() ignores the queue type passed in the parameter struct but deduces the queue type from the pktio input mode. This is the current behaviour in linux-gen and the expected behaviour in the API validation tests.
Specify a few more default values for classifier config structures. The added defaults were already assumed by the API validation tests.
Add validation tests to check the defaults.
This PR assumes that PR 1416 gets merged first (for the vector.enable default value spec).
=> [PATCH v3] api: clarify default values that were underspecified

CHANGELOG, configure.ac
- shm: added a bit mask capability odp_shm_capability_t.flags for ODP_SHM_*
flags
- timer: added initialization function odp_timer_pool_param_init() for
timer pool parameters. Application must use it to initialize parameters
to their default values.
- classifier: added missing default values for
odp_cls_cos_param_t.num_queue, odp_cls_cos_param_t.red.enable,
odp_cls_cos_param_t.bp.enable, and odp_pmr_param_t.range_term
- crypto: clarified that odp_crypto_session_create() parameters, including
the key and IV data, can be freed after session creation.
- dma: added new DMA module which enables applications to offload memory
transfers (copies) to DMA hardware. See …
=> [PATCH v2] api: increment ODP API version to 1.33.0.0

test/validation/api/atomic/atomic.c
```
validation: atomic: break validation function into multiple functions
Break the validation function into multiple separate validation
functions. This way existing code (the single validation function)
doesn't need to be changed when adding new tests.
validation: atomic: validate max and min values
Validate the resulting max and min values, instead of just max > min.
validation: atomic: add increment/add and decrement/sub tests
Test increments and adds separately from decrements and subs. This is
in addition to the existing tests, which test that a counter reaches
its starting value after matching increments and decrements, and after
matching adds and subs.
validation: atomic: test xchg operations with random data
Add a new test, which uses random bytes with xchg operations and
counts …
```
=> [PATCH v3] validation: atomic: some improvements

test/validation/api/atomic/atomic.c
Defined CNT as ULL to avoid potential overflow in total_count
calculations. Coverity reported these issues as "Unintentional
integer overflow (OVERFLOW_BEFORE_WIDEN)".
=> [PATCH v1] validation: atomic: define CNT as unsigned long long

example/ipsec_crypto/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_cache.c, example/ipsec_crypto/odp_ipsec_cache.h, example/ipsec_crypto/odp_ipsec_misc.h
Reusing the same ESP IV within the same SA should not be done. Fix the code to not reuse pre-generated IVs but generate a new random IV for every outbound ESP packet.
Somewhat related to this, I am working on a crypto API change proposal to remove per-session IVs altogether (i.e. require an IV for every packet in the per-crypto-operation parameters), as the per-session IVs are rarely, if ever, used as opposed to per-packet IVs. I will submit a separate PR on that later.
Another change in this PR is simple removal of unnecessary tunnel header IP ID randomization after ID wrap-around.
=> [PATCH v3] example: ipsec_crypto: fix outbound ESP processing to not reuse IVs

platform/linux-generic/odp_shared_memory.c, test/performance/odp_random.c
Stop listing deprecated SHM flag ODP_SHM_SW_ONLY as supported as it is no
longer used by any example applications or tests.
V2:
- Enable usage of `ODP_SHM_SW_ONLY` flag with `--enable-deprecated` configuration option (Janne)
=> [PATCH v3] linux-gen: shm: stop listing deprecated ODP_SHM_SW_ONLY flag as supported

platform/linux-generic/odp_random_std.c, test/validation/api/random/Makefile.am, test/validation/api/random/random.c
```
linux-gen: random: improve ODP_RANDOM_BASIC data and random test data
Improve the quality of data generated by and the speed of
odp_random_test_data() and _odp_random_std_data() (used when OpenSSL
random is not enabled).
validation: random: add test for buffer overflow and alignment problems
Add a new test, which checks that odp_random_data() and
odp_random_test_data() do not modify bytes outside the given buffer.
validation: random: test randomness
Test that random data looks random by adding four new tests:
random_test_frequency checks that random data is uniformly
distributed.
random_test_independence checks that …
```
=> [PATCH v7] random data improvements and tests

test/validation/api/atomic/atomic.c
```
validation: atomic: add separate test for odp_atomic_init_*() functions
Add a separate test for odp_atomic_init_*() functions, instead of
relying on implicit checks in the other tests.
validation: atomic: add separate test for each type of operation
Add a separate test for each type of atomic operation, unless such a
test already exists.
```
v3:
- Rebase.
- Petri's comments.
=> [PATCH v3] validation: atomic: more improvements

platform/linux-generic/pktio/socket.c
Add missing whitespace to `sock_init_global()` log.
=> [PATCH v2] linux-gen: pktio: socket: fix log text

test/validation/api/pktio/pktio.c, test/validation/api/queue/queue.c
While creating pools, take into consideration buffer starvation
that can occur on a core due to buffers being cached on a different
core. So ensure that pools are created with enough buffers.
While creating pools, take into consideration buffer starvation
that can occur on a core due to buffers being cached on a different
core. So ensure that pools are created with enough buffers.
=> [PATCH v2] Pull request for buffer starvation due to caching

platform/linux-generic/odp_pool.c, test/validation/api/packet/packet.c
Failures were seen in CI when a packet pool was being created with
the existing maximum uarea size of 10MB.
So reduce maximum user area size to 2048 bytes.
Add a new test which creates multiple pools with different user area
sizes and validates that memset of the user area does not affect the
packet validity.
=> [PATCH v4] validation: packet: add new test for user area testing

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_dma_perf.c
ODP DMA API performance is tested with a scenario where a configurable
amount of input segments are transferred to a single large output
segment configurable amount of times. Both synchronous and asynchronous
transfers can be tested.
Current implementation supports packet-type transfers, plain buffer
based support will be added later.
v2:
- fix miscellaneous style issues
v3:
- fix transfer and completion parameter init usage
v4:
- year bump
- check event completion pool capability
- allocate individual event for every event-completion transfer
v5:
=> [PATCH v5] test: performance: add DMA performance test

example/timer/odp_timer_accuracy.c
V2:
- Updated copyright year
- Print error string in case of `fopen()` failure
=> [PATCH v3] example: timer_accuracy: close output file on failure

test/performance/odp_lock_perf.c
```
test: lock_perf: print counter values when validation fails
At the end of the test, print counter values that do not match the
expected values.
test: lock_perf: add option to run tests repeatedly
Add a command line option to run the tests repeatedly until failure,
or forever.
```
v2:
- Rebase.
=> [PATCH v2] test: lock_perf: a couple of small improvements

test/validation/api/pool/pool.c
Test that default odp_pool_param_t values are set correctly by
odp_pool_param_init() function.
=> [PATCH v2] validation: pool: check odp_pool_param_init() output

platform/linux-generic/odp_system_info.c
odp_sys_huge_page_size_all() function implementation uses qsort() to sort
the system huge page sizes into ascending order. qsort() comparison
function returns an integer and with large page sizes (e.g. 16G) the return
value could overflow with the previous implementation.
=> [PATCH v2] linux-gen: sysinfo: fix odp_sys_huge_page_size_all() return value order

test/performance/odp_dma_perf.c
Use wider types when calculating size for shared memory reservation to
prevent a potential integer overflow.
v2:
=> [PATCH v2] test: performance: dma_perf: fix potential overflow issue

test/performance/odp_random.c, test/validation/api/random/random.c
```
validation: random: use less random data
True random generators may be slow, so use much less random data in
the randomness tests so that the tests don't take too much time.
random_test_independence_true test is removed, while some other tests
are scaled down. With this change, the randomness tests use about 51
MB of crypto random data and about 527 KB of true random data.
test: perf: random: divide test rounds by 100 for ODP_RANDOM_TRUE
True random data may be slow, so divide the test length by 100 for
ODP_RANDOM_TRUE.
```
v2:
- Rebase.
- Matias' comments.
v3:
- Add review tags,
=> [PATCH v3] test: random: use less random data

test/validation/api/atomic/atomic.c
```
validation: atomic: limit random buffer size
Set the size of the buffer holding random numbers in the xchg tests to
64K, so that we don't run out of memory if the test length is
increased.
validation: atomic: fix validation in case of 32 bit overflow and underflow
If test length is increased, 32 bit counters will overflow or
underflow, and min and max variables will be saturated. Fix validation
for these cases.
```
v2:
- Rebase.
- Tuomas' comments.
v3:
- Rebase.
=> [PATCH v3] validation: atomic: fix validation in case of 32 bit overflow and underflow

test/performance/odp_dma_perf.c
Instead of exiting with `EXIT_FAILURE`, use a different exit code (2) if
underlying implementation does not support attempted test scenario.
v3:
=> [PATCH v3] test: performance: dma_perf: add new exit code for unsupported scenario

test/validation/api/crypto/odp_crypto_test_inp.c
There is no need to check in a test function that the tested algorithms
are included in crypto capabilities. The check has already been done
by check_alg_support() and the test is conditional on the support.
Remove the leftover redundant capability check code. Move remaining
capability validations (all algorithms that are marked HW offloaded
must be marked supported too) in a separate test case. Add a check
that at least one of sync mode and async mode is supported if any
crypto is supported.
=> [PATCH v2] validation: crypto: remove redundant capability check

platform/linux-generic/include/odp_traffic_mngr_internal.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
linux-gen: tm: remove unused odp_queue_t instance
tm_queue_obj contains an instance of odp_queue_t but the ODP queue is
not used for anything. The queue seems to be a leftover from very early
revisions and has been unused since 0d6d0923b. Remove the queue and
associated code.
linux-gen: tm: fix success return value of odp_tm_enq()
Currently odp_tm_enq() may (and often does) return a positive value
after successful enqueue, even though the API specifies that in success
the function returns 0. Fix the return value.
validation: tm: check the return value of odp_tm_enq() better
According to ODP API, odp_tm_enq() will never return a positive value.
Check that the return value is not positive.
=> [PATCH v2] linux-gen: tm: odp_tm_enq() fix and stale queue removal

test/performance/Makefile.am, test/performance/odp_dma_perf_run.sh
Add test script for running `odp_dma_perf` with a few different
scenarios during `make check`.
v2:
- reduce test rounds to 1000
- utilize exit code of `odp_dma_perf`
- move `odp_dma_perf` to compile only
- always use 1024B segment size
v3:
- rebase
=> [PATCH v3] test: performance: dma_perf: add test script

.github/workflows/ci-pipeline.yml, scripts/ci/coverage.sh
Upgrade to Codecov uploader V2 as V1 is being discontinued. The new
uploader doesn't convert *.gcno files into *.gcov files automatically
anymore, so this has to be done now manually in the coverage.sh script.
=> [PATCH v2] ci: update codecov uploader version

example/ipsec_crypto/odp_ipsec_cache.c, include/odp/api/spec/crypto.h, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_ipsec_sad.c
Make hash generation and verification spec match linux-gen implementation.
In particular: After verification, the hash field in the packet is left
to undefined value, not the calculated hash value and in generation the
hash field is not cleared before the hash calculation.
=> [PATCH v5] api: crypto: change hash generation and verification details

doc/users-guide/users-guide-crypto.adoc, example/ipsec_crypto/odp_ipsec_cache.c, include/odp/api/spec/crypto.h, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_ipsec_sad.c, test/performance/odp_crypto.c, test/validation/api/crypto/odp_crypto_test_inp.c
Reusing the same initialization vector (IV) with the same key is almost always wrong and results in weakened security. Therefore the ability of specifying IV in crypto session creation and reusing it in multiple crypto operations is of questionable value. It complicates both the API and implementations and may encourage incorrect IV reuse (see PR 1446).
This PR deprecates odp_crypto_iv_t type (which holds IV length and IV data) and the cipher_iv and auth_iv parameters of odp_crypto_session_param_t. New session parameters, cipher_iv_len and auth_iv_len, are introduced for setting IV lengths in the session. From now on, IV data must always be passed through the existing cipher_iv_ptr and auth_iv_ptr parameters of odp_crypto_op_param_t and odp_crypto_packet_op_param_t.
=> [PATCH v7] api: crypto: deprecate IV data in session parameters

include/odp/api/spec/random.h
```
Explicitly state that the same series of odp_random_test_data() calls
is required to generate the same data. This is already the
interpretation in linux-gen, this change is only a clarification to
the API text.
```
v2:
- Add review tag.
=> [PATCH v2] api: random: explicitly require the same series of calls to generate repeatable test data

example/ipsec_crypto/odp_ipsec_cache.c, include/odp/api/spec/crypto.h, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c
api: crypto: add session creation error codes for unsupported combos
Add crypto session creation error codes for cases where the requested
combination of algorithms, order of algorithms or other combination
of creation parameters is not supported. The new errors are for cases
where a limitation of an ODP implementation cannot be expressed
through crypto capabilities.
api: crypto: clarify auth_range parameter with AEAD algorithms
AEAD algorithms authenticate the plaintext that is to be encrypted
plus additional authenticated data (AAD). Clarify that in case of AEAD
algorithms the auth_range parameter is not used, except with AES-GMAC.
AES-GMAC, as defined, does not take any plaintext to be encrypted
as input but only AAD. In ODP API the aad_ptr parameter is not used
but the AAD is provided …
=> [PATCH v5] api: crypto: API clarifications and new session creation error codes

example/traffic_mgmt/odp_traffic_mgmt.c, include/odp/api/abi-default/traffic_mngr.h, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
commit d2988a3b6bde68dc7bc863ecf3edf15f1291351a
Date:   Wed Jul 14 20:18:06 2021 +0530
abi: tm: provide shaper burst limits
Provide shaper min burst and max burst limits.
commit b44421e0bd4e8fd05dac955fa333c71985a84fbb
Date:   Wed Jul 14 20:17:52 2021 +0530
api: tm: add spec to express shaper burst limits
Add macro's that needs to be defined by platform to express
shaper rate burst min and max in bytes. This is similar to existing
shaper rate bandwidth min and max macros.
=> [PATCH v12] api: tm: add spec to express shaper burst limits

platform/linux-generic/odp_traffic_mngr.c
Use the signal_request/check_request mechanism to make sure the TM
system thread is not accessing shaper parameters at the same time
when they are being changed by another thread.
This should prevent the crash that sometimes occurs when running TM
validation tests that disable shapers on the fly, changing the shaper
parameter pointer in shaper objects NULL just when the TM system thread
is about to dereference it.
This patch does not fix other issues in the synchronization mechanism:
The mechanism is not always used when needed, it uses relaxed atomics
that do not guarantee memory ordering and it does not work with
multiple TM system threads.
=> [PATCH v2] linux-gen: tm: synchronize with TM thread when configuring shaper

include/odp/api/spec/traffic_mngr.h, test/validation/api/traffic_mngr/traffic_mngr.c
api: tm: define default values for many parameters
Define the default values for many parameters to be set by various
init functions. Current API validation tests already rely on certain
defaults (at least packet_mode being false) which are set by the
linux-gen implementation but which are not specified in the API.
validation: tm: test default values
Test that init functions initialize parameters to their default values.
=> [PATCH v2] api: tm: define default values

.github/workflows/gh-pages.yml
Prevent automatic GitHub workflow 'pages-build-deployment' from rebuilding
ODP documentation. The documentation is already built by 'GitHub Pages'
workflow.
=> [PATCH v2] github_ci: prevent automatic documentation rebuild

example/classifier/odp_classifier.c, example/ipsec_api/odp_ipsec.c, example/ipsec_crypto/odp_ipsec.c, example/l3fwd/odp_l3fwd.c, example/l3fwd/odp_l3fwd_run.sh, example/packet/pktio_run.sh, example/simple_pipeline/simple_pipeline_run.sh, example/switch/switch_run.sh, platform/linux-generic/test/example/classifier/pktio_env, platform/linux-generic/test/pktio_ipc/pktio_ipc1.c, platform/linux-generic/test/pktio_ipc/pktio_ipc2.c, platform/linux-generic/test/pktio_ipc/pktio_ipc_run.sh, test/performance/Makefile.am, test/performance/odp_cpu_bench_run.sh, test/performance/odp_crypto_run.sh, test/performance/odp_ipsec_run.sh, test/performance/odp_pktio_ordered_run.sh, test/performance/odp_pktio_perf.c, test/validation/api/system/system.c
Many tests run unnecessarily long during make check, especially on slower platforms. Often just a small number of iterations or short test time is sufficient for checking that things work and longer run time just wastes cycles without much benefit.
Reduce the run time of various tests for which it was easy to do.
=> [PATCH v3] Speed up make check

scripts/ci/build.sh, scripts/ci/build_riscv64.sh
Run odp_sysinfo application after native ODP builds in the CI. This
application can provide more useful information in the CI log (e.g. CPU
model) compared to the previously used odp_hello application. When cross
compiling, the odp_sysinfo application is only built.
=> [PATCH v2] ci: run odp_sysinfo example after native builds

DEPENDENCIES
In the current installation of DPDK-20.11, configuring the location of
DPDK installation to the home directory is a required step. System-wide
installation of DPDK is also an option when ODP-DPDK is not able to link
to DPDK-20.11 by setting of PKG_CONFIG_PATH. This issue was observed on
Arm64 platforms.
Reviewed-by: Govindarajan <govindarajan.mohandoss@arm.com>
=> [PATCH v2] DEPENDENCIES: update DPDK-20.11 installation instructions

platform/linux-generic/include/odp/api/plat/byteorder_inlines.h, platform/linux-generic/include/odp/api/plat/packet_vector_inlines.h, platform/linux-generic/include/odp/api/plat/ticketlock_inlines.h, platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/include/odp_name_table_internal.h, platform/linux-generic/include/odp_pkt_queue_internal.h, platform/linux-generic/include/odp_traffic_mngr_internal.h, platform/linux-generic/include/protocols/eth.h, platform/linux-generic/include/protocols/ip.h, platform/linux-generic/include/protocols/ipsec.h, platform/linux-generic/include/protocols/sctp.h, platform/linux-generic/include/protocols/tcp.h, platform/linux-generic/include/protocols/thash.h, platform/linux-generic/include/protocols/udp.h, platform/linux-generic/odp_event.c, platform/linux-generic/odp_name_table.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_pkt_queue.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/null.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/pktio/stats/sysfs_stats.c, platform/linux-generic/pktio/tap.c
Don't include odp_api.h header inside the implementation files as it
unnecessarily includes all API headers. The remaining includes have been
cleaned up and grouped.
=> [PATCH v3] linux-gen: remove odp_api.h includes from implementation

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c
Remove unnecessary functions from odp_pktio_open() call paths.
This makes it easier to follow pktio entry initialization.
Make sure that pktio open always initializes all feature enable
flags to zero.
=> [PATCH v3] linux-gen: pktio: clean up pktio open and init

test/common/odp_cunit_common.h
Replace various fatal assertion macros with our own versions that
indicate to the compiler and static analyzers when they do not return.
=> [PATCH v2] test: cunit: reduce bogus warnings after fatal assertion failures

test/performance/odp_crypto.c
test: performance: crypto: use AAD of 8 bytes
AEAD algorithms are typically used with non-empty AAD, so use
AAD of 8 bytes in the tests when applicable.
test: performance: crypto: fix capability checking and enable bit mode
Check that an algorithm is supported and supports thew desired key
lengths etc before trying to test it. Do not assume that algorithms
work in byte mode but used them in bit mode if algorithm capabilities
indicate bit mode operation.
=> [PATCH v3] test: performance: crypto: use non-empty AAD and fix capability checking

test/validation/api/crypto/odp_crypto_test_inp.c
Checking of AAD length capability is entirely missing. Add a check that
the AAD length used in a test vector is actually supported before
executing the test.
=> [PATCH v3] validation: crypto: fix checking of AAD length capability

example/ipsec_api/odp_ipsec.c, example/ipsec_crypto/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_cache.c, example/ipsec_crypto/odp_ipsec_cache.h, example/ipsec_crypto/odp_ipsec_sa_db.c, example/ipsec_crypto/odp_ipsec_sa_db.h
example: ipsec_crypto: fix crypto capability checking
Check that the used algorithm as well as key length etc are supported
before trying to create a crypto session. Give up if the used ODP
implementation supports the algorithm in bit mode since the code expects
byte mode and would pass incorrect auth_range to an implementation which
works in bit mode.
example: ipsec_crypto: support bit mode algorithm implementations too
Do not give up if the underlying ODP supports an algorithm in bit mode
but scale the range parameter as appropriate.
=> [PATCH v2] example: ipsec_crypto: add capability checking and bit mode support

include/odp/api/abi-default/packet_io.h, include/odp/api/spec/packet_io.h, platform/linux-generic/include-abi/odp/api/abi/packet_io.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, scripts/checkpatch.pl, test/validation/api/pktio/pktio.c
Add new packet output queue size configuration option `odp_pktout_queue_param_t.queue_size`
and matching capabilities `odp_pktio_capability_t.min_output_queue_size` and `odp_pktio_capability_t.max_output_queue_size`.
V2:
- Mention `ODP_PKTOUT_MAX_QUEUES` in `odp_pktio_capability_t.max_output_queues` spec (Jerin)
V3:
- `ODP_PKTOUT_MAX_QUEUES` spec clarification (Petri)
-  Added output queue size validity check to implementation (Petri)
- Ignore camel case warnings from `PRIuPTR` usage
V4:
- Fixed commit message typos (Jere)
- Removed loopback pktio include changes (Jere)
- Clean loopback pktio internal plain queue before reconfigure/destroy
V5:
- Reviewed-by tags
=> [PATCH v6] api: pktio: add packet output queue size configuration option

include/odp/api/spec/timer.h, include/odp/api/spec/timer_types.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
New timer pool parameter which allows application to force timers not to expire before target time.
=> [PATCH v6] api: timer: expiration mode parameter

CHANGELOG, configure.ac
- sched: deprecate scheduling priority level defines
ODP_SCHED_PRIO_HIGHEST, ODP_SCHED_PRIO_NORMAL, ODP_SCHED_PRIO_LOWEST, and
ODP_SCHED_PRIO_DEFAULT
- tm: change meaning of odp_tm_enq_multi() return value of zero from
failure code to part of normal operation
- packet: remove references to deprecated odp_pktin_ts_res() and
odp_pktin_ts_from_ns() functions
- pktio: add ODP_PKTOUT_MAX_QUEUES define for the maximum number of packet
output queues
- pktio: add new packet output queue size configuration option
odp_pktout_queue_param_t.queue_size and matching capabilities
odp_pktio_capability_t.min_output_queue_size and
odp_pktio_capability_t.max_output_queue_size
- pktio: clarify …
=> [PATCH v2] api: increment ODP API version to 1.35.0.0

platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
Add aging support for packets enqeued for transmission to linux-gen. This ends up affecting traffic manager only as in practice there is no long output queuing elsewhere.
v2:
- address Jere's comments
v3:
- address Matias' comment
v4:
- rebase on-top-of #1495 
- add reviewed-by tags
v5:
- rebase
=> [PATCH v6] linux-gen: implement tx packet aging

platform/linux-generic/include/odp/api/plat/queue_inline_types.h
linux-gen: queue: add missing include directive
Include odp/api/event.h in queue_inline_types.h, since it uses odp_event_t. This omission also prevented the proto_stats.h API header from being compiled on its own.
v3:
- Include order.
v4:
- Rebase.
=> [PATCH v4] linux-gen: queue: add missing include directive

platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp_atomic.h, platform/linux-generic/arch/aarch64/odp_llsc.h, platform/linux-generic/arch/arm/odp_atomic.h, platform/linux-generic/arch/default/odp_atomic.h, platform/linux-generic/include/odp_atomic_internal.h, platform/linux-generic/include/odp_llqueue.h, platform/linux-generic/include/odp_types_internal.h, platform/linux-generic/odp_queue_lf.c, platform/linux-generic/odp_timer.c
```
linux-gen: define a 128-bit integer type
Define a 128-bit unsigned integer type _odp_u128_t in a new header
file odp_types_internal.h.
linux-gen: use new 128-bit integer type
Use _odp_u128_t instead of various ad hoc typedefs.
linux-gen: use _odp_u128_t instead of __int128
Replace usage of __int128 and __int128_t with _odp_u128_t.
```
v2:
- Matias' comment.
- Rebase.
=> [PATCH v2] linux-gen: 128-bit integer type cleanups

platform/linux-generic/odp_pool.c, platform/linux-generic/pktio/dpdk.c
Change zero-copy memory population to be done in separate virtually and
physically contiguous chunks, skipping those buffers that would span
hugepage boundaries.
v2:
- Clarify population with a comment
- Query hugepage size via SHM
v3:
- Add reviewed-by tags
=> [PATCH v3] linux-gen: dpdk: refactor zero-copy memory population

test/performance/odp_ipsec.c, test/performance/odp_ipsec_run.sh
Introduce an option to prepare and submit multiple packets for IPsec
processing.
ODP allows multi APIs with packet alloc, free & IPsec processing. Usage
of these APIs would help in improving performance with burst cases. New
option '--burst' or '-b' can be used to enable burst processing. When
specified without any arguments, burst size would be set as 32. User can
control burst size by specifying the optional argument.
Usage: 'odp_ipsec --burst=512'
=> [PATCH v7] test: performance: ipsec: introduce burst processing

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c
linux-gen: crypto: arm: avoid unneeded packet data copy
linux-gen: crypto: arm: use constant length memcpy for AAD
linux-gen: crypto: arm: optimize authentication tag handling
linux-gen: crypto: arm: combine cipher and auth into one function
=> [PATCH v6] crypto: miscellaneous ARM crypto optimizations

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, DEPENDENCIES, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/dpdk_parse.c
Main impacts:
- A few macro name deprecations, new names taken into use, old names
mapped to the new names with older versions.
- rte_eth_dev_set_mtu() is now forbidden to be used before device is
configured (rte_eth_dev_configure()), so "MTU-settability" checking
becomes less complete: support can still be inferred based on return
codes but proper error checking cannot be done due to the pre-config
condition.
v2:
- Update instructions in DEPENDENCIES
v3:
- Change MTU-settability support handling
- Handle `rte_eth_dev_info_get()` return value in `dpdk_open()`
v4:
- Add Github CI items for DPDK 21.11
=> [PATCH v4] linux-gen: dpdk: add support for DPDK 21.11

helper/include/odp/helper/cli.h, helper/include/odp/helper/linux/process.h, helper/include/odp/helper/linux/pthread.h, helper/include/odp/helper/threads.h
Added three missing ODP API header includes and removed one
include that was not needed.
=> [PATCH v2] helper: add missing odp_api.h includes

platform/linux-generic/m4/odp_crypto.m4
OpenSSL and ARMv8 crypto implementations are platform specific, so wrap the
AM_CONDITIONALs to avoid configure failures on other platforms:
configure: error: conditional "WITH_OPENSSL_CRYPTO" was never defined.
Suggested-by: Nithin Dabilpuram <ndabilpuram@marvell.com>
=> [PATCH v2] linux-gen: crypto: fix configure portability issue

platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec.c
linux-gen: ipsec: remove redundant inline operation result setting
linux-gen: ipsec: access union member properly to silence a warning
linux-gen: ipsec: fix uninitialized variable access with dummy packets
validation: ipsec: relax tunnel mode dummy TFC packet checking
validation: ipsec: get rid of an unchecked odp_ipsec_capability call
=> [PATCH v3] IPsec: a few small fixes

configure.ac
configure: remove fallbacks for standard int types and inline
Remove checking whether the compilation environment supports the inline
keyword and the standard fixed-width integer types. This also removes
the fallback preprocessor macros that autoconf would create if the
keyword or some of the types were not supported. The checking and the
fallback mechanism is unnecessary since ODP requires C11 and stdint.h.
configure: remove unused function and header checks
Remove checks for the existence of a set of function and header files.
The HAVE_ macros resulting from the checks are not used for anything.
=> [PATCH v2] configure: remove some unneeded checks from configure.ac

platform/linux-generic/include/odp_packet_dpdk.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_parse_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_parse.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c
v2 - v4:
- Only do packet_parse_reset(), etc., when needed.
- Include odp_macros_internal.h.
- Store parse layer in pktio_entry_t.
v5:
- Fix packet_init() / parse_reset() in dpdk pktio.
v6 - v7:
- Remove _odp_packet_parse_common_l3_l4_opt().
- Move pktio_entry::parse_layer.
- Add chksums temporary variable also in netmap and pcap pktio.
- Move commit `linux-gen: drop error packets according to pktin configuration`.
v8:
- Rebase.
- Petri's comment.
=> [PATCH v8] linux-gen: pktio and packet parse: some improvements and cleanups

include/odp/api/spec/classification.h, platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/include/odp_classification_internal.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/classification.h, test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/classification/odp_classification_testsuites.h
Add an action parameter to CoS parameters (odp_cls_cos_param_t). Action may be to accept or drop the packet classified to the CoS.
Add CoS specific statistics counters (odp_cls_cos_stats_t) and matching capabilities (in odp_cls_stats_capability_t). Statistics counters can be read with odp_cls_cos_stats().
Branched from #1498.
v1 - v4:
- Add commit linux-gen: cls: return odp_cos_action_t from _odp_cls_classify_packet()
- loop: Fix in_errors.
v5:
- Rebase on #1498.
- Rename ACTION_DROP to ACTION_ENQUEUE and tweak documentation accordingly.
- Add mention of final matching CoS.
v6:
- Add capability for max number of CoS with statistics.
- Add validation test for max number of CoS.
- Add validation test for max number of CoS with statistics.
v7:
- Rebase.
v8:
- Petri's comments.
v9 - v11:
- …
=> [PATCH v13] api: cls: add cos action and cos specific counters

doc/users-guide/users-guide-crypto.adoc, include/odp/api/abi-default/event_types.h, include/odp/api/spec/crypto.h, platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/include-abi/odp/api/abi/event_types.h, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_event.c, test/performance/odp_crypto.c, test/validation/api/crypto/odp_crypto_test_inp.c
Depracate odp_crypto_operation() and the associated data structures and the completion event.
The odp_crypto_operation() function is a bit problematic since it can be synchronous or asynchronous on per-packet basis without application having control on it. Uncontrolled sync versus async behaviour can have adverse effects on packet ordering and application design in general. The function is also somewhat redundant with the newer odp_crypto_op() and odp_crypto_op_enq() functions that provide explicit control on the crypto operation completion behavior.
=> [PATCH v10] api: crypto: deprecate odp_crypto_operation()

CHANGELOG, configure.ac
- cls: add action parameter odp_cos_action_t to CoS parameters
- crypto: deprecate odp_crypto_operation() and the associated data
structures and the completion event
- tm: split odp_tm_capabilities_t.tm_queue_threshold capability into byte
and packet modes
- tm: split odp_tm_level_capabilities_t.tm_node_threshold capability into
byte and packet modes
- cls: add CoS specific statistics counters (odp_cls_cos_stats_t) and
matching capabilities (odp_cls_stats_capability_t)
- common: convert 'unsigned int' types to 'uint32_t'
- tm: remove unused TM shaper color enum odp_tm_shaper_color_t and
ODP_NUM_SHAPER_COLORS define
=> [PATCH v2] api: increment ODP API version to 1.36.0.0

platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/loop.c, test/validation/api/pktio/pktio.c
linux-gen: packet: put crypto and ipsec results in a union in packet hdr
linux-gen: traffic_mgr: add assert to suppress warnings
linux-gen: pktio: loop: remove unnecessary odp_ipsec_result() call
validation: pktio: trigger fatal failure before dividing by zero
=> [PATCH v3] A couple of very small clean-ups

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c
validation: crypto: remove odp_packet_has_error() check after crypto error
ODP API does not say that odp_packet_has_error() must return true after
crypto operation errors. odp_packet_has_error() indicates various packet
parsing errors and crypto operations are not parsing the packet.
Remove the odp_packet_has_error() check to prevent potential test failures
with API compliant ODP implementations.
linux_gen: remove crypto error from packet error flags
Remove the unnecessary crypto_err parse flag from packet header.
odp_packet_has_error() is supposed to indicate parse errors not crypto
processing errors, which are indicated through odp_crypto_result_t.
Remove the flag and its setting in crypto implementations as the flag
is not needed and may cause subtle API spec violations.
=> [PATCH v3] remove crypto error from packet error flags

platform/linux-generic/odp_pool.c
Add support for counting the total number of alloc and free operations.
=> [PATCH v2] linux-gen: pool: add support for total_ops statistic counter

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, DEPENDENCIES, include/odp/autoheader_internal.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/include/odp_packet_dpdk.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/libodp-linux.pc.in, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_xdp.m4, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_pool_mem_src_ops.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/io_ops.c, platform/linux-generic/pktio/socket_xdp.c
This patchset introduces a (minimal) AF_XDP socket based packet I/O implementation. Implementation is based on `libxdp` wrapper library and currently provides the zero-copy variant.
L2fwd performance has been tested with Mellanox ConnectX-5 and Intel XL710 adapters, throughput ranging from 6.8 to 7.8 Gbit/s respectively with a single core and 64 B frames.
Additionally, packet pool configuration adjustment by zero-copy-based packet I/Os is now generalized and done via a new interface.
v8:
- Add name field to `_odp_pool_mem_src_ops_t` to be used in pool prints and debugging
v9:
v10:
- Free fill and completion queue packets on packet I/O close.
v11:
v12:
- Add reviewed-by tags
- Sleep after socket create and delete to take into account …
=> [PATCH v13] linux-gen: pktio: add AF_XDP socket based packet IO

platform/linux-generic/include/odp_packet_internal.h
`PKT_EXTRA_LEN` and `PKT_EXTRA_TYPE_DPDK` seems to have become unused
when DPDK zero copy implementation was improved a while ago. Remove
them.
v2:
- Rebase
- Add reviewed-by tag
=> [PATCH v2] linux-gen: packet: remove unused defines

doc/Doxyfile_common, include/odp/api/spec/crypto.h, include/odp/api/spec/traffic_mngr.h
Have Doxygen expand the ODP_DEPRECATED_API macro so that it includes
conditional deprecated segments of API headers in document generation
when ODP is configured with --enable-deprecated.
v2:
- Include the deprecated secions in documentation always, regardless of the --enable-deprecated option, as suggested by @psavol.
- Add an API patch (that does not modify the actual API) to improve documentation generation for various deprecated fields.
=> [PATCH v3] doc: include deprecated APIs in documentation

test/validation/api/traffic_mngr/traffic_mngr.c
Avoid maybe-uninitialized warnings from GCC-10/11.
=> [PATCH v2] validation: tm: fix maybe-uninitialized warnings

test/validation/api/pool/pool.c
External pool spec does not limit the max user area size to be non-zero.
So remove the check for non-zero max user area size for external pools
in pool_main test case.
=> [PATCH v3] validation: pool: allow zero max user area size for external pools

test/validation/api/crypto/odp_crypto_test_inp.c
Crypto session create API returns a negative value on failure.
To check for the error code for failure, status parameter need to
be explicitly checked not the return value of the API.
=> [PATCH v5] validation: crypto: fix check for session create error

platform/linux-generic/odp_stash.c
Allocate per stash SHM memory from single VA memory to enable calling
odp_stash_create() after fork (process mode).
Reported-by: Carl Wallen <carl.wallen@nokia.com>
=> [PATCH v3] linux-gen: stash: alloc shm memory using ODP_SHM_SINGLE_VA in process mode

platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/test/example/ipsec_api/pktio_env, platform/linux-generic/test/example/ipsec_crypto/pktio_env
TM and openssl crypto are not compatible with process mode, so disable TM and libssl based crypto algorithms in process mode.
=> [PATCH v3] linux-gen: disable TM and most of openssl crypto in process mode

platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_parse_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_parse.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/socket_xdp.c, platform/linux-generic/pktio/tap.c
v2:
- Add commit `linux-gen: pktio: remove struct pktio_entry::in_chksums`
v3:
- Rebase.
- stats_extra comment.
v4 - v6:
- Matias' comments.
- packet_to_pool() call added also to xdp.
v7:
- packet_to_pool() call added also to dpdk zero copy.
v8:
- Rebase.
- Add commit `linux-gen: pktio: dpdk: move reading pkt_dpdk_t::supported_ptypes`
- Set data pointers in pkt_hdr before packet_to_pool() in xdp.
- Add review tags. (Matias)
v9:
- Add review tags. (Tuomas)
=> [PATCH v9] linux-gen: pktio: a couple of parse and classification related fixes

test/validation/api/classification/odp_classification_basic.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/dma/dma.c, test/validation/api/init/init_main.c, test/validation/api/ipsec/ipsec_test_out.c, test/validation/api/pktio/pktio.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c, test/validation/api/scheduler/scheduler.c, test/validation/api/stash/stash.c, test/validation/api/timer/timer.c, test/validation/api/traffic_mngr/traffic_mngr.c
validation: improve testing of default values set by init functions
Improve testing of the default values set by various init functions by
checking the defaults twice: once after memsetting the to-be-initialized
structure to zero before the init call and once after memsetting to 0xff.
This way missing initialization can always be detected.
validation: init: test default value setting by odp_init_param_init()
Test that odp_init_param_init() initializes parameters to the specified
default values.
=> [PATCH v3] validation: test default value setting by init functions better

platform/linux-generic/odp_queue_scalable.c, test/validation/api/dma/dma.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c
Added test cases to check that pools and queue can be created with the same name as API promises. Added also missing default value checks when queue param is NULL.
=> [PATCH v3] validation: test pool and queues with same name

include/odp/api/spec/packet_io.h
Clarify that odp_pktout_send_lso() can be used also for packets
that have payload less than 'max_payload_len' bytes. These
packets do not need segmentation, but it is implementation
dependent if those will be segmented or not.
=> [PATCH v2] api: pktio: clarify that LSO send handles small packets

CHANGELOG, configure.ac
- pktio: clarify that LSO send handles small packets
- stash: change get/put function parameter names
- tm: add rate limit mode in shapers
=> [PATCH v2] api: increment ODP API version to 1.37.1.0

platform/linux-generic/odp_schedule_basic.c
Currently, scheduler selects group first (round robin), and then finds highest priority queue from that. This leads to bad response time to high priority events when there are multiple groups, but only few of those have high priority queues.
This PR changes scheduler to check first highest priority level on all groups. This causes more work for each schedule call. A new mask of active groups per priority is introduced to optimize the additional checking.
=> [PATCH v6] linux-gen: scheduler: improve priority scheduling

platform/linux-generic/include/odp_packet_internal.h
Move rarely used 'timestamp' member of odp_packet_hdr_t, so that both more
commonly used 'uarea_addr' and 'user_ptr' members will fit into the second
64-byte cache line.
=> [PATCH v2] linux-gen: packet: reorder packet header members

test/performance/odp_l2fwd.c
Inlined functions used in fast path to improve forwarding performance.
Signed-off-by: Shijith Thotton <sthotton@marvell.com>
=> [PATCH v2] test: l2fwd: inline fast path functions

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/netmap.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/stats/packet_io_stats.c, platform/linux-generic/pktio/tap.c
This series attempts to unify statistics handling in the recv functions in different pktios.
v2:
- Add commit `linux-gen: pktio: loop: support discards counter in queue statistics`
- Add commit `linux-gen: pktio: stats: fix error handling for socket type pktio`
v3:
- _odp_sock_stats_get -> sock_stats_get
v4:
- Use atomic counters.
v5:
- Rebase.
- Remove xdp changes.
- Counter increments on one line.
v6:
=> [PATCH v6] linux-gen: pktio: statistics fixes and cleanups

test/performance/odp_l2fwd.c
When flow aware scheduling is enabled, packet's initial flow ID is the flow
hash. So, flow hash generation needs to be enabled in flow aware mode.
=> [PATCH v3] test: l2fwd: enable flow hashing in flow aware scheduling mode

platform/linux-generic/arch/default/odp/api/abi/atomic_generic.h
Pointer aliasing caused by pointer casting in _odp_atomic_load_u128() seems
to confuse GCC 12.1 so that GCC issues a warning about a use of an
uninitialized variable. The generated code was anyway ok in the compiler
versions I tested.
Replace pointer casting in the problematic code by type punning through
a union, which appears to have been valid C since C99. The generated code
is not affected in various GCC and Clang versions tested.
=> [PATCH v2] linux-gen: atomic: fix build error with gcc 12

test/validation/api/Makefile.am, test/validation/api/init/.gitignore, test/validation/api/init/Makefile.am, test/validation/api/init/init_main.c
At present, test binary for init_test_param_init is not created.
This patch creates it appropriately from init_main.c.
Signed-off-by: Gowrishankar Muthukrishnan <gmuthukrishn@marvell.com>
=> [PATCH v5] validation: init: create binary for init_test_param_init test

example/ping/odp_ping.c, example/ping/ping_run.sh, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/null.c
Remove incomplete and unnecessary support of promiscuous mode set operation from loop and null interfaces.
Use promiscuous mode in ping example testing with pcap, since pcap file of the test case has different dest MAC address than the interface.
=> [PATCH v2] linux-gen: promiscuous mode fixes

test/common/odp_cunit_common.c, test/common/odp_cunit_common.h
CUnit is not thread-safe and not aware of process mode, which causes
problems when CUnit assertions are used in multithreaded tests:
- Updating the recorded assert failures has data races
- Assertion failures in other than the main process are lost
- The longjmp performed at fatal assertion failure tries to jump to
a stack frame of another thread, which is doomed to fail badly
Fix the problems by wrapping the commonly used CUnit assertions with
ODP macros and an ODP function that calls CUnit only if running in the
main thread and the main process. In other threads/processes record
failed assertions in shared memory and re-play them to CUnit within
the main thread/process when becoming single threaded again in
odp_cunit_thread_exit().
This does not solve the general issue that careless use …
=> [PATCH v3] test: cunit: fix cunit asserts for multithreaded test apps

platform/linux-generic/include/odp_global_data.h, platform/linux-generic/odp_system_info.c
Number of CPUs is stored into odp_global_ro.num_cpus_installed.
Remove code maintaining a redundant copy of the same value in
odp_global_ro.system_info.cpu_count. Rename systemcpu() to
system_cache_line(), as code remaining in the function handles
system cache line size only.
=> [PATCH v2] linux-gen: system: remove redundant cpu count code

CHANGELOG, configure.ac
- cpumask: allow usage of NULL pointer with odp_cpumask_default_worker()
and odp_cpumask_default_control() calls
- cpumask: clarify odp_cpumask_default_worker() and
odp_cpumask_default_control() specifications
- pktio: specify that interfaces that support promiscuous mode set
operation have promiscuous mode disabled by default
- pool: add new statistics counters for reading per thread pool cache usage
- stash: add odp_stash_print() function for printing implementation
specific debug information to the ODP log
- stash: add statistics counters to stash API
=> [PATCH v3] api: increment ODP API version to 1.37.2

.github/workflows/ci-pipeline.yml
Update checkpatch-action to v8 to fix failures caused by dubious ownership
in git repository.
=> [PATCH v2] github_ci: update checkpatch-action version

platform/linux-generic/odp_pool.c, test/validation/api/pool/pool.c
This patchset fixes `odp_packet_is_valid()` behavior with packets allocated from external memory pools. Currently the check always fails due to pool base and maximum address fields being zero. This is fixed by properly initializing the addresses utilizing the populated memory chunks.
v2:
=> [PATCH v3] linux-gen: pool: properly initialize ext pool base and max addresses

platform/linux-generic/odp_timer.c
In timer_reset() and timer_cancel() functions, old tick_buf is read
in every iteration of the while loop. This code is redundant since
CAS operation will update tick_buf values on failure.
This change gave 1.5-2.5% performance improvement in CPU cycles on Neoverse N1 system.
=> [PATCH v2] linux-gen: timer: initialize old tick_buf only once

helper/cli.c, platform/linux-generic/odp_packet_io.c
This patchset adds more commands to helper CLI for printing packet I/O total, queue, event queue and extra statistics.
v2:
- Copyright updated
- Refactored packet I/O handle getter
v4:
- Moved some commands out of `call` parent
- Reverted the I/O handle getter change
- Added new functions for queue stat printing
v5:
=> [PATCH v5] helper: cli: add more packet I/O statistics printing commands

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_ipsecfwd.c
`odp_ipsecfwd` is a simple IPsec performance testing utility to profile
ODP IPsec implementation performance.
Tester supports running IPsec processing in multiple workers and in a
few different queue setups. Packets are forwarded according to passed
forwarding configuration.
v4:
- Review comments addressed
- All algorithms defined in spec now exposed in tester
v5:
- Fixed help text
- Dropped IPsec-unsupported algorithms from exposed algorithms
v7:
- Adjusted MAC address fetch error log
- Adjusted forwarding entry parsing format
=> [PATCH v7] test: performance: add IPsec performance tester

test/common/odp_cunit_common.c
Added guarding #ifndef to avoid re-definition of _GNU_SOURCE.
=> [PATCH v2] validation: common: add missing guard

.github/workflows/ci-pipeline.yml, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, scripts/ci/build_static_x86_64.sh, test/performance/odp_crypto.c, test/validation/api/crypto/odp_crypto_test_inp.c
Add build only jobs that use static linking. Test LTO mainly with static linking since that exposes more code to LTO analysis that dynamic linking.
=> [PATCH v2] ci: update LTO builds

test/validation/api/timer/timer.c
Many timer validation tests use each allocated timer only once. Applications commonly reuse single shot timers after they expire or are cancelled. Added loop a repeat loop into single shot timer tests. Selected repeat count and timeout values so that test cse duration remain about the same than before (1 sec).
=> [PATCH v3] validation: timer: reuse timer in test cases

.github/workflows/ci-pipeline.yml, .github/workflows/coverity.yml
Ubuntu 18.04 GitHub hosted runners are being deprecated, so start using
Ubuntu 20.04 runners instead. Netmap tag has been updated to support the
newer Linux kernel.
=> [PATCH v2] github_ci: upgrade to ubuntu 20.04 runners

platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_common.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_testsuites.h
This patchset marks implemented but missing IPsec SPI PMR and class-of-service hash protocol capabilities enabled in classification. Additionally, add validation tests for `ODP_PMR_IPSEC_SPI` variants.
v2:
- Added valid values to AH and ESP header fields when creating test packets
v3:
- Fixed AH header length usage
v4:
- Removed extra endianness swap in `verify_pmr_ipsec_spi()` and changed validation tests accordingly
v5:
=> [PATCH v5] linux-gen: cls: mark implemented capabilities enabled

config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Add new configuration file options for adjusting scheduler burst sizes per
scheduled queue type. Use 32-bit fast path variables for improved
arithmetic operation performance.
=> [PATCH v4] linux-gen: sched: add configuration options for per queue type burst sizes

platform/linux-generic/Makefile.am, platform/linux-generic/include/odp_print_internal.h, platform/linux-generic/odp_print.c, platform/linux-generic/odp_schedule_basic.c
Print full lines from odp_schedule_print() call, so that log remain readable also when other threads print into it simultaneously.
=> [PATCH v6] linux-gen: sched: print full lines

platform/linux-generic/include/odp_debug_internal.h, platform/linux-generic/include/odp_global_data.h
Remove the separate check_printf_format() function and move
ODP_PRINTF_FORMAT, so that the variable argument in _ODP_LOG_FN is
substituted only once, to avoid duplication of side effects.
v2:
- Rebase.
=> [PATCH v2] linux-gen: debug: avoid duplication of macro argument side effects

helper/include/odp/helper/cli.h, helper/include/odp/helper/odph_api.h
This reverts commit 65a7f559c173ddbe9738c9c03bf9dbfc52279bc0.
cli.h is optional, so it cannot be included unconditionally.
v2:
=> [PATCH v2] Revert "helper: allow cli.h to be included individually"

helper/include/odp/helper/threads.h, helper/threads.c
Memory for odph_thread_create() output thread table is given by application, so there is no guarantee that the memory can be used to synchronize child process startup. Fix this by using mmap() to create the necessary memory for thread startup synchronization.
=> [PATCH v2] helper: threads: fix synchronized thread start in process mode

helper/cli.c
- Remove the "call" command and move commands to top level.
- Prefix commands with "odp_".
- Add command odp_pool_print_all.
- Add command odp_schedule_print.
- Alphabetize the commands.
v2:
=> [PATCH v2] helper: cli: add commands, reorganize existing commands

platform/linux-generic/include/odp_atomic_internal.h, platform/linux-generic/odp_timer.c
Use newer and ODP standardized 128-bit atomic APIs in the timer
processing functions. ODP timer library was the sole user of the
_odp_atomic_u128_cmp_xchg_mm() API so this can be removed as well.
The first commit is a part of PR #1610 which has been approved. It will be dropped when the PR is merged
=> [PATCH v5] linux-gen: timer: use new 128-bit atomic APIs for timer processing functions

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c
commits in v2:
linux-gen: crypto: fix pool checking before metadata copying
The packet metadata copying check in a crypto operation assumes that the
pool of the output packet is the pool configured in the session, but that
is not necessarily the case when an ODP application passes an explicit
output packet to a crypto operation. In that case the pool of the session
could even be ODP_POOL_INVALID.
linux-gen: crypto: reuse input packet as output packet if possible
Do not allocate a new packet but reuse the input packet when a crypto
operation is requested to allocate the output packet and the input
packet and the session use the same packet pool.
Make the code cleaner by moving output packet allocation and preparation
to its own function from crypto_int().
=> [PATCH v4] crypto: bug fix and cleanup

test/performance/odp_ipsecfwd.c
Add burst support to packet handling. This enables passing more than a single packet at a time to IPsec processing pipelines, potentially increasing tester throughput.
v2:
- Added a retry logic to IPsec in/out enqueuing
v3:
- Inlined IPsec in/out enqueuing retry logic
v4:
- Rebased
=> [PATCH v4] test: ipsecfwd: add support for burst processing

include/odp/api/spec/crypto.h
Mention that ODP_CIPHER_ALG_ZUC_EEA3 and ODP_AUTH_ALG_ZUC_EIA3 may support 256 bit key length but that the support is experimental and subject to change. The standardization status of the algorithms is open and it is not clear what the defining specifications are. There are are already two different initialization schemes with different IV lengths defined.
Mention NEA3 and NIA3 in addition to EEA3 and EIA3 in the API as they are identical, respectively.
=> [PATCH v3] api: crypto: add experimental ZUC-256 support

include/odp/api/spec/buffer.h, include/odp/api/spec/packet.h, include/odp/api/spec/pool_types.h, include/odp/api/spec/timer.h, platform/linux-generic/include/odp/api/plat/event_vector_inline_types.h, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp/api/plat/packet_vector_inlines.h, platform/linux-generic/include/odp/api/plat/timer_inline_types.h, platform/linux-generic/include/odp/api/plat/timer_inlines.h, platform/linux-generic/include/odp_buffer_internal.h, platform/linux-generic/include/odp_event_vector_internal.h, platform/linux-generic/include/odp_timer_internal.h, platform/linux-generic/odp_buffer.c, platform/linux-generic/odp_packet_vector.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_timer.c, test/validation/api/buffer/buffer.c, test/validation/api/packet/packet.c, test/validation/api/pktio/pktio.c, test/validation/api/pool/pool.c, test/validation/api/timer/timer.c
Packets have already user area for storing user specific metadata, which is preserved while packet is modified or stored into a queue, etc. Introduce user area to other event types (that are allocated from a pool) as well.
=> [PATCH v10] api: pool: user area in buffer, timeout and vector events

CHANGELOG, configure.ac
- pool: change odp_pool_capability_t.pkt.max_uarea_size to state that the value of zero means user area is not supported
- buffer: add odp_buffer_user_area() function which returns pointer to the user area
- crypto: add experimental ZUC-256 support
- packet: add odp_packet_vector_user_area() function which returns pointer to the user area
- packet: add new user flag metadata to packets and packet vectors
- pool: add user area size capability and parameter into buffer, timeout, and vector event pools
- pool: specify that the default value of odp_pool_param_t.pkt.uarea_size is zero
- stash: add batch variants of all put/get functions and capabilities for maximum supported batch sizes
- …
=> [PATCH v3] api: increment ODP API version to 1.38.0.0

test/validation/api/classification/odp_classification_test_pmr.c
Test ODP_PMR_ETHTYPE_X and ODP_PMR_VLAN_ID_X also with packets that have only single VLAN.
=> [PATCH v2] validation: cls: improve most inner VLAN test cases

platform/linux-generic/include/odp_parse_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_parse.c, test/validation/api/packet/packet.c
linux-gen: packet: fix odp_packet_parse() with nonzero offset
validation: packet: test packet parsing more with nonzero offset
=> [PATCH v3] packet parsing bugfix and validation test improvement

test/performance/odp_scheduling.c
Fix invalid 'array-bounds' error in GCC-9 -O3 build.
=> [PATCH v1] test: performance: scheduling: fix array-bounds build error

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, .github/workflows/coverity.yml, .github/workflows/gh-pages.yml
Update GitHub Checkout action to V3. V2 uses Node.js 12 which is being deprecated by GitHub.
=> [PATCH v3] github_ci: update checkout action to v3

platform/linux-generic/pktio/socket_xdp.c
When handling pending TX descriptors, define array for sent packets only if there actually were packets sent, i.e. corresponding descriptors available in a completion queue.
v2:
=> [PATCH v2] linux-gen: socket_xdp: fix potential undefined behavior

test/validation/api/timer/timer.c
DPDK rte_lcore_state_t.WAIT exposed by odp-dpdk implementation conflicts with WAIT enum. Prefix all test internal enumerations to avoid conflicts.
=> [PATCH v3] validation: timer: fix naming conflict

test/performance/Makefile.am
The previous fix to this does not work when ODP is configured with --without-examples and built out-of-tree (i.e. configure is run in some other directory than ODP base directory).
Fix by adding a recipe to explicitly go to the generator directory to build it.
v2:
- Re-word subject line.
=> [PATCH v2] test: perf: l2fwd: fix more dependency to odp_generator

platform/linux-generic/odp_timer.c
Fix data race between timer free call initializing the destination queue and timer expire call reading it.
=> [PATCH v2] linux-gen: timer: fix dest queue race

test/performance/odp_packet_gen.c
This patchset adds option to measure latency with `odp_packet_gen`. Sent packets can have a timestamp in their payload which is then utilized at reception time to calculate latency. Additionally:
- option to disable packet reference usage (enables latency measurements),
- option to disable UDP checksum calculations,
- option to disable payload filling
are added.
v2:
- Added a new patch where error/warning logs are printed with `ODPH_ERR()`
- Added a new patch where new options are printed in startup configuration summary dump
v3:
v4:
- Rebased
=> [PATCH v4] test: packet_gen: add option for latency measurements

platform/linux-generic/odp_crypto_openssl.c, test/performance/odp_crypto.c
test: performance: crypto: improve printouts when session creation fails
test: performance: crypto: fix out-of-bounds hash result offset
linux-gen: crypto: check hash result offset against pkt len in debug builds
test: performance: ipsec: authenticate cipher text instead of vice versa
test: performance: crypto: add zuc-eea3 and zuc-eia3 tests
=> [PATCH v2]  crypto perf test bug fix and improvements

helper/threads.c
Add more debug information to thread startup timeout error message from
odph_thread_create().
=> [PATCH v4] helper: threads: improve odph_thread_create() timeout error message

platform/linux-generic/odp_ipsec_events.c
When freeing IPsec status events, reset type of the event to `ODP_EVENT_BUFFER` before freeing. This way next allocation of the freed buffer will have the correct type set passing internal sanity checks.
v3:
- Rebased
=> [PATCH v3] linux-gen: ipsec: fix ipsec status event free

platform/linux-generic/odp_timer.c
GCC 9.2 warns that queue handle may be used uninitialized, although it is set always when the event handle is set. Initialize queue handle to avoid the warning.
=> [PATCH v1] linux-gen: timer: fix GCC 9.2 warning

test/performance/odp_crypto.c
GCC 9.2 complains that crypto capability structure might be uninitialized when used even though it should always be properly initialized by a successful `odp_crypto_capability()` call.
Fix this by simply always initializing the structure to zero.
v2:
- Rebased
=> [PATCH v2] test: crypto: fix GCC 9.2 warning

test/performance/odp_ipsecfwd.c
This patchset adds an option to not use scheduler with `odp_ipsecfwd`. Tester throughput increases slightly as scheduling overhead disappears. 
Additionally, packets are now forwarded with bursts instead of single packet at a time after lookup, this further increases tester thoughput if a lot of packets are destined to the same output per processing loop.
v2:
- Added a separate patch where existing processing functions are moved earlier
- Changed "no scheduler" option to "direct RX" option and changed title accordingly
- Rebased
v3: 
- Addressed Janne's comments
v4:
=> [PATCH v4] test: ipsecfwd: add option for direct reception 

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c
Use non-random but still unpredictable IVs for AES-CBC to get rid of random number generation overhead. DES-CBC and 3DES-CBC continue using random IVs due to their shorter IV length. Make also a couple of small optimizations in IV handling.
=> [PATCH v3] linux-gen: ipsec: improve IV generation and use non-random IVs

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_stress.c
Add test application that can be used to stress CPU, memory and HW accelerators. Stress level can be modified with -m option. Minimal stress level (-m 0) can be used e.g. to measure idle power, and compare that to higher levels. The next level (-m 1) does simply a memcpy() from the first half of worker memory to the second half. More advanced levels can be added later.
v2: Added CPU load and total memcpy speed statistics
=> [PATCH v3] test: stress: add new ODP stress test

test/validation/api/atomic/atomic.c, test/validation/api/barrier/barrier.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/lock/lock.c
CUnit API is included through odp_cunit_common.h. Remove direct CUnit includes from test applications.
=> [PATCH v2] test: validation: remove unnecessary cunit includes

test/common/odp_cunit_common.c, test/performance/odp_cpu_bench.c
By default run all the tests on worker thread and
provide option to run tests on control thread.
This is needed because control threads will be slower and have less performance w.r.t fast path API.
For example, in our case, control thread will only support packet burst of 1 which would fail pktio_main test
case(pktio_test_recv_queue()) which tries to do burst enqueue of packets.
=> [PATCH v3] test: cunit: provide option to run tests on control thread

include/odp/api/abi-default/packet_types.h, include/odp/api/spec/packet.h, include/odp/api/spec/packet_types.h, platform/linux-generic/include-abi/odp/api/abi/packet_types.h
Move odp_proto_l2_type_t, odp_proto_l3_type_t, and odp_proto_l4_type_t types and defines from ABI to API header. L3 protocol type define values have been changed to match actual EtherType values. The size of odp_proto_l3_type_t is increased to accommodate this.
Allow odp_packet_l3_type() and odp_packet_l4_type() functions to return also other protocol types than the ones defined in ODP_PROTO_L3_TYPE_* and ODP_PROTO_L4_TYPE_* defines. This enables implementations to support additional protocols without having to add each one to the ODP API.
=> [PATCH v4] api: packet: support additional l3 and l4 protocol types

include/odp/api/spec/crypto.h
Fix a stale reference to the renamed hash_result_not_in_auth_range session parameter to use the correct name (hash_result_in_auth_range) in the comment text of hash_result_offset. The parameter was renamed before the patch was merged to master but one occurrence of the old name was missed.
=> [PATCH v3] api: crypto: fix out-of-date text in hash_result_offset specification

include/odp/api/abi-default/shared_memory.h, include/odp/api/spec/shared_memory.h, include/odp/api/spec/system_info.h, platform/linux-generic/include-abi/odp/api/abi/shared_memory.h, platform/linux-generic/odp_ishm.c, platform/linux-generic/odp_shared_memory.c, test/validation/api/shmem/shmem.c, test/validation/api/system/system.c
Adds new system and SHM API functions which can be used to monitor/debug ODP instance memory usage.
v2: updated documentation of odp_shm_reserve() operation without flags (3rd commit)
v3: added system meminfo implementation and test
v4: added odp_shm_segment_info() implementation and test
v6: Moved IOVA/PA_INVALID defines to ABI file. Use defines in implementation and test.
=> [PATCH v7] api: memory usage debug info

include/odp/api/spec/classification.h, include/odp/api/spec/packet_io_types.h, platform/linux-generic/odp_packet_io.c, test/validation/api/pktio/pktio.c
Initial support to enable PFC flow control. It is left implementation specific (for future development) how packet output halts a traffic priority level.
v2:
- Renamed config parameter names to pause_rx/pause_tx. These match the current names in link info.
- Added flow control capability fields
v3:
- Rebased
- Grouped API config parameters inside "flow_control" structure
- Added minimal implementation and first test case
v4:
- Rebased
- Added pause/PFC configuration test case
=> [PATCH v6] api: pktio: PFC support

example/classifier/odp_classifier.c, include/odp/api/spec/classification.h, platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/classification/odp_classification_testsuites.h
- Clarify that it is implementation defined which PMR is selected if multiple PMRs match (in a CoS)
- Deprecate drop policy and odp_cos_with_l2_priority()
v2: split first commit into separate clean up and API spec clarification commits
v3: rebase
=> [PATCH v4] api: cls: spec clarification and deprecations

CHANGELOG, configure.ac
- cls: deprecate odp_cos_with_l2_priority() function
- cls: deprecate packet drop policy option and related functions
- shm: disallow usage of invalid SHM handles with odp_shm_info()
- buffer: add multi variants of event conversion functions
- cls: add PFC priority level to back pressure parameters
- cls: clarify PMR specification for the case of multiple PMRs matching within a CoS
- crypto: fix a stale reference to renamed hash_result_not_in_auth_range session parameter
- packet: add support for additional L3 and L4 protocol types
- pktio: add ODP_PKTIN_MAX_QUEUES define for maximum number of packet input queues
- pktio: add new packet input queue size configuration option and …
=> [PATCH v2] api: increment ODP API version to 1.39.0.0

test/performance/odp_sched_perf.c
Print SHM memory reservations which may be useful information when debugging.
=> [PATCH v1] test: sched_perf: print SHM in verbose mode

test/validation/api/shmem/shmem.c
Use test default block size if odp_shm_capability_t.max_size is zero.
=> [PATCH v2] validation: shm: fix shmem_test_info() block size

.github/workflows/ci-pipeline-arm64.yml, DEPENDENCIES, include/odp/autoheader_internal.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/libodp-linux.pc.in, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_crypto.m4, platform/linux-generic/m4/odp_ipsec_mb.m4, platform/linux-generic/odp_crypto_ipsecmb.c
The first commit adds the support for detecting the presence of the Arm-optimized Multi-buffer Crypto for IPSec Library and enabling it if present.
The second and third commits integrate the ZUC128 and ZUC256 EEA3 and EIA3 algorithms to ODP.
v2: Update Makefile.am to fix build issue
v1: https://github.com/OpenDataPlane/odp/pull/1694
=> [PATCH v18] linux-gen: crypto: integrate Arm-optimized Multi-buffer Crypto for IPSec Library

DEPENDENCIES
Bump IPsec MB library version to SECLIB-IPSEC-2022.12.13, fix the missing imb_set_errno in some functions.
Signed-off-by: Tianyu Li <tianyu.li@arm.com>
=> [PATCH v2] dependencies: update IPsec MB library version

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c
The Arm crypto library may read up to 16 bytes of data when it is reading
a 12 byte IV. If the IV provided by the caller ends at a page boundary and
the next page is not mapped to readable memory, bad things can happen.
Fix the problem by always copying the user provided IV to a bigger
temporary buffer that is passed to the crypto library.
=> [PATCH v2] crypto: arm: fix out-of-bounds IV read access

config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Add new configuration option `sched_basic.order_stash_size`, which can be used to adjust the size of implementation internal per thread ordered queue reorder stash. If 'order_stash_size' > 0, events may be dropped by the implementation if the target queue is full. To prevent this set 'order_stash_size' to 0.
=> [PATCH v2] linux-gen: sched: add config option for adjusting ordered queue stash size

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_bench_buffer.c, test/performance/odp_bench_misc.c, test/performance/odp_bench_packet.c
Test overhead of miscellaneous set of API functions. For example, time and CPU cycle count APIs may be called often in fast path.
=> [PATCH v4] test: bench_misc: add new perf test for misc API calls

doc/images/timeout_fsm.gv, doc/images/timer_fsm.gv, doc/users-guide/users-guide-timer.adoc, example/debug/odp_debug.c, example/timer/odp_timer_accuracy.c, example/timer/odp_timer_simple.c, example/timer/odp_timer_test.c, test/performance/odp_sched_pktio.c, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
Remove usage of deprecated API functions `odp_timer_set_abs()` and `odp_timer_set_rel()`.
=> [PATCH v4] example/test/validation: remove usage of deprecated timer functions

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, include/odp/autoheader_external.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/README, platform/linux-generic/include/odp/api/plat/event_validation_external.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp/api/plat/pool_inline_types.h, platform/linux-generic/include/odp/api/plat/queue_inlines.h, platform/linux-generic/include/odp_event_internal.h, platform/linux-generic/include/odp_event_validation_internal.h, platform/linux-generic/include/odp_init_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_event_validation.m4, platform/linux-generic/odp_event.c, platform/linux-generic/odp_event_validation.c, platform/linux-generic/odp_init.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_queue_basic.c, test/performance/odp_ipsec.c, test/performance/odp_sched_pktio.c
Add support for runtime event validation (initially buffer endmark
checking). Event validation can be enabled during configure with
'--enable-event-validation' [warn/abort] or  with --enabled-debug=full.
When event validation is enabled, endmarks are checked in:
- odp_buffer_free() / odp_buffer_free_multi()
- odp_buffer_is_valid()
- odp_event_free() / odp_event_free_multi() / odp_event_free_sp()
- odp_event_is_valid()
- odp_packet_free() / odp_packet_free_multi() /odp_packet_free_sp()
- odp_packet_is_valid()
=> [PATCH v5] linux-gen: event: add event validation support

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/pktio/loop.c
This patchset adds multi-queue support to loop packet I/O. This enables more realistic packet I/O application testing.
Additionally, relevant statistics are refactored and simple hashing is implemented to distribute packets to RX queues.
v2:
- Utilized `odp_hash_crc32()` for queue hashing
v3:
v4:
v5:
- Swapped to `odp_hash_crc32c()`
=> [PATCH v6] linux-gen: loop: add multi-queue support

config/odp-linux-generic.conf, platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_stash.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Use one common SHM block for all stash memory. This enables creating a large number of stashes without hitting the SHM block count limit, for the cost of having to pre-reserve the memory during global init.
The amount of required memory can be adjusted with new configuration file options:
- stash:max_num:     maximum number of stashes
- stash:max_num_obj: maximum number of objects in a stash
=> [PATCH v4] linux-gen: stash: reserve all memory from a single shm block

include/Makefile.am, include/odp/api/abi-default/buffer.h, include/odp/api/abi-default/buffer_types.h, include/odp/api/buffer_types.h, include/odp/api/spec/buffer.h, include/odp/api/spec/buffer_types.h, include/odp/arch/arm32-linux/odp/api/abi/buffer_types.h, include/odp/arch/arm64-linux/odp/api/abi/buffer_types.h, include/odp/arch/default-linux/odp/api/abi/buffer_types.h, include/odp/arch/power64-linux/odp/api/abi/buffer_types.h, include/odp/arch/x86_32-linux/odp/api/abi/buffer_types.h, include/odp/arch/x86_64-linux/odp/api/abi/buffer_types.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/buffer.h, platform/linux-generic/include-abi/odp/api/abi/buffer_types.h, platform/linux-generic/include/odp/api/plat/buffer_inlines.h, platform/linux-generic/include/odp/api/plat/event_validation_external.h
Split buffer API into separate header files for functions and types. This fixes circular dependency issues with inline headers.
=> [PATCH v2] api: buffer: split header files

test/Makefile.inc, test/common/Makefile.am, test/common/packet_common.c, test/common/packet_common.h, test/validation/api/crypto/Makefile.am, test/validation/api/crypto/odp_crypto_test_inp.c
test: common: add reusable functions for checking packet metadata
Add a common test library for setting and saving packet metadata
and for comparing saved metadata. The functions can be used by
different test modules that need to check that packet metadata
has not changed during some operation under test.
validation: crypto: check that packet metadata does not change
Add a check that packet metadata not related to crypto is not altered by
crypto operations.
=> [PATCH v5] validation: add common packet metadata functions and use them in crypto validation

include/odp/api/spec/crypto_types.h, platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c
Remove fully the deprecated per-session IVs from the API, validation tests and implementation.
=> [PATCH v7] api: crypto: remove deprecated per-session IVs

test/validation/api/time/time.c
Reset busy loop count to zero before reading the next set of
timestamps.
=> [PATCH v1] validation: time: reset count before reading ts

test/validation/api/dma/dma.c
In addition to checking that DMA implementation passes the user context pointer of completion parameters as is back to application (in poll and event completion cases), check also that the value pointed to by it remains unchanged.
v2:
- Added check to conditionally assert `user_ptr` value
v3:
- Further simplified `user_ptr` value check
=> [PATCH v3] validation: dma: validate user context pointer value

include/odp/api/spec/crypto_types.h
EIA2 uses 64-bit IV, not 128-bit as mentioned in the current API text. Fix the remark about IV length and fix also a couple of small typos.
=> [PATCH v3] api: crypto: fix EIA2 IV length in API text

platform/linux-generic/include/odp/api/plat/packet_inlines.h
Previously, a warning was thrown if bad-function-cast warning was enabled in application build with non-abi-compat ODP library.
=> [PATCH v2] linux-gen: packet: avoid bad-function-cast warning from inline header

test/performance/odp_timer_perf.c
Print min and max timeout length parameters when creating timer pools.
=> [PATCH v2] test: timer_perf: print min/max timeout params

helper/test/chksum.c, platform/linux-generic/pktio/ipc.c, test/validation/api/pktio/pktio.c
Fix a couple of cases where potentially uninitialized data in shm blocks are being used. These problems were revealed by filling all shm blocks with 0xaa.
v2:
- Initialize IP header fields before checksum.
v3:
- Rebase.
=> [PATCH v3] fix a couple of cases of uninitialized data

platform/linux-generic/odp_crypto_ipsecmb.c, test/performance/odp_crypto.c
Integrate SNOW3G-UEA2 and SNOW3G-UIA2 algorithms for IPsec MB library.
Add SNOW3G-UEA2 and SNOW3G-UIA2 algorithms in the crypto perf test tool.
=> [PATCH v5] linux-gen: crypto: support snow3g algorithm for IPsec MB

config/odp-linux-generic.conf, platform/linux-generic/include/odp_schedule_if.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_if.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_sp.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf, platform/linux-generic/test/stash-custom.conf
Optionally, when there are no events to schedule, sleep for a while to save power. Add power saving config file options poll_time and sleep_time.
v2:
- Change sleep_time to struct timespec.
- Clean up schedule_loop_sleep().
- Move comment about *_sleep functions.
v3:
- Change conf file option names.
- Remove change to schedule_multi_wait().
v4:
- _odp_schedule_basic_sleep_api comments.
v5:
- Update config file version.
=> [PATCH v6] linux-gen: sched: implement power saving sleep in schedule loop

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c
The output packet pointer of crypto_int() may point to an uninitialized packet handle with the basic crypto operation type. Do not access the uninitialized handle even for the purpose of passing it to a function that would ignore it. Such uninitialized access could result in undefined behaviour.
=> [PATCH v3] linux-gen: crypto: fix uninitialized variable access

example/ipsec_crypto/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_cache.c, example/ipsec_crypto/odp_ipsec_cache.h, platform/linux-generic/odp_ipsec_sad.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/test/example/ipsec_api/pktio_env, platform/linux-generic/test/example/ipsec_crypto/pktio_env
example: ipsec_crypto: switch to basic crypto operation type
linux-gen: test: fix skipping ipsec examples in process mode
linux-gen: loop: fix use of stale pkt_hdr after inline ipsec
linux-gen: ipsec: switch to basic crypto operation type
=> [PATCH v2] ipsec: small fixes and switch to basic crypto op type

example/timer/odp_timer_accuracy.c
Add a new mode (-m 3), which uses the periodic timer API.
v2:
- Rebase.
- Matias' comments.
- Remove unnecessary wait in cancel_periodic_timers().
v3:
- Rebase.
- Matias' comments.
- Change -P default to 5:0:0:1.
- Add periodic mode defaults to help text.
v4:
- Tweak help texts.
- Make periodic timer measurement more accurate.
v5:
- All comments.
- Add warmup option.
- Fix tmo_ns rounding (+.5) in run_test().
v6-v7:
- All comments.
v8:
- Rebase.
=> [PATCH v8] example: timer_accuracy: add periodic timer mode

test/validation/api/dma/dma.c
Add and modify tests to verify that maximum signaled in-flight transfer count is handled correctly.
With synchronous transfers, run more than maximum in-flight transfer count back to back to verify proper implementation resource handling.
With asynchronous transfers, start maximum in-flight count of transfers and wait for completion (poll/event).
v2:
- Added testing of maximum completion event allocation
- Added a new test for max DMA pools
- Took maximum segment length into account when configuring transfers
v3:
v4:
=> [PATCH v4] validation: dma: verify maximum concurrent transfers

platform/linux-generic/odp_timer.c
In odp_timer_periodic_start(), if first_tick is zero, set the first expiration time to one period after current time, instead of the current time.
=> [PATCH v1] linux-gen: timer: fix first expiration time for periodic timer

test/validation/api/timer/timer.c
Usage of first tick reduces period of the first timeout.
=> [PATCH v4] validation: timer: fix periodic timer duration calculation

test/validation/api/crypto/odp_crypto_test_inp.c
validation: crypto: fix ignoring of leftover bits of bit mode ciphers
validation: crypto: test both cipher/auth orders with single alg
validation: crypto: run all tests only when FULL_TEST env variable is set
validation: crypto: test combined ciphering and authentication
=> [PATCH v5] validation: crypto: test combined ciphering and authentication

.github/workflows/ci-pipeline-arm64.yml, scripts/ci/build_arm64.sh
The default DPDK release has been changed to v22.11. The arm64 test containers have been updated to use this release.
=> [PATCH v6] github_ci: update arm64 ci dpdk versions

platform/linux-generic/arch/aarch64/odp/api/abi/atomic_inlines.h, platform/linux-generic/arch/default/odp/api/abi/atomic_generic.h, platform/linux-generic/include/odp/api/plat/atomic_inlines.h, test/performance/odp_atomic_perf.c
ARM ISA v8.1 introduced specific instructions for atomic minimum and maximum value updates (e.g. STUMIN and STUMAX). Utilize these instructions when available. Optimization is similar to previous optimization of atomic add operations to utilize STADD instruction.
=> [PATCH v2] linux-gen: atomic: optimize min/max operations on ARM

platform/linux-generic/odp_schedule_basic.c
Fix potential integer overflows reported by Coverity.
=> [PATCH v2] linux-gen: sched: fix potential integer overflows

test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/ipsec/ipsec_test_out.c
Miscellaneous minor validation test tweaks to allow current and future odp-dpdk pass validation tests even when some algorithm combinations etc are not supported:
validation: crypto: do not combine aes-gmac with any cipher
validation: crypto: do not require support for digest in cipher range
validation: crypto: increase max packet size of packet pool
validation: crypto: reduce the number of unsupported combo warnings
validation: crypto: test all digest lengths in full test only
validation: ipsec: allow sa creation failure for unsupported algos
=> [PATCH v3] validation: crypto & ipsec

helper/include/odp/helper/odph_debug.h, platform/linux-generic/include/odp/api/plat/debug_inlines.h, platform/linux-generic/include/odp_debug_internal.h
Print format warnings were disabled as a side effect of enabling compilation with `-pedantic`. Re-enable them.
=> [PATCH v4] linux-gen, helper: re-enable print format warnings

config/odp-linux-generic.conf, include/odp/api/spec/stash.h, include/odp/api/spec/stash_types.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_stash.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf, platform/linux-generic/test/stash-custom.conf, test/validation/api/stash/stash.c
Add new stash create parameter odp_stash_param_t.strict_size. When this option is enabled, application must never attempt to store more handles into the stash than specified in the odp_stash_param_t.num_obj parameter. Depending on the implementation, this may enable performance optimization. The new option is disabled by default and the total object count limitation is removed from odp_stash_put() function.
=> [PATCH v6] api: stash: add new strict size create parameter

doc/application-api-guide/Doxyfile, doc/application-api-guide/api_guide_lines.dox, doc/application-api-guide/odp.dox, doc/platform-api-guide/Doxyfile, include/README
Add ODP API principles chapter and improve formatting of include/README file. The file is also referenced from application-api-guide and platform- api-guide for increased visibility.
=> [PATCH v5] README: improve api header README file

include/odp/api/spec/classification.h, include/odp/api/spec/packet_io.h, include/odp/api/spec/pool.h, include/odp/api/spec/queue.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/pktio/pktio.c
Clarify the order in which CoSes, PMRs, pools and queues should be destroyed. Allow default CoS to be removed. Allow CoS pool to be set to ODP_POOL_INVALID.
=> [PATCH v5] api: cls: clarify destroy order

include/odp/api/spec/timer_types.h
Clarify that zero first_tick means that the first expiration time is one period after the current time, not at the current time.
=> [PATCH v4] api: timer: clarify periodic first_tick documentation

.github/workflows/gh-pages.yml
Update GitHub action ghaction-github-pages to v3, which runs on Node.js 16. Previously used v2 ran on Node.js 12, which has been deprecated.
=> [PATCH v2] github_ci: update github pages deploy action

include/odp/api/spec/dma_types.h, include/odp/api/spec/pool_types.h, test/validation/api/dma/dma.c
Clarify that odp_pool_capability_t.max_pools is used for all pool types defined in odp_pool_type_t. Also, added reference to DMA pool capability (odp_dma_pool_capability_t.max_pools) to make this clearer.
=> [PATCH v4] api: pool: clarify odp_pool_capability_t.max_pools specification

include/odp/api/spec/crypto.h, test/validation/api/crypto/odp_crypto_test_inp.c
api: crypto: clarify that parse flags are not affected
validation: crypto: do not allow has_error packet flag to change
=> [PATCH v3] api: crypto: clarify that parse flags are not affected

CHANGELOG, configure.ac
- crypto: deprecate the old session creation error names (ODP_CRYPTO_SES_CREATE_ERR_NONE, ODP_CRYPTO_SES_CREATE_ERR_ENOMEM, ODP_CRYPTO_SES_CREATE_ERR_INV_CIPHER, ODP_CRYPTO_SES_CREATE_ERR_INV_AUTH)
- crypto: change return value of odp_crypto_result() to indicate crypto operation success/failure
- crypto: deprecate odp_crypto_packet_result_t.ok field
- crypto: specify that the status fields of odp_crypto_packet_result_t are valid only when the operation failed
- crypto: deprecate odp_crypto_hw_err_t type and odp_crypto_op_status_t.hw_err field
- crypto: deprecate ODP_CRYPTO_ALG_ERR_KEY_SIZE and ODP_CRYPTO_ALG_ERR_IV_INVALID error codes
- crypto: require that cipher range and auth range have zero offset …
=> [PATCH v2] api: increment ODP API version to 1.41.0

test/validation/api/pool/pool.c
odp_pool_stats_t.alloc_ops counter includes also failed alloc operations, so comparison should be made against the number of alloc rounds. Also, add same check for odp_pool_stats_t.cache_alloc_ops.
=> [PATCH v2] validation: pool: fix odp_pool_stats_t.alloc_ops test

DEPENDENCIES, platform/linux-generic/pktio/socket_xdp.c
This patchset refactors AF_XDP packet I/O queue handling. Queues are now properly mapped to the configured packet I/O level input and output queues as well as RSS being configured automatically by the driver, instead of needing manual configuration first (with the exception of Mellanox NICs).
v2:
v3:
=> [PATCH v3] linux-gen: socket_xdp: refactor queue handling

platform/linux-generic/include/odp_classification_internal.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/socket_xdp.c, platform/linux-generic/pktio/tap.c
Reduce latency by enqueueing packets directly to classifier and inline
IPsec destination queues from pktio devices.
=> [PATCH v3] linux-gen: pktio: enqueue packets to destination queues from pktio devices

platform/linux-generic/odp_dma.c, test/validation/api/dma/dma.c
Correctly allow up to maximum capability of input segments in case of packet-type transfer.
v2:
=> [PATCH v2] linux-gen: dma: fix packet-type transfer segmentation

platform/linux-generic/odp_packet_io.c
Previously, if a stop operation was still pending for a scheduled pktio device when odp_pktio_start() was called, the input queues were added again to scheduler's internal queues causing random behaviour.
=> [PATCH v4] linux-gen: pktio: detect pending stop operations

test/validation/api/ipsec/ipsec.c
validation: ipsec: disable anti-replay with null authentication
Set antireplay_ws to zero to disable anti-replay service when an inbound SA
without integrity protection is created.
The anti-replay service is not used in IPsec without integrity protection
and therefore some ODP implementations may not support SAs that have null
auth algorithm but anti-replay enabled. This change also enables a future
API change that would require zero antireplay_ws with null authentication.
=> [PATCH v9] validation: ipsec: disable anti-replay with null authentication

test/validation/api/crypto/odp_crypto_test_inp.c
validation: crypto: re-enable testing of non-legacy op types
validation: crypto: fix packet freeing after failed crypto ops
=> [PATCH v3] crypto: validation fixes

platform/linux-generic/test/validation/api/shmem/shmem_odp2.c, test/validation/api/atomic/atomic.c, test/validation/api/barrier/barrier.c, test/validation/api/buffer/buffer.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/comp/comp.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/init/init_main.c, test/validation/api/ipsec/ipsec.c, test/validation/api/lock/lock.c, test/validation/api/packet/packet.c, test/validation/api/pktio/parser.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c, test/validation/api/scheduler/scheduler.c, test/validation/api/scheduler/scheduler_no_predef_groups.c, test/validation/api/stash/stash.c, test/validation/api/thread/thread.c, test/validation/api/time/time.c, test/validation/api/timer/timer.c
Use ODPH_ERR() macro for all error prints in the validation tests and make error messages more consistent. The helper macro adds additional debug information (filename, line number, function name) to the error messages, which can help debugging.
=> [PATCH v2] validation: use ODPH_ERR() macro for error prints

platform/linux-generic/odp_queue_lf.c
GCC-13 warns that a variable may be used uninitialized. The warning is a false positive. Get rid of it by initializing the variable.
=> [PATCH v2] linux-gen: queue_lf: fix bogus 'maybe-uninitialized' warning

platform/linux-generic/odp_pool.c
When printing pools, correctly print DMA completion pool as its own type instead of as a buffer pool.
v2:
- Rebased
=> [PATCH v2] linux-gen: pool: correctly print DMA completion pool

platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/ipc.c
Remove pktio level single_capability() function which was only used by IPC pktio.
=> [PATCH v2] linux-gen: pktio: remove common capability function

test/validation/api/time/time.c
Test global time sync also with a control thread. Print the time differences.
=> [PATCH v3] validation: time: improve global time sync test

example/timer/odp_timer_accuracy.c, example/timer/odp_timer_test.c, include/odp/api/spec/timer.h, include/odp/api/spec/timer_types.h, platform/linux-generic/odp_timer.c, test/performance/odp_sched_pktio.c, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
Use same return values between timer start and cancel calls. Separate cancel failure return values allow application to distinguish timing related failures (TOO_NEAR) from severe errors (that should never happen).
v2: Rebased
v3: Rebased
v4: Rebased
=> [PATCH v5] api: timer: new timer cancel return values

include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
Added a new function that samples tick value of multiple timer pools simultaneously. This helps application to calculate tick offset between timer pools with minimum error.
v3: Fixed comments, rebased
v4: Fixed comment
v6: Rebased
=> [PATCH v7] api: timer: add tick sample function

include/odp/api/spec/pool.h, include/odp/api/spec/pool_types.h, platform/linux-generic/odp_pool.c, test/validation/api/pool/pool.c
Add new function `odp_pool_stats_selected()` for reading only selected pool
statistic(s). This can minimize function overhead compared to original
`odp_pool_stats()` function, which always returns all enabled counters.
Also, relax `odp_pool_stats()` specification to allow implementations to have some
delay until pool statistics are updated. This is required by some HW
statistics counters.
=> [PATCH v8] api: pool: add new function for reading only selected statistics

include/odp/api/spec/init.h, platform/linux-generic/odp_init.c, test/validation/api/Makefile.am, test/validation/api/init/.gitignore, test/validation/api/init/Makefile.am, test/validation/api/init/init_main.c
New `odp_term_abnormal()` function can be used to abnormally terminate an ODP application. Application can utilize the new function to terminate ODP with additional debug data in error situations where regular local and global clean-up is not possible.
v2:
- Jerin's comments
v3:
- Petri's comments
v4:
- Added patches for ODP abort function usage clarification, `odp_term_abnormal()` linux-gen implementation and validation
- Changed `odp_term_abnormal()` `data` parameter type to `void *`
- Added a `ODP_TERM_LAST_FLAG` constant
v6:
- Added an explicit `uint64_t` cast to `ODP_TERM_FROM_SIGH`
v7:
- Rebased
=> [PATCH v7] api: init: add abnormal termination function

include/odp/api/spec/dma.h, include/odp/api/spec/dma_types.h, platform/linux-generic/odp_dma.c, platform/linux-generic/odp_pool.c, test/validation/api/dma/dma.c
This patchset introduces user area for DMA event-completion pools.
v2:
- Dropped "minimum" in `odp_dma_pool_param_t` user area parameter spec
v3:
- Rebased
- Added a function to query completion event user area
v4:
- Added a patch that prints inactive tests at the end of DMA suite
v5:
v6:
- Rebased
=> [PATCH v6] api: dma: add completion event pool user area

include/odp/api/spec/event.h, platform/linux-generic/include/odp/api/plat/event_inlines.h, test/validation/api/buffer/buffer.c, test/validation/api/dma/dma.c, test/validation/api/ipsec/ipsec.c, test/validation/api/packet/packet.c, test/validation/api/pktio/pktio.c, test/validation/api/timer/timer.c
Add odp_event_user_area() function which returns a pointer to the user area associated with the event. If the event does not have user area, NULL is returned.
This PR needs to rebased on top of #1811 before merge.
=> [PATCH v5] api: event: add function for reading event user area address

include/Makefile.am, include/odp/api/abi-default/time_types.h, include/odp/api/spec/packet.h, include/odp/api/spec/packet_io.h, include/odp/api/spec/time.h, include/odp/api/spec/time_types.h, include/odp/api/time.h, include/odp/api/time_types.h, include/odp/arch/arm32-linux/odp/api/abi/time_types.h, include/odp/arch/arm64-linux/odp/api/abi/time_types.h, include/odp/arch/default-linux/odp/api/abi/time_types.h, include/odp/arch/power64-linux/odp/api/abi/time_types.h, include/odp/arch/x86_32-linux/odp/api/abi/time_types.h, include/odp/arch/x86_64-linux/odp/api/abi/time_types.h, platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/time.h, platform/linux-generic/include-abi/odp/api/abi/time_types.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp/api/plat/time_inlines.h, platform/linux-generic/include/odp_packet_io_internal.h
Split time API into separate header files for functions and types. This makes inlining API function implementations easier.
=> [PATCH v2] api: time: split header files

CHANGELOG, configure.ac
- dma: add odp_dma_compl_user_area() function for reading user area pointer
- dma: clarify that DMA session names don't need to be unique
- event: odp_event_user_area() function for reading user area pointer
- init: add odp_term_abnormal() function that can be used to abnormally terminate an ODP application after a non-recoverable error
- packet: extend packet transmit completion with poll mode
- packet: add odp_packet_free_ctrl_set() function for controlling packet output interface to not free a packet after transmitting it
- packet: add odp_packet_free_ctrl() function for reading packet's free control option value
- pool: relax odp_pool_stats() specification to allow implementations to have some delay …
=> [PATCH v3] api: increment ODP API version to 1.41.1

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
GCC 13 is now available for Ubuntu 22.04, so the separate Ubuntu 23.04 based job can be removed.
=> [PATCH v2] github_ci: change gcc-13 test container

test/performance/Makefile.am
Update CFLAGS with libconfig CFLAGS. The app has dependency on libconfig and CFLAGS should be updated.
Fixes: 249739742fcf ("test: ipsecfwd: utilize libconfig")
Cc: tuomas.taipale@nokia.com
=> [PATCH v2] test: ipsecfwd: update CFLAGS with libconfig

test/performance/odp_stress.c
Avoid invalid maybe-uninitialized error from GCC 13.1, when ODP is configured with debug mode enabled.
Reported-by: Carl Wallen <carl.wallen@nokia.com>
=> [PATCH v2] test: stress: fix maybe-uninitialized error from gcc-13

platform/linux-generic/include/odp_event_vector_internal.h, platform/linux-generic/odp_packet_io.c
Move `packet_vector_to_event_hdr()` to `odp_event_vector_internal.h` where it is reusable also elsewhere. Rename it accordingly.
v2:
- Rebased
=> [PATCH v2] linux-gen: pktio: move packet vector cast helper

LICENSE, README
Change current project owner to OpenFastPath Foundation and update license text to match the standard BSD-3-Clause format. The default copyright message has been shortened and reformatted:
```
/* SPDX-License-Identifier: BSD-3-Clause
* Copyright (c) <YEAR> <COPYRIGHT HOLDER>
*/
```
The rest of project files will be updated later to follow this new format.
=> [PATCH v2] LICENSE: update project owner

include/odp/api/spec/crypto.h, include/odp/api/spec/crypto_types.h, platform/linux-generic/odp_crypto_openssl.c, test/performance/odp_crypto.c, test/validation/api/crypto/crypto_op_test.c, test/validation/api/crypto/odp_crypto_test_inp.c
Allow non-zero-length cipher and auth ranges for the null cipher and auth algoriths in the OOP operation type. Copy the ranges to the output packet as with non-null algorithms. Allow implementations to not fully support non-zero-length ranges by explicitly mentioning that a crypto operation with such a range may fail if not supported.
This changes makes null algorithms behave as non-null algorithms with respect to packet data copying in the OOP operation type. When both the cipher and the auth algorithms are null, a crypto operation reduces to a´packet data copying operation (if supported by the underlying ODP implementation). Such copying may be useful for applications that wish to process crypto and non-crypto packets in the same way using the OOP crypto operation type.
=> [PATCH v10] api: crypto: copy the ranges of null algorithms in OOP op type & change bit mode semantics

include/odp/api/spec/dma_types.h, include/odp/api/spec/pool_types.h, platform/linux-generic/odp_dma.c, platform/linux-generic/odp_pool.c, test/validation/api/dma/dma.c, test/validation/api/pool/pool.c
This patchset adds possibility to initialize event user areas at pool creation time. Additionally, a user area persistence capability is added to signal if an implementation is able to maintain user area contents across event frees and allocations. 
v2:
- Petri's comments
v3:
- Petri's comments
v5:
- Rebased
- Ashwin's and Petri's comments
v6:
- Rebased
- Fixed checkpatch error
=> [PATCH v6] api: pool: add user area initialization parameters

include/odp/api/spec/dma_types.h
Move structure fields so that addr/packet field is directly followed by length and offset fields. After this change all commonly used fields locate in the first 16 bytes of the structure, which may improve performance.
v3: rebased
=> [PATCH v3] api: dma: pack DMA segment data structure

include/odp/api/spec/sync.h, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp/api/abi/sync_inlines.h, platform/linux-generic/arch/default/odp/api/abi/sync_inlines.h, platform/linux-generic/arch/x86/odp/api/abi/sync_inlines.h, platform/linux-generic/include/odp/api/plat/sync_inlines.h, test/validation/api/barrier/barrier.c
Added data synchronizing memory barriers that are stronger than the current barriers, and can be used also when accessing memory mapped device registers.
v4: rebased
=> [PATCH v5] api: sync: new memory barriers

CHANGELOG, configure.ac
- crypto: change 'bit_mode' cipher/auth capability flag to indicate whether bit mode is supported in addition to byte mode that is always supported
- crypto: add 'cipher_range_in_bits' and 'auth_range_in_bits' session parameters
- barrier: add memory barriers odp_mb_sync(), odp_mb_sync_load(), and odp_mb_sync_store()
- crypto: allow non-zero-length cipher and auth ranges for the null cipher and auth algorithms in the OOP operation type
- dma: add new 'uarea_persistence' pool capability
- dma: add new 'uarea_init' pool parameters 'init_fn' and 'args'
- dma: move odp_dma_seg_t structure fields
- event: add odp_event_types_multi() function
- event: add odp_event_user_area_and_flag() …
=> [PATCH v2] api: increment ODP API version to 1.42.0

platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_null.c, test/validation/api/crypto/odp_crypto_test_inp.c
linux-gen: crypto: null: fix session allocation when out of sessions
linux-gen: crypto: fail bit mode session creation when not supported
validation: crypto: test that session creation fails when it must
=> [PATCH v3] crypto: test that session creation fails when bit mode requested but not supported

test/validation/api/dma/dma.c
Max segment length should be calculated based on the DMA device
capabilities such as max supported segments and segment length.
Fixes: 1aaf5cf55a0c ("validation: dma: add tests for maximum segment amount transfers")
Reviewed-by: Tuomas Taipale <tuomas.taipale@nokia.com>
=> [PATCH v4] validation: dma: fix max segment length

.github/workflows/ci-pipeline.yml
Speed up CI by disabling coverage test (takes over 30 minutes). Also, the coverage report processing in Codecov has been broken for a while. The test can be added back once the report processing is fixed.
=> [PATCH v2] github_ci: disable coverage test

.github/actions/build-failure-log/action.yml, .github/actions/dump-log/action.yml, .github/actions/run-failure-log/action.yml, .github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
This patchset introduces local github actions that replace current inline per-job failure logging commands. Additionally, a new logging action to display logs of successful runs is added. This enables inspection of e.g. validation test prints after a successful CI run.
v2:
- Renamed actions
v3:
=> [PATCH v3] github_ci: add github actions for build and run logging

platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp/api/abi/cpu_inlines.h, platform/linux-generic/arch/aarch64/odp_cpu_cycles.c, platform/linux-generic/include/odp/api/plat/cpu_inlines.h, platform/linux-generic/odp_init.c, test/performance/odp_bench_misc.c
Implement odp_cpu_cycles() function using 'cntvct_el0' virtual counter
register on aarch64.
=> [PATCH v3] linux-gen: cpu: optimize aarch64 odp_cpu_cycles() implementation

test/performance/odp_sched_pktio.c
Remove unnecessary delay for the first tick as it might cause
ODP_TIMER_TOO_FAR error base on the timer pool created.
Reorder start_pktios with start_timers to prevent timeouts due
to delays in pktio start.
=> [PATCH v5] test: sched_pktio: remove unnecessary delay first tick

platform/linux-generic/include/odp_ring_mpmc_internal.h
Previously, _RING_MPMC_ENQ_MULTI() and _RING_MPMC_ENQ_BATCH() could return
zero even though the ring was not actually full. Read w_head before r_tail,
which guarantees that w_head - r_tail <= size. Any additional delay in
reading r_tail makes the subtraction result only smaller. This avoids
returning zero when the ring is not actually full.
=> [PATCH v3] linux-gen: ring: fix ring size detection

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_dmafwd.c
`odp_dmafwd` is a simple tester to compare packet forwarding throughput when received packets are first copied either with software memory copy or with DMA offload and then echoed back to sender.
v2:
v3:
- Refactored packet forwarding
v4:
- Rebased
- Added a separate copy pool also for SW copy mode
- Fixed a packet leak issue
v5:
- Rebased
=> [PATCH v5] test: performance: add DMA performance tester with packet I/O

platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/null.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c
With zero-copy packet I/O drivers (i.e. DPDK and XDP) packet dispatching happens asynchronously in `odp_pktout_send()` context, meaning that memory areas related to packets are marked to be sent in the underlying machinery during the function execution, but the actual sending might occur after the function has returned. Because of this, current TX completion might signal packet TX completion before actual transmission.
To workaround this, TX completion capability filling is moved to individual drivers and currently not supported by zero-copy DPDK and XDP drivers.
v2:
- Rebased
=> [PATCH v2] linux-gen: pktio: move tx completion capability to drivers

configure.ac
Add 'auto' argument to '-flto' to enable parallel LTO jobs, which may reduce linking duration. Also, fixes "using serial compilation of N LTRANS jobs" warnings when using GCC-12.
The '-flto=auto' and '-ffat-lto-objects' options are currently not supported by clang.
=> [PATCH v2] configure: enable parallel lto

platform/linux-generic/m4/configure.m4, platform/linux-generic/test/Makefile.am, platform/linux-generic/test/performance/Makefile.am, platform/linux-generic/test/performance/dmafwd/Makefile.am, platform/linux-generic/test/performance/dmafwd/pktio_env, test/performance/Makefile.am, test/performance/odp_dmafwd.c, test/performance/odp_dmafwd_run.sh
v3:
- Added platform abstraction to runner script
v4:
- Rebased
- Added a fallback to `stat` if `tcpdump` is not found when validating results
v5:
- Rebased
=> [PATCH v5] test: dmafwd: add CI integration

platform/linux-generic/odp_pool.c, test/validation/api/pool/pool.c
According to the specification, odp_pool_ext_capability() should set
'max_pools' to zero and return success if a valid but unsupported pool type
is used.
Add tests to validate that odp_pool_ext_capability() works according to the
specification when unsupported pool type is used.
=> [PATCH v4] linux-gen: pool: fix odp_pool_ext_capability() return value

platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/null.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c, test/validation/api/pktio/pktio.c
This patchset implements poll mode for packet TX completion. Poll mode is useful in cases where overhead from scheduling and event handling is not desired.
v3:
v4:
- Rebased
- Fixed required additional internal SHM block count
v5:
- Rebased
=> [PATCH v5] linux-gen: pktio: implement TX completion poll mode

test/validation/api/pool/pool.c
The max payload of single segmented packets in external pools depends on the odp_header_size, app_header_size, max_headroom_size and odp_trailer_size.
Take all these into consideration when doing packet alloc from external pools so that allocations don't fail.
=> [PATCH v3] validation: pool: fix uarea init test for external pools

test/validation/api/pktio/pktio.c
Test packet output don't free operation by sending the same packet five times through the interface. TX completion is not checked as reception of the packet verifies previous TX completion.
=> [PATCH v2] validation: pktio: add don't free test case

test/performance/odp_ipsecfwd.c
When tearing down resources, free interface string unconditionally as teardown logic could be reached before packet I/Os have been opened.
v2:
=> [PATCH v2] test: ipsecfwd: fix potential memory leak

test/performance/Makefile.am, test/performance/bench_common.c, test/performance/bench_common.h, test/performance/odp_bench_buffer.c, test/performance/odp_bench_misc.c, test/performance/odp_bench_packet.c, test/performance/odp_bench_timer.c
Move common code from odp_bench_* applications to bench_common.h/c.
=> [PATCH v2] test: performance: refactor bench applications

test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c
Test how many PMRs can be added to the default CoS. There is no max number of PMR capability.
=> [PATCH v2] validation: cls: add max pmr create test case

test/performance/odp_dmafwd.c, test/performance/odp_dmafwd_run.sh
This patchset implements DMA poll mode support to `odp_dmafwd`.
Additionally, a few improvements related to pool cache and element count configuration are introduced which may improve performance when DMA copy scenarios are used.
v2:
v3:
- Refactored stash capability checking
v4:
=> [PATCH v4] test: dmafwd: implement DMA poll mode

platform/linux-generic/odp_dma.c
In case of stash creation failure during DMA session creation, reset the session activity state to inactive to prevent a session leak.
v2:
=> [PATCH v2] linux-gen: dma: fix potential session leak

test/performance/odp_dmafwd.c
Move pool and stash cache calculations inside branches where related logic resides, preventing uninitialized value usage. The actual uninitialized usage is prevented later and does not cause any runtime issues. Nevertheless, this is now properly handled during startup.
v2:
=> [PATCH v2] test: dmafwd: reorder cache size calculations

test/validation/api/timer/timer.c
When starting again a canceled periodic timer, test also event reuse. Instead of freeing the last timeout event and allocating a new one, just reuse the event.
=> [PATCH v3] validation: timer: test timeout event reuse with periodic timer

test/performance/bench_common.c
Use correct type when zeroing timed benchmark suite data.
=> [PATCH v2] test: performance: fix wrong type in bench_tm_suite_init()

test/validation/api/timer/timer.c
Test that odp_timer_alloc() returns TIMER_INVALID when pool is empty, with both one-shot and periodic timer pools.
=> [PATCH v3] validation: timer: test that odp_timer_alloc() returns TIMER_INVALID when pool is empty

example/timer/odp_timer_accuracy.c
Schedule wait time is not in nanoseconds. Convert by calling odp_schedule_wait_time().
=> [PATCH v3] example: timer_accuracy: fix schedule wait time

test/validation/api/crypto/odp_crypto_test_inp.c
Use the basic crypto operation type instead of the legacy operation type when invoking crypto for the purpose of creating test data. The legacy operation type, which may get deprecated in the future, will now only be used when testing the legacy operation type itself.
=> [PATCH v3] validation: crypto: use basic op type when creating test data

test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/crypto/util.h
Run time consuming algorithm combination tests only once, in async-sched, async-plain or sync mode (in that preference order) instead of in all the three modes, unless FULL_TEST is requested. We assume that the actual crypto implementation being tested is the same in all the three modes so test coverage should not suffer much.
=> [PATCH v2] validation: crypto: reduce duplicate testing in different op modes

test/performance/bench_common.c, test/performance/bench_common.h, test/performance/odp_bench_pktio_sp.c
Add new test case 'cls_create_pmr', which creates a selected number ('-p') of PMRs.
bench_tm_func_record() saves now also the number of measurements, which makes the usage more flexible. Optional precondition check function 'cond' was added to bench_tm_info_t to enable skipping unsupported tests.
=> [PATCH v2] test: bench_pktio_sp: add new test for creating pmr rules

test/performance/odp_l2fwd.c
Print packet IO interface extra statistics (if available) in verbose mode.
=> [PATCH v2] test: l2fwd: print pktio extra statistics

example/ping/odp_ping.c, include/odp/api/abi-default/packet_io_types.h, include/odp/api/spec/packet_io.h, include/odp/api/spec/packet_io_types.h, platform/linux-generic/include-abi/odp/api/abi/packet_io_types.h, platform/linux-generic/odp_packet_io.c, test/performance/odp_dmafwd.c, test/performance/odp_l2fwd.c, test/performance/odp_packet_gen.c, test/performance/odp_sched_pktio.c, test/validation/api/pktio/pktio.c
Add new API define ODP_PKTIO_MAX_INDEX for maximum packet IO interface
index. The value of ODP_PKTIO_MAX_INDEX is always greater or equal to
odp_pktio_max_index(), so the new define can be used for example when
defining static length arrays.
V3:
- Fixed rebase failure
=> [PATCH v5] api: pktio: add ODP_PKTIO_MAX_INDEX define

include/odp/api/spec/timer_types.h
Remove the limitation on application. This change implies that application may attempt to allocate more timers than there are in a timer pool. In that case, odp_timer_alloc() returns ODP_TIMER_INVALID.
=> [PATCH v2] api: timer: clean up odp_timer_pool_param_t.num_timers description

include/odp/api/spec/queue.h, include/odp/api/spec/queue_types.h
Move default queue type specification from odp_queue_create() to odp_queue_param_t to make it conform with the other parameters.
Also, explicitly state that queue size default value is zero. This was already tested by the validation test.
=> [PATCH v2] api: queue: clarify odp_queue_param_t default value specification

include/odp/api/spec/crypto.h, include/odp/api/spec/crypto_types.h, platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/crypto_op_test.c, test/validation/api/crypto/crypto_op_test.h, test/validation/api/crypto/odp_crypto_test_inp.c
api: crypto: clarify packet ordering of async crypto ops
api: crypto: add null_crypto crypto op flag for skipping crypto
api: crypto: allow both basic and out-of-place ops in one session
=> [PATCH v6] API: Crypto API additions

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/system_info.h, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, test/validation/api/system/system.c
Added enumerations for ARM ISA versions ARMv8.8-A, ARMv8.9-A, and ARMv9.3-A.
V2:
- Added implementation and tests
=> [PATCH v3] api: sysinfo: add new ARMv8 and v9 enumerations

include/odp/api/spec/classification.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c
V2:
- Changed `odp_cls_cos_create_multi()` parameter `const odp_cls_cos_param_t *param[]` to `const odp_cls_cos_param_t param[]`
- Changed `odp_cls_pmr_create_multi()` parameter `const odp_pmr_create_opt_t *opt[]` to `const odp_pmr_create_opt_t opt[]`
V3:
- Added `odp_cos_destroy_multi()` and `odp_cls_pmr_destroy_multi()` APIs
V4:
- Added implementation and validation tests
=> [PATCH v6] api: cls: add pmr/cos create/destroy multi functions

include/odp/api/spec/queue.h, platform/linux-generic/include/odp/api/plat/queue_inline_types.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_if.c, platform/linux-generic/odp_queue_scalable.c, test/validation/api/queue/queue.c
Add new odp_queue_create_multi() function for creating multiple queues with a single call.
V2:
- Changed `odp_queue_create_multi()` parameter `const odp_queue_param_t *param[]` to `const odp_queue_param_t param[]`
- Added implementation and validation test
V3:
- Added `odp_queue_destroy_multi()` API
=> [PATCH v6] api: queue: add queue create/destroy function multi variants

CHANGELOG, configure.ac
- cls: add odp_cls_pmr_create_multi() function
- cls: add odp_cls_pmr_destroy_multi() function
- cls: add odp_cls_cos_create_multi() function
- cls: add odp_cos_destroy_multi() function
- crypto: clarify packet ordering of async crypto ops
- crypto: add null_crypto crypto op flag for skipping crypto
- crypto: allow both basic and out-of-place ops in one session
- pktio: add ODP_PKTIO_MAX_INDEX define
- queue: add odp_queue_create_multi() function
- queue: add odp_queue_destroy_multi() function
- queue: clarify odp_queue_param_t default value specification
- system: add new ARMv8 and v9 enumerations
- timer: clean up odp_timer_pool_param_t.num_timers description
- timer: add odp_timeout_alloc_multi() …
=> [PATCH v3] api: increment ODP API version to 1.42.1

example/ipfragreass/odp_ipfragreass.c, helper/test/debug.c, helper/test/macros.c, helper/test/parse.c, helper/test/version.c, test/miscellaneous/odp_api_headers.c
Use ODP_UNUSED for intentionally unused variables of functions. Thereby, harmonizing the main function signatures across multiple files.
=> [PATCH v3] helper: test: harmonize main function signatures

test/validation/api/dma/dma.c
When testing DMA transfers with potentially segmented packets, ensure that allocated packet length does not exceed allocated transfer destination memory size.
v3:
=> [PATCH v3] validation: dma: fix packet length when using segmented packets

include/odp/api/abi-default/dma_types.h, platform/linux-generic/odp_dma.c
Increase default `odp_dma_transfer_id_t` size to 64 bit from 32 bit. This enables different implementations to potentially utilize pointers as the transfer ID.
v2:
- Reverted 64 bit transfer ID usage in `linux-gen`
v3:
=> [PATCH v3] abi: dma: increase default transfer ID size

platform/linux-generic/odp_timer.c
Don't print timer pool "overrun" and "scans missed" debug prints, if no timers have been started.
=> [PATCH v4] linux-gen: timer: avoid overrun debug prints if no timers started

platform/linux-generic/include/odp_chksum_internal.h
Architectures that support unaligned access do not necessarily support it for all instructions that a compiler might choose to use. Therefore we should not mispresent the alignment of an object to the compiler even when unaligned access is typically supported.
The current checksum code casts a potentially unaligned pointer to uint32_t when _ODP_UNALIGNED is set. This typically works but may, in some cases, result in generation of invalid code. In particular, when targeting AArch32 (which supports unaligned access for regular loads and stores) gcc-12.2 generated LDM instructions which always reguire 4-byte alignment.
Fix the problem by informing the compiler about the non-standard alignment by using a type attribute.
=> [PATCH v3] linux-gen: fix unaligned access in checksum calculation

example/timer/odp_timer_accuracy.c
According to help, test runs on single CPU by default.
=> [PATCH v2] example: timer_accuracy: fix CPU count default value

include/odp/autoheader_external.h.in, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp/api/abi/wait_until.h, platform/linux-generic/arch/aarch64/odp_llsc.h, platform/linux-generic/arch/default/odp/api/abi/wait_until.h, platform/linux-generic/arch/default/odp/api/abi/wait_until_generic.h, platform/linux-generic/include/odp/api/plat/ticketlock_inlines.h, platform/linux-generic/m4/configure.m4, platform/linux-generic/m4/odp_wfe.m4
Fix casts to union type erros with CPP on aarch64. When "odp_cpu.h" is included in some head files, "odp_api_from_cpp.cpp" would include "odp_cpu.h" as well. Build failure and error of 'unknown conversion of types' show as going through this file with CPP.
Use WFE instruction on aarch64 to replace ISB instrution, making threads waiting for their turn into low-power state. Performance test with "odp_lock_perf" shows that it could reduce IPC while maintain similar performance.
**PLatform:arm-n1amp-01**
_Use 4 cores, test case ticketlock, run forever._ 
**1.ISB**
2.971 GHz
IPC: 0.06 insn per cycle.
total rounds: 3.5-4.5 M rounds/sec
**2 WFE**
2.305 GHz
IPC: 0.02  insn per cycle.
total rounds: 4-4.5 M rounds/sec
_Use 8 cores, test case ticketlock, run forever._ 
**1.ISB**
2.958 GHz
IPC: 0.07 …
=> [PATCH v8] linux-gen: ticketlock: enable WFE on aarch64

platform/linux-generic/include/odp/api/plat/timer_inlines.h, platform/linux-generic/odp_timer.c, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
Optimize timer current tick and other functions by using nsec time directly as the tick. API does not require tick to start from zero.
=> [PATCH v3] timer: tick does not need to start from zero

test/performance/odp_timer_perf.c
To avoid division by zero in result print, check the value used in division instead of number of rounds.
=> [PATCH v1] test: timer_perf: fix thread activity check

test/performance/odp_dma_perf.c, test/performance/odp_dma_perf_run.sh
This patchset introduces a new SW packet copy transfer mode. This is useful for comparing the performance of DMA subsystem and copying on CPU. Additionally, new sparse segment type variants are introduced: 'sparse packet' and 'sparse memory'. These configure scenarios which might be a more realistic usecase for some applications due to potentially incurred cache misses and allocation overheads. The old existing segment type options are renamed to 'dense packet' and 'dense memory'.
v2:
- Simplified memory copy transfer with transfer being done now only with a single function instead of separate for packets and addresses
v3:
v4:
- Fixed an issue when preparing transfers for poll mode
- Dropped ticketlock return value check
=> [PATCH v4] test: dma_perf: add memory copy and sparse segment type options

test/validation/api/timer/timer.c
Run most of the tests with all clock sources that are supported according to capability.
=> [PATCH v5] validation: timer: run tests with all supported clock sources

test/performance/odp_ipsecfwd.c
Replace IP lookup table provided by ODP helper library with a simpler structure.
v2:
- Fixed potential undefined behavior with bitshifting
v3:
- Removed sorting of forwarding entries
v4:
=> [PATCH v4] test: ipsecfwd: replace helper IP lookup table

include/odp/api/spec/hints.h
Convert the argument of odp_unlikely() to boolean before passing it to __builtin_expect() which takes a long int argument. This prevents implementation-defined behaviour when the argument of odp_unlikely() does not fit in a long int. In certain systems with 32-bit long, odp_unlikely() currently turns certain non-zero 64-bit values to zero, breaking the code that is using odp_unlikely().
=> [PATCH v3] api: hints: fix type conversion problem in odp_unlikely()

include/odp/api/spec/timer_types.h
Explicitly deprecate `odp_timer_set_t` with `ODP_DEPRECATE()` macro.
v2:
v3:
- Rebased
v5:
- Rebased
=> [PATCH v5] api: timer: explicitly deprecate odp_timer_set_t

include/odp/api/spec/schedule_types.h
Describe event ordering in ordered scheduling contexts more accurately. In particular, events in a destination queue are not necessarily in the same order as they are in the source queue if odp_schedule_multi() returns multiple events (sharing single scheduling synchronization context) and if the ODP application enqueues the events in a different order. Also, other enqueued events than the scheduled ones have a well defined ordering.
This API change is not intended to change any functionality but just tries to document more accurately what already is the expected behaviour.
=> [PATCH v4] api: sched: clarify event ordering in ordered contexts

example/debug/odp_debug.c, example/timer/odp_timer_accuracy.c, example/timer/odp_timer_simple.c, include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/performance/odp_sched_pktio.c, test/performance/odp_stress.c, test/performance/odp_timer_perf.c, test/validation/api/timer/timer.c
Remove possibility to free a timer that is running. When timer free call returns, the timer handle cannot be referenced any more. Expiration and event delivery of an already destroyed timer is an error prone corner case.
=> [PATCH v6] api: timer: only inactive timers can be freed

doc/users-guide/users-guide-timer.adoc, example/timer/odp_timer_test.c, include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/performance/odp_bench_timer.c, test/validation/api/timer/timer.c
The feature is not very useful to applications, since freshness result depends on timing of cancel/restart API calls vs the freshness check point.
=> [PATCH v3] api: timer: deprecate timeout fresh

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/classification.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c
Add new `max_pmr` and `max_pmr_per_cos` packet matching rule capabilities to `odp_cls_capability_t` to signal maximum amount of PMRs and maximum amount of PMRs per class of service, respectively, that an implementation is able to support.
v2:
- Spec text reworded
v3:
- Spec text reworded
- Renamed `max_pmr_terms` field
- Removed `available_pmr_terms` field
v4:
v5:
=> [PATCH v5] api: cls: add new packet matching rule capabilities

include/odp/api/spec/packet.h
Clarify that the option does not affect direct packet free calls.
=> [PATCH v4] api: packet: clarify don't free option

configure.ac, example/packet/odp_pktio.c, platform/linux-generic/odp_schedule_sp.c, platform/linux-generic/pktio/stats/ethtool_stats.c
Quell a few -Warray-bounds and -Wstringop-overflow warnings with GCC 13.1, with and without -Wpedantic.
The question here is do we keep adding these pragmas to the code or do we just disable -Warray-bounds and -Wstringop-overflow?
=> [PATCH v5] quell GCC 13.1 bound check warnings

test/performance/odp_dma_perf.c, test/performance/odp_dma_perf_run.sh
Add new option to verify correctness of successfully transferred data. This can be useful in the unlikely occurences of data corruption caused by a DMA subsystem.
v2:
- Fixed a commit message typo
v3:
- Rebased
=> [PATCH v3] test: dma_perf: add new verify option

CHANGELOG, configure.ac
- cls: add new odp_cls_capability_t.max_pmr and odp_cls_capability_t.max_pmr_per_cos capabilities
- cls: rename odp_cls_capability_t.max_pmr_terms field to odp_cls_capability_t.max_terms_per_pmr
- time: change local/global time specification to allow timestamp values to start from an implementation defined value
- timer: deprecate odp_timer_set_t type
- timer: deprecate odp_timer_pool_start() function
- timer: deprecate odp_timeout_fresh() function
- timer: change odp_timer_free() specification to remove the possibility to free a timer that is running
- timer: change odp_timer_pool_create() specification to state that timer pool handles must not be used by other APIs before being started
Backward …
=> [PATCH v3] api: increment ODP API version to 1.43.0

platform/linux-generic/odp_packet_io.c
odp_lso_profile_create() ensures that size is one of the allowed values. But the compiler doesn't know that, and it may generate out of bounds warnings in some cases. For example, in odp-dpdk, where odp_packet_copy_to_mem() calls rte_memcpy(), this results in:
/usr/lib/gcc/x86_64-redhat-linux/13/include/emmintrin.h:742:8: warning: array subscript ‘__m128i_u[0]’ is partly outside array bounds of ‘void[8]’ [-Warray-bounds=]
Set the value of size to 1 if it's not one of the allowed values.
=> [PATCH v2] linux-gen: pktio: avoid possibility of out of bounds warnings in lso_update_custom()

example/packet/odp_pktio.c, example/packet/pktio_run.sh, example/timer/odp_timer_simple.c, example/traffic_mgmt/odp_traffic_mgmt.c, platform/linux-generic/test/pktio_ipc/ipc_common.c, platform/linux-generic/test/pktio_ipc/ipc_common.h, platform/linux-generic/test/pktio_ipc/pktio_ipc1.c, platform/linux-generic/test/pktio_ipc/pktio_ipc2.c, platform/linux-generic/test/pktio_ipc/pktio_ipc_run.sh, test/performance/odp_atomic_perf.c, test/performance/odp_bench_buffer.c, test/performance/odp_bench_packet.c, test/performance/odp_scheduling.c, test/performance/odp_scheduling_run.sh, test/performance/odp_stress.c, test/validation/api/pktio/lso.c, test/validation/api/pktio/pktio.c, test/validation/api/scheduler/scheduler.c, test/validation/api/system/system.c
Make 'make check' run slightly faster by speeding up various tests and other programs run during 'make check'.
Performance tests and examples are run in 'make check' just to see that they do not crash otherwise directly fail, so there is no use in running them for more than just a brief time.
=> [PATCH v6] Speed up testing slightly

.github/workflows/ci-pipeline.yml, .github/workflows/coverity.yml, .github/workflows/gh-pages.yml
Update used x86 GitHub Actions into their latest release versions. Project documentation build runner is updated to Ubuntu 22.04 for newer Doxygen version.
V2:
- Removed arm64 action updates
=> [PATCH v3] github_ci: update all used github actions

platform/linux-generic/include/odp_packet_internal.h
Move odp_packet_hdr_t.cos field to a gap on the previous 64-byte cache line. This cache line is always written during packet reception, so writing CoS here (when classifier is enabled) can reduce classification overhead.
=> [PATCH v3] linux-gen: packet: move packet header cos field

test/validation/api/scheduler/scheduler.c
There is no guarantee that the main thread (ODP_THREAD_CONTROL) won't end up running on the same core with a worker thread. To avoid test slowdowns run multithreaded scheduler tests only on worker threads.
=> [PATCH v2] validation: sched: run tests only on worker threads

test/performance/odp_cpu_bench.c, test/performance/odp_dma_perf.c, test/performance/odp_dma_perf_run.sh, test/performance/odp_dmafwd.c, test/performance/odp_dmafwd_run.sh, test/performance/odp_sched_latency_run.sh, test/validation/api/timer/timer.c
Speed up 'make check' by making certain tests (mainly timer validation and dma perf tests) complete faster.
=> [PATCH v3] speed up testing

test/performance/odp_sched_perf.c
Added options to read (-u) and modify (-U) user area content per event reception.
=> [PATCH v2] test: sched_perf: add user area touch

platform/linux-generic/arch/x86/odp_time_cpu.c, platform/linux-generic/odp_system_info.c
Speed up TSC frequency measurement and thus ODP startup by reducing the
measurement duration. Make the result more accurate despite the decreased
duration by using a busyloop instead of nanosleep and by taking the median
of several measurements.
Using a busyloop instead of nanosleep also fixes the measurement in (old)
systems that have constant but not invariant TSC which may stop or change
frequency in C-states.
=> [PATCH v3] linux-gen: time: improve TSC frequency measurement

config/odp-linux-generic.conf, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/include/odp_timer_internal.h, platform/linux-generic/odp_cpumask.c, platform/linux-generic/odp_cpumask_task.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_system_info.c, platform/linux-generic/odp_timer.c
When using inline timers and power saving sleep, limit sleep duration according to the next timeout.
=> [PATCH v7] linux-gen: sched: improve timer behavior when power saving sleep is enabled

.github/workflows/ci-pipeline.yml, scripts/ci-checkpatches.sh
Previously, in case of push operations only the latest commit was tested to avoid issues with invalid commit ranges in force pushes. Read force push status from GitHub events and test full commit range with normal push operations.
=> [PATCH v2] github_ci: improve checkpatch testing for push operations

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_pool_latency.c
`odp_pool_latency` is a simple pool latency tester for profiling pool allocation and free latencies under different load patterns. Test scenario consists of a configurable pattern (allocations/frees/delays) that is run continuously. All the currently specified pool types are available for testing.
v2:
- Improved capability checks and statistics
- Renamed `write_data` long option to `write_uarea`
v3:
v4:
- Changed `odp_pool_latency` to be run as part of `make check`
v5:
- Added user area size to summary
- Rebased
=> [PATCH v5] test: performance: add pool latency tester

test/validation/api/crypto/crypto_op_test.c
Previously, odp_crypto_packet_to_event() function was not tested by the validation suite.
=> [PATCH v1] validation: crypto: add test for odp_crypto_packet_to_event()

configure.ac, example/ipsec_crypto/odp_ipsec.c, example/timer/odp_timer_accuracy.c, example/timer/odp_timer_test.c, example/traffic_mgmt/odp_traffic_mgmt.c, helper/include/odp/helper/macros.h, platform/linux-generic/arch/default/odp/api/abi/atomic_generic.h, platform/linux-generic/include/odp_macros_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_schedule_scalable_ordered.c, test/performance/odp_crypto.c, test/performance/odp_dma_perf.c, test/performance/odp_ipsec.c, test/validation/api/random/random.c, test/validation/api/scheduler/scheduler.c, test/validation/api/timer/timer.c
Enables compiler warnings (-Wshadow=local) when a local variable
shadows another local variable or parameter.
For example:
for (int i = 0; i < N; ++i) {
...
for (int i = 0; i < M; ++i) {
...
}
}
=> [PATCH v2] build: add -wshadow compiler check

test/performance/odp_dmafwd.c, test/performance/odp_pool_latency.c
In `odp_pool_latency` and `odp_dmafwd`, actually pass instance initialization parameters to `odp_init_global()`. Previously, they were defined but erroneously not utilized.
v2:
=> [PATCH v2] test: performance: fix initialization parameter usage

example/packet/Makefile.am, example/timer/Makefile.am, helper/test/Makefile.am, platform/linux-generic/test/example/ipsec_api/Makefile.am, platform/linux-generic/test/example/ipsec_crypto/Makefile.am, scripts/ci/distcheck.sh, test/performance/Makefile.am
Enabling parallel build in all directories outweighs the benefits from being able to run distcheck in parallel. Running 'make check' with -j option is not expected to work anymore after this commit.
=> [PATCH v2] build: re-enable parallel build

CHANGELOG, configure.ac
- ml: add new API module for machine learning offload
=> [PATCH v2] api: increment ODP API version to 1.44.0

test/miscellaneous/.gitignore, test/miscellaneous/Makefile.am, test/miscellaneous/odp_dyn_workers.c
`odp_dyn_workers` is a simple dynamic worker tester and can be used to verify ability of an implementation to dynamically add and remove workers from one ODP application to another. Acts as a frontend and forks ODP applications based on configuration.
v2:
- Rebased
- Removed accidental sleeping in workers
- Added logging for cases where maximum number of workers has been created or all workers have been removed
v3:
- Rebased
- Fixed a few typos
- Fixed a few potential issues in worker addition logic
=> [PATCH v3] test: miscellaneous: add dynamic worker tester

test/miscellaneous/Makefile.am, test/miscellaneous/odp_dyn_workers.c, test/miscellaneous/odp_dyn_workers_run.sh
Add new option to execute tester in non-interactive mode. A pattern of additions, removals and delays can be passed to the tester which then executes the commands sequentially. New test script utilizing the new mode is added to be run as part of `make check`.
Additionally, existing logic is refactored slightly to dump summaries of workers that are still active when interactive session is terminated from command line.
v2:
- Rebased
v3:
- Run script copyright format updated
- Fixed typo in help
- Added additional logging to summary check
=> [PATCH v4] test: dyn_workers: add CI integration

test/validation/api/pktio/lso.c, test/validation/api/pktio/pktio.c
Depending on OS and pktio device type extra packets may be received from interfaces (e.g. IPv6 ICMP). Ignore these packets also in pktio_test_pktin_event_queue() to avoid failures.
=> [PATCH v4] validation: pktio: ignore extra packets in pktio_test_pktin_event_queue

doc/users-guide/users-guide-packet.adoc
Use correct function names for packet pull/push head operations.
=> [PATCH v3] doc: userguide: fix packet function names

test/performance/odp_l2fwd.c
Move odp_pktio_print() call to a later phase when all pktio configurations have been completed. This may enable implementations to print more information.
=> [PATCH v3] test: l2fwd: move pktio print call

.github/workflows/ci-pipeline.yml, example/classifier/odp_classifier.c, example/ipsec_api/odp_ipsec.c, example/ipsec_crypto/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_stream.c, example/ipsec_crypto/odp_ipsec_stream.h, example/simple_pipeline/odp_simple_pipeline.c, helper/Makefile.am, helper/hashtable.c, helper/test/table.c, platform/linux-generic/Makefile.am, platform/linux-generic/example/ml/mnist.c, platform/linux-generic/example/ml/model_explorer.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/pcap.c, test/performance/odp_l2fwd_run.sh, test/performance/odp_pktio_ordered_run.sh, test/validation/api/traffic_mngr/traffic_mngr.c
Enable address sanitizer and fix bugs found by it.
=> [PATCH v8] fix issues reported by GCC address sanitizer

test/miscellaneous/Makefile.am, test/miscellaneous/odp_dyn_workers.c, test/miscellaneous/odp_dyn_workers_run.sh
User commands in both interactive and non-interactive modes now take an additional index parameter which is used to launch or remove workers to/from a specific index. The index is relative to the given CPU masks, e.g. index 0 would launch a worker on CPU 0x1 with CPU mask 0x111 and index 2 would launch a worker to CPU 0x100 with the same mask.
Additionally, add a new print after worker additions which lists all active workers on the particular ODP process.
On top of #2038 
v3:
- Rebased
=> [PATCH v4] test: dyn_workers: improve command granularity

platform/linux-generic/odp_timer.c
Replace all usage of sched_yield() with odp_cpu_pause(). The man page states that "sched_yield() is intended for use with real-time scheduling policies [...] Use of sched_yield() with nondeterministic scheduling policies such as SCHED_OTHER is unspecified and very likely means your application design is broken."
=> [PATCH v2] linux-gen: timer: don't use sched_yield()

example/cli/odp_cli.c, example/l2fwd_simple/odp_l2fwd_simple.c, helper/include/odp/helper/threads.h, helper/test/cli.c, helper/test/odpthreads.c, helper/threads.c, test/common/odp_cunit_common.c, test/performance/odp_l2fwd.c, test/performance/odp_random.c, test/validation/api/time/time.c
Add new join function which is similar to the existing `odph_thread_join()` but optionally outputs results of joined threads and interrupts only if the actual join operation fails for some thread.
v3:
- Rebased
- Switched to utilize new `odph_thread_join_res()` in cases where result of the join operation was checked
v4:
- Initialized result structure in cases where LTO wrongly thinks it might be uninitialized
v5:
v6:
- Bumped copyright years
=> [PATCH v6] helper: threads: add new join function

helper/include/odp/helper/threads.h
Clarify in odph_thread_create() specification that the output thread table elements must not be modified during the life time of the threads if odph_thread_join() is used to wait for thread exit.
=> [PATCH v2] helper: threads: clarify odph_thread_create() documentation

include/odp/api/spec/packet.h
Use correct name when referring to `odp_packet_tx_compl_request()`.
=> [PATCH v4] api: packet: fix typo

CHANGELOG, configure.ac
- crypto: increase size of odp_crypto_cipher_algos_t.all_bits and odp_crypto_auth_algos_t.all_bits
- packet: change odp_packet_reset() specification to use odp_packet_reset_max_len() for maximum packet data length value
- proto_stats: limit length of odp_proto_stats_create() object name parameter to a new ODP_PROTO_STATS_NAME_LEN define
- tm: limit lengths of TM object names to a new ODP_TM_NAME_LEN define
- common: make mentions of maximum string lengths clear and consistent and always state that the null character is included
- cpu: add more specific data prefetch variants: odp_prefetch_l1(), odp_prefetch_l2(), and odp_prefetch_l3()
- cpu: add more specific data prefetch variants …
=> [PATCH v2] api: increment ODP API version to 1.45.0

platform/linux-generic/odp_traffic_mngr.c
Use API call instead of _odp_cpu_pause(), which is used to implement the API call.
=> [PATCH v2] linux-gen: tm: use CPU pause API call

test/miscellaneous/odp_dyn_workers.c
Allow setenv() to overwrite existing environment variable values. For example, some implementations may use environment variables (e.g. ODP_PLATFORM_PARAMS for odp-dpdk) during 'make check' to configure resources per application, so a variable may already be set when odp_dyn_workers is run.
=> [PATCH v2] test: dyn_workers: allow overwriting environment variables

platform/linux-generic/include/protocols/thash.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c
Implement `odp_cls_hash_result()` function utilizing the existing hashing machinery used in packet classification.
v2:
v3:
=> [PATCH v3] linux-gen: cls: implement odp_cls_hash_result()

test/validation/api/packet/packet.c
Improve odp_packet_reset() test coverage by extending packet data into available tailroom. Also, try to configure some headroom to test packets.
=> [PATCH v3] validation: packet: improve odp_packet_reset() test coverage

test/validation/api/buffer/buffer.c, test/validation/api/crypto/crypto_op_test.c, test/validation/api/event/event.c, test/validation/api/ipsec/ipsec.c, test/validation/api/packet/packet.c, test/validation/api/timer/timer.c
Build failure has been observed, as some flags, sub event
types were uninitialized.
error: ‘subtype’ may be used uninitialized \
[-Werror=maybe-uninitialized]
Signed-off-by: Harman Kalra <hkalra@marvell.com>
=>  [PATCH v3] test: build failure due to uninitialized variable

test/validation/api/classification/odp_classification_basic.c
Allocating a large array of odp_cls_cos_param_t on stack causes
overflows. Fixing it by dynamically allocating this array.
Signed-off-by: Kiran Kumar K <kirankumark@marvell.com>
Signed-off-by: Satheesh Paul <psatheesh@marvell.com>
=> validation: cls: fix local allocation of large array

test/performance/odp_packet_gen.c
Add new -U option to define custom L3 headers. Option string consists of wanted EtherType followed by a set of field definitions containing the field name, length, value and a diff value that's added (subtracted in case of a negative value) to the value element in successive packets.
If given, the custom L3 header overrides the default IP header and any related options. Additionally, L4 checksums requiring a L3 IP header won't be calculated.
v2:
- Rebased
v3:
- Rebased
v4:
- Addressed comments
v5:
- Fixed field name buffer size
=> [PATCH v5] test: packet_gen: add possibility to define custom L3 headers

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_icache_perf.c
Added new performance test application to measure CPU performance when application code size exceeds L1 instruction cache size. The -n option is used to select how many copies of each function type are called. I.e. application code footprint scales up and down with -n option values.
=> [PATCH v6] test: performance: add new odp_icache_perf application

test/performance/odp_packet_gen.c, test/validation/api/init/Makefile.am, test/validation/api/ipsec/Makefile.am
commit 71a76ef6c0e26903d41680188ada869a2d931066 (HEAD -> dev-fixes-145, origin/dev-fixes-145)
Date:   Tue May 21 17:47:43 2024 +0530
test: packet_gen: fix pktio draining path
Avoid calling odp_schedule() when there are no Rx queues.
Also don't break Tx thread on enqueue failure as it
can happen due to backpressure.
commit cb497d0e323a42b28e04755d04a1d1cf6aab1f13
Date:   Wed May 15 16:18:25 2024 +0530
test: validation: install new test scripts
Make changes to install new test scripts that were added
as part of IPsec and init validation suite.
=> [PATCH v6] Fixes to packet gen and validation suite make file

test/validation/api/scheduler/scheduler.c
Increase latency tolerance in scheduler_test_wait_time() test when odp_schedule() is called multiple times. Also, use odp_time_local_strict() for more reliable timestamping.
=> [PATCH v2] validation: sched: increase latency tolerance in scheduler_test_wait_time()

test/common/bench_common.c
The benchmark index 'j' is already incremented in the for loop, so remove the extra increment which caused every other index to be skipped.
V2:
- Renamed `j` to `i`
=> [PATCH v2] test: bench_common: fix running selected test indefinitely

.github/workflows/ci-pipeline.yml, DEPENDENCIES
CentOS 7 has reached EOL, so remove it from the CI tests.
=> [PATCH v2] github_ci: remove CentOS 7 build test

platform/linux-generic/odp_ipsec.c
Do not try to send a packet to a pktout using an uninitialized queue handle when the queue lookup has failed in inline output.
=> [PATCH v2] linux-gen: ipsec: fix error path when pktout queue not found

config/odp-linux-generic.conf, platform/linux-generic/include/odp/api/plat/thread_inline_types.h, platform/linux-generic/include/odp/api/plat/thread_inlines.h, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_system_info.c, platform/linux-generic/odp_thread.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf, platform/linux-generic/test/stash-custom.conf
Add new config file option 'system:cpu_id_static' for selecting whether the implementation reads CPU identifier value from OS during every odp_cpu_id() call or only once  during thread initialization (default). If thread(s) may be migrated between cores during the application lifetime this option should be set to 0.
=> [PATCH v3] linux-gen: cpu: make possible to read cpu id during every odp_cpu_id() call

test/performance/odp_l2fwd.c
Instead of checking for `odp_unlikely(pkts) == 0`, check for `odp_unlikely(pkts == 0)` in run functions after extra feature processing.
v2:
=> [PATCH v2] test: l2fwd: fix odp_unlikely() conditions

README, configure.ac
Enable the -fno-strict-aliasing compiler option. Some sections of code in ODP deliberately access the same data via pointers to different types, which is undefined behavior in C. The -fno-strict-aliasing option prevents the compiler from making assumptions about aliasing in these instances.
=> [PATCH v3] configure: enable -fno-strict-aliasing option

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, test/m4/performance.m4, test/performance/Makefile.am
Build odp_icache_perf only when enabled using --enable-icache-perf-test configuration flag. This speeds up builds since the icache performance test takes a long time to compile.
=> [PATCH v1] build: do not build odp_icache_perf by default

helper/test/Makefile.am
Prefixed all helper tests with "odph_" to prevent naming conflicts with
existing Linux utilities.
Eg. Renaming "stress" helper test with "odph_stress" to avoid conflict with
linux "stress" utility.
Signed-off-by: Harman Kalra <hkalra@marvell.com>
=> [PATCH v4] helper: prefix odph to all helper tests

include/odp/api/spec/packet.h
Clarify `odp_packet_reset_max_len()` documentation to state that the returned length may be less than the current packet data length if data length has been increased by utilizing head- or tailroom.
=> [PATCH v2] api: packet: clarify odp_packet_reset_max_len() documentation

include/odp/api/spec/atomic.h, platform/linux-generic/arch/aarch64/odp/api/abi/atomic_inlines.h, platform/linux-generic/arch/default/odp/api/abi/atomic_generic.h, platform/linux-generic/include/odp/api/plat/atomic_inlines.h, test/performance/odp_atomic_perf.c, test/validation/api/atomic/atomic.c
V4:
- Moved `odp_atomic_add_u32/64()` calls out of validation tests loops
=> [PATCH v10] api: atomic: add functions for fetching and updating maximum/minimum values

include/odp/api/spec/atomic.h, platform/linux-generic/include/odp/api/plat/atomic_inlines.h, test/performance/odp_atomic_perf.c, test/validation/api/atomic/atomic.c
Add functions to atomically set and clear bits in 32-bit and 64-bit variables.
v2:
- Comments addressed
v3:
- Comments addressed
v4:
v6:
- Comments addressed
v8:
- Rebased
=> [PATCH v9] api: atomic: add atomic bit set and clear functions

include/odp/api/spec/ml_quantize.h, platform/linux-generic/odp_ml_quantize.c, test/validation/api/ml/ml.c
Added APIs to support quantization of int16_t and uint16_t data types. Added implementation for linux-generic platform and API validation test cases.
odp_ml_fp32_to_uint16
odp_ml_fp32_from_uint16
odp_ml_fp32_to_int16
odp_ml_fp32_from_int16
=> [PATCH v7] api: ml: add 16-bit integer type conversion APIs

CHANGELOG, configure.ac
- atomic: add odp_atomic_fetch_min_u32() and odp_atomic_fetch_min_u64() functions
- atomic: add odp_atomic_fetch_max_u32() and odp_atomic_fetch_max_u64() functions
- atomic: add functions for atomically setting and clearing bits in 32-bit and 64-bit atomic variables
- atomic: add flags for the new atomic functions into odp_atomic_op_t
- cpu: add instruction prefetch function odp_prefetch_l1i()
- dma: add debug function odp_dma_transfer_id_to_u64()
- init: add debug function odp_instance_to_u64()
- ml: add functions for supporting quantization of int16_t and uint16_t data types
- packet: add debug function odp_packet_tx_compl_to_u64()
- packet: clarify odp_packet_reset_max_len() documentation
- scheduler: …
=> [PATCH v3] api: increment ODP API version to 1.45.1

test/common/Makefile.am
Instead of depending on presence of `libcunit`, always build `libtest_common`. Otherwise, this will lead to build issues if `libcunit` is not present.
v2:
=> [PATCH v2] test: common: always build libtest_common

platform/linux-generic/include/odp_pool_internal.h
Pack and reorganize implementation internal pool_t struct for increased performance. Fast path data has been collected to the beginning of the struct.
=> [PATCH v2] linux-gen: pool: pack internal pool_t struct

helper/include/odp/helper/ip.h
Variable length arrays are not allowed in C++, so do not use one in a header file that may be included by a C++ application. Clang++-18 complains about it, breaking the build.
=> [PATCH v2] helper: ip: avoid using a VLA in a header because of C++ apps

.github/workflows/ci-pipeline-arm64.yml
Test running arm64 CI using Graviton3 runners.
=> [PATCH v2] github_ci: move arm64 pipeline to graviton3 runners

test/performance/odp_l2fwd_run.sh
Currently, even if runner script fails to parse the maximum pps value from `odp_l2fwd` test log (e.g. the searched pattern is not found or value is not numerical), runner script reports success.
Improve this by checking that the parsed value is actually found and is an integer. This should help if the searched pattern somehow changes without additionally updating the runner script.
v2:
- Rebased
=> [PATCH v2] test: l2fwd: improve runner script failure detection

platform/linux-generic/odp_packet_io.c
_odp_lso_create_packets() crashes currently with a segmentation fault if odp_packet_alloc_multi() returns zero or a negative value. Fix this by selecting error path always after alloc failure.
=> [PATCH v2] linux-gen: pktio: fix lso packet alloc error handling

test/performance/odp_atomic_perf.c, test/performance/odp_lock_perf.c, test/performance/odp_pool_perf.c, test/performance/odp_sched_latency.c, test/performance/odp_sched_perf.c, test/performance/odp_stash_perf.c, test/performance/odp_timer_accuracy.c
call test_common_write_term() also when exiting and writing is successful.
=> [PATCH v5] test: export: terminate writing properly

test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_common.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/classification/odp_classification_testsuites.h
The test code goes through the trouble of checking classification capabilities when deciding whether to use UDP or TCP port matching rules in tests but then always uses UDP test packets anyway. Tests are thus broken is only TCP port matching is supported despite all the capability checking.
Fix the problem by selecting also the protocol used in test packets based on capabilities.
=> [PATCH v3] validation: cls: use correct L4 proto for the PMR used

test/performance/odp_queue_perf.c
Add new option ('-p') for using private queues per worker. In private queue mode each worker thread operates on separate queues which can improve performance scaling.
V2:
- Added new queue pair test mode
=> [PATCH v4] test: queue_perf: add new test modes

test/validation/api/pktio/pktio.c
Replace the magic number 1000 used for test packet counts and rx attempt counts with two macros. Lower the test packet count to 100 since the used pool configuration did not allow allocating more than 128 packets anyway. Make the rx attempt count twice the test packet count to leave room for a few possible non-test packets and to allow almost 100 ms for the first sent test packet to come back.
The previous code had a higher rx attempt count than the test packet count but that was apparently accidental due to the pool config limiting the test packet count. The 1000 used for the rx attempt count was higher than necessary and slowed down the test slightly.
=> [PATCH v4] validation: pktio: separate and reduce packet and rx counts

test/validation/api/pktio/lso.c
Currently the validation test of the custom segment number add operation passes even if the ODP implementation overwrites the field instead of adding to it. Fix the problem by using a non-zero value in the field in the original packet. Also select the value so that with the third segment the addition carries to the most significant byte of the two byte field used in the test.
=> [PATCH v2] validation: pktio: lso: improve test coverage of custom segnum add

.github/workflows/ci-pipeline.yml, .github/workflows/coverity.yml
Update GitHub hosted runners from Ubuntu 20.04 to 22.04.
=> [PATCH v2] github_ci: update github hosted runners

config/odp-linux-generic.conf, platform/linux-generic/include/odp/api/plat/thread_inline_types.h, platform/linux-generic/include/odp/api/plat/thread_inlines.h, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_system_info.c, platform/linux-generic/odp_thread.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf, platform/linux-generic/test/stash-custom.conf
Overhead from reading CPU ID in each odp_cpu_id() call is minimal (<10 cycles in local testing). Remove the system:cpu_id_static configuration option to simplify the code and avoid problems if ODP threads are migrated between CPU cores.
V2:
- Removed now unnecessary inline wrapper for `odp_cpu_id()`
V3:
- Added missing include
=> [PATCH v4] linux-gen: cpu: remove static cpu id config file option

platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_system_info.c
Check odp_cpu_id() call return values to prevent accidentally using negative return values as array indices. Fixes Coverity warnings.
=> [PATCH v2] linux-gen: check odp_cpu_id() call return values

platform/linux-generic/odp_timer.c
Currently, when handling timer expiration, error while enqueueing timeout event leads to an abort. Before the abort, the timeout event is attempted to be freed. With POSIX timer implementation, where timer expiration is handled in a separate helper thread that has not been locally ODP-initialized, this leads to a NULL pointer access as thread-local pool cache is uninitialized in the helper thread. As the thread (and related worker/process) is about to be aborted anyways, remove the event freeing attempt to fix this.
v2:
=> [PATCH v2] linux-gen: timer: fix expiration enqueueing error handling

doc/users-guide/users-guide-comp.adoc, doc/users-guide/users-guide-pktio.adoc, doc/users-guide/users-guide-timer.adoc, doc/users-guide/users-guide-tm.adoc, doc/users-guide/users-guide.adoc
Remove code sections copied from the API headers as they will not stay up- to-date. Update some code examples to utilize current APIs and remove some obsolete ones.
=> [PATCH v3] doc: userguide: update code blocks

test/validation/api/pktio/lso.c
Ignore non-test packets already at packet reception time to simplify the segment checking phase.
=> [PATCH v3] validation: pktio: lso: filter non-test packets away earlier

test/performance/odp_queue_perf.c
In pair mode events may end up unevenly into the queues. Fix queue clean-up by simply dequeuing events from queues until ODP_EVENT_INVALID is returned.
=> [PATCH v2] test: queue_perf: fix queue destroy step in pair mode

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/packet_io_types.h, platform/linux-generic/odp_packet_io.c, test/validation/api/pktio/lso.c
- add ODP_LSO_WRITE_BITS operation
- add ODP_LSO_ADD_SHIFTED_PAYLOAD_OFFSET operation
=> [PATCH v10] api: add custom LSO operation for setting flag bits

include/odp/api/spec/packet_io_types.h, test/validation/api/pktio/lso.c
Change the DF flag handling in TCP segmentation offload and improve the description in general:
- Specify that the DF flag of the IP header is to be preserved as it was in the original packet and not cleared as the current spec says.
- Specify that TCP segmentation should be done in a way that complies with the TCP standard, without going into details. This entails proper handling of various TCP header flags and TCP options.
- Specify that unique ID values are generated for non-atomic datagrams and leave it unspecified how the ID value is updated for atomic datagrams (packets which are not fragments and have the DF flag set). Suggest that an application should avoid sending packets with ID values that may lead to overlapping IDs after segmentation.
Improve the description of IPv4 …
=> [PATCH v7] api: pktio: lso: improve the specification of IPv4 and TCP LSO

include/odp/api/spec/event.h
Document in odp_event_free() specification that it frees also the packets stored inside packet vectors. Previously this was only documented in odp_packet_vector_free().
=> [PATCH v3] api: event: clarify odp_event_free() documentation for packet vectors

include/odp/api/spec/packet_io_types.h, include/odp/api/spec/packet_types.h, test/validation/api/pktio/lso.c
Specify that LSO for the custom protocol produces same-sized segments (except the last segment).
Add a profile parameter to request exactly maximum length payload sizes in the non-last segments produced by the custom protocol LSO.
v2:
Remove configurability and the capability flag and just promise that the custom LSO protocol always produces maximum length segments.
v3:
Added validation test commit.
=> [PATCH v7] api: pktio: lso: promise maximum payload size for custom proto

platform/linux-generic/odp_dma.c
Initialize variable to avoid false positive maybe-uninitialized warning from GCC 14.
=> [PATCH v2] linux-gen: dma: fix bogus 'maybe-uninitialized' warning

include/odp/api/spec/packet_io_types.h, include/odp/api/spec/packet_types.h, include/odp/api/spec/timer.h, include/odp/api/spec/timer_types.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_timer.c, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/ipc.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/null.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/socket.c, platform/linux-generic/pktio/socket_mmap.c, platform/linux-generic/pktio/tap.c, test/validation/api/pktio/pktio.c, test/validation/api/timer/timer.c
- Explicitly deprecate APIs which have been deprecated only in documentation
- Remove APIs which have been explicitly deprecated over a year
=> [PATCH v3] api: deprecated API clean-up

test/performance/odp_timer_accuracy.c
Initialize variable to avoid false positive maybe-uninitialized warning from GCC 14.
=> [PATCH v2] test: timer_accuracy: fix bogus 'maybe-uninitialized' warning

CHANGELOG, configure.ac
- crypto: change the default crypto op type to ODP_CRYPTO_OP_TYPE_BASIC
- crypto: deprecate crypto op type ODP_CRYPTO_OP_TYPE_LEGACY
- pktio: modify certain details of IP and TCP LSO, specify missing details, add restrictions, and clarify the API in general
- pktio: clarify classifier back pressure API
- pktio: deprecate ODP_PACKET_TX_COMPL_ALL define
- pktio: deprecate odp_pktio_capability_t.tx_compl.mode_all field
- pktio: deprecate odp_pktout_config_opt_t.bit.tx_compl_ena field
- timer: deprecate odp_timer_pool_start() function
- event: clarify odp_event_free() documentation
- init: add printf format check to odp_override_log() and odp_log_func_t declarations
- init: add …
=> [PATCH v3] api: increment ODP API version to 1.46.0

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_timer_stress.c
`odp_timer_stress` is a tool for benchmarking timer related handling performance in different scenarios. Tester currently supports modes for single-shot (with and without cancelling) and periodic timers.
Both single-shot and periodic timers are configured based on the passed 'resolution' parameter so that both should end up having the same expiration interval.
v2:
- Rebased
v5:
v6:
- Rebased
=> [PATCH v6] test: performance: add timer stress test

platform/linux-generic/odp_timer.c
Do not log an error about an unsupported clock source in odp_timer_capability() since one intended use of the function is to probe which clock sources are supported. Print a debug message instead. This gets rid of an annoying error printout in odp_sysinfo output.
=> [PATCH v3] linux-gen: timer: do not log an error in capability query

test/validation/api/scheduler/scheduler.c
Add missing function return value checks and remove dead code.
=> [PATCH v2] validation: sched: fix coverity warnings

config/odp-linux-generic.conf, platform/linux-generic/test/sched-basic.conf
Disable basic scheduler implementation's ordered queue reorder stash by default. Reorder stash usage can cause event drops inside the implementation if the destination queue is full, which is against the ODP spec and can cause difficult to debug application problems.
When enabling reorder stash, application should make sure queues are large enough, so event drops will never occur.
=> [PATCH v2] linux-gen: sched: disable ordered queue reorder stash by default

test/performance/odp_ml_perf.c
Skip test instead of failing it when ML offload is not available. CUnit uses special value 77 to mark test as SKIPPED.
=> [PATCH v3] test: ml_perf: skip test when ml offload is not available

test/validation/api/timer/timer.c
Improve odp_timer_capability() testing by running the test twice. First with the output capability struct initialized with zeros and again with 0xff. Also, remove unnecessary memset() calls from other odp_timer_capability() usages throughout the validation tests.
=> [PATCH v2] validation: timer: improve odp_timer_capability() testing

platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_if.c
Use a simpler ord_enq_multi function in the basic scheduler when event stashing at enqueue is disabled, which is now the default config setting.
=> [PATCH v2] linux-gen: sched: optimize slightly the case when stash is disabled

include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
api: tm: add node stats capability and query API
Add capability to advertise capability of nodes at a given level
to provide statistics.
Also add a new API to query for packet sent count in green, yellow
and red color and packet drop count stats, along with corresponding
octet count statistics. TM node stats query will return only platform
supported statistics.
linux-gen: tm: add node stats API stub
Add node stats API stub.
=> [PATCH v11] api: tm: add node stats capability and query API 

helper/include/odp/helper/macros.h, helper/test/macros.c, test/performance/odp_pktio_perf.c, test/performance/odp_sched_latency.c, test/performance/odp_sched_perf.c, test/performance/odp_timer_stress.c
Add two new utility macros:
- `ODPH_ROUNDUP_DIV()` for dividing two numbers rounded up to the
closest integer
- `ODPH_ROUNDUP_ALIGN()` for rounding up a value to a given alignment
v2:
v4:
- Rebased
- Macro test improvement
v5:
v6:
- Rebased
=> [PATCH v7] helper: macros: add new utility macros

include/odp/api/spec/system_info.h
V2:
- Dropped validation test change commit
=> [PATCH v4] api: system: allow odp_system_meminfo_t.total_overhead to be zero

include/odp/api/spec/schedule.h, include/odp/api/spec/schedule_types.h, platform/linux-generic/odp_schedule_if.c, test/validation/api/queue/queue.c, test/validation/api/scheduler/scheduler.c
Enable possibility to configure cache stashing at schedule group, priority and/or queue levels. Stashing data of to-be-scheduled events and queues may improve performance in some workloads.
For the moment, the cache stashing configuration is instantiated as hints. Implementation can utilize the information according to its capabilities.
v2:
- Petri's comments
v3:
- Refactored configuration toggle: moved region specific L2/L3 configuration toggle to a bitmap at `odp_cache_stash_config_t` level, this should make filling and parsing of the configuration more convenient
v4:
- Petri's comments
v5:
- Rebased
- Petri's comments
- Added barebone `linux-gen` implementation and validation tests
v6:
- Increased configuration bitfield width to 32 bits
v7: …
=> [PATCH v10] api: sched: add cache stashing

include/odp/api/spec/timer_types.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
Add new timer pool parameter odp_timer_pool_param_t.priority and related capabilities.
V2:
- Note that lower priority timers may get delayed due to higher priority timer processing
V3:
- Fixed Petri's comments
- Added validation tests
- Added parameter check in the implementation
V4:
- Added reviewed/acked-by tags
=> [PATCH v5] api: timer: add timer pool priority

include/README
Add a paragraph in the API principles section in include/README to describe parameter lifetimes of ODP API functions: Structures passed by reference (and structures referred by them) do not need to outlive the API call, unless otherwise noted in the API.
=> [PATCH v4] api: describe parameter lifetimes in API principles

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/classification.h, include/odp/api/spec/queue.h, include/odp/api/spec/queue_types.h, platform/linux-generic/include/odp/api/plat/queue_inlines.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c, test/validation/api/queue/queue.c
This is based on PR 2187 even though the code is not included here.
This PR adds a new queue enqueuing function that can be used for passing start-of-vector and end-of-vector hints to an event aggregator (if the queue is, in fact, an event aggregator). This PR also adds a new classifier CoS parameter to select aggregator profile, which in turn causes the CoS to generate aggregation hints if it enqueues a packet to an event aggregator.
=> [PATCH v7] api: add event aggregator enqueue profile to CLS and a new queue enqueuing function

include/odp/api/spec/dma_types.h, platform/linux-generic/include/odp/api/plat/dma_inlines.h, platform/linux-generic/odp_dma.c, test/validation/api/dma/dma.c
Review for `linux-gen` implementation and validation tests.
API patches contributed by @VamsiKrishnaA99 in #2179.
v2:
v3:
- Added additional input validation for synchronous transfer destination segment allocation
v4:
=> [PATCH v6] api: dma: support source free and destination allocation features

platform/linux-generic/odp_ishm.c
After the latest change lots of error messages are generated when ODP cannot create a directory in the huge page file system even though a fallback to normal pages works. This happens e.g. when running ODP as a normal user in a system with huge page fs mounted but not writable by normal users.
Get rid of the distracting error messages by changing them to debug prints.
=> [PATCH v1] linux-gen: shm: do not print an error when huge pages cannot be used

test/performance/odp_queue_perf.c
Add new option '-b 0' for testing odp_queue_enq() and odp_queue_deq() functions. By default multi variants odp_queue_enq_multi() and odp_queue_deq_multi() are used.
V2:
- Fixed review comments
- Use `odp_cpu_cycles_strict()` for reading CPU cycles
=> [PATCH v3] test: queue_perf: add support for testing single event enq/deq operations

test/performance/odp_sched_perf.c
V2:
- All review comments addressed
=> [PATCH v3] test: sched_perf: add new event forwarding mode

platform/linux-generic/odp_ml.c
Some model input/output data types defined in
ML API are missing in function data_type_str().
=> [PATCH v3] linux-gen: ml: add string for missing data types

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/classification.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_test_pmr.c
Add configurable priority to PMRs so that when multiple PMRs match a packet a PMR with the highest priority is selected. If multiple PMRs of the same priority match a packet, leave it implementation specific which PMR gets selected. Add a capability for the maximum priority value.
=> [PATCH v7] api: cls: add PMR priority to break PMR matching ties

include/odp/api/spec/event_vector.h, platform/linux-generic/include/odp/api/plat/event_vector_inline_types.h, platform/linux-generic/include/odp/api/plat/event_vector_inlines.h, platform/linux-generic/include/odp_event_vector_internal.h, platform/linux-generic/odp_event_vector.c, platform/linux-generic/odp_pool.c, test/validation/api/event/event_vector.c
Change odp_event_vector_type() to not return the type of events actually stored in the event vector but the event type stored in event vector metadata and add odp_event_vector_type_set() to set the event type. Specify that event aggregators set the event type according to the event types they put in the event vector and require that applications use odp_event_vector_type_set() to update the event type of a vector after vector table modifications.
This way odp_event_vector_type() can be used largely as before, but an ODP implementation is not forced to loop through the vector every time odp_event_vector_type() is called.
=> [PATCH v7] api: event: add event type metadata to event vectors

include/odp/api/spec/dma_types.h, test/validation/api/dma/dma.c
Enable possibility to configure cache stashing for destination segments. Stashing the data of newly transferred segments may improve performance in some workloads.
The stashing configuration is instantiated as hints. Implementation can utilize the information according to its capabilities.
v2:
- Added a new simple validation test patch
v3:
- Rebased
v4:
- Rebased
v5:
- Rebased
v6:
- Rebased
v7:
- Rebased
=> [PATCH v8] api: dma: add cache stashing

include/odp/api/spec/crypto.h, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/include/odp_crypto_internal.h, platform/linux-generic/odp_crypto.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c, test/validation/api/crypto/util.c
Add odp_crypto_session_print() function for printing implementation defined information about a crypto session to the ODP log.
V2:
- Added implementation and validation test change
=> [PATCH v4] api: crypto: add session debug print function

CHANGELOG, configure.ac
api: increment ODP API version to 1.48.0
- dma: move odp_dma_seg_t struct's segment hints
- event_vector: change odp_event_vector_type() function specification
- event_vector: change odp_event_vector_tbl() function specification
- cls: add configurable priority odp_pmr_create_opt_t.priority to PMRs
- cls: add odp_cls_capability_t.max_pmr_priority capability
- cpu: add missing documentation for odp_cpumask_t type
- crypto: add odp_crypto_session_print() function
- dma: add cache stashing hints (odp_dma_seg_t.hints)
- event_vector: add odp_event_vector_type_set() function
- event_vector: clarify odp_event_vector_type() function specification
- ml: add odp_ml_num_engines() function
- …
=> [PATCH v4] api: increment ODP API version to 1.48.0

test/common/odp_cunit_common.c, test/performance/odp_crypto.c, test/performance/odp_ipsec.c, test/validation/api/packet/packet.c
GCC 15.1 emits a couple of new warnings that fail the build due to -Werror. Fix the issues to make compilation work with GCC-15 too.
=> [PATCH v2] test: small changes for compiling with GCC-15

platform/linux-generic/arch/x86/odp_random.h
Fix compilation with Clang on x86 when the target architecture supports RDRAND. ODP implementation uses low level GCC specific compiler builtin functions that are not available with Clang. Clang does support the higher level intrinsics like _rdrand64_step() but this commit does not switch to use them but simply falls back to the generic code when Clang is being used.
=> [PATCH v2] linux-gen: random: do not use GCC specific intrinsics with Clang

test/performance/odp_timer_accuracy.c
Pending timeouts left in scheduler kept queues non-empty in non-periodic modes, causing queue_destroy() failure.
Fix by canceling remaining timers and draining pending timeout events before destroying queues.
=> [PATCH v2] test: timer_accuracy: cancel timers and drain timeouts before teardown

example/ipsec_crypto/odp_ipsec.c, example/ipsec_crypto/odp_ipsec_cache.c, example/ipsec_crypto/odp_ipsec_cache.h, test/validation/api/crypto/odp_crypto_test_inp.c
Fix crypto validation test and ipsec_crypto example to adhere to the API spec which says that the output_pool crypto session parameter must be set to ODP_POOL_INVALID in the basic and OOP operation types.
=> [PATCH v3] crypto: fix output_pool session parameter

platform/linux-generic/pktio/dpdk.c
DPDK EAL has to be initialized before calling
rte_eth_dev_get_port_by_name(). This fixes calling odp_pktio_open() with a DPDK device name.
Closes: https://github.com/OpenDataPlane/odp/issues/2276
=> [PATCH v2] linux-gen: dpdk: fix eal initialization order
