platform/linux-generic/drv_driver.c
Before registering a new devio, we loop through all currently registered
devios to make sure none with the same name has already been
registered. The loop is protected with a read lock, later this lock is
released and a new write lock is taken to insert the new element in the
list. Between the release of the read lock and the acquisition of the
write lock, a new devio with the same name could be successfully
registered. To prevent this we only take the write lock once to enclose
both operations.
Signed-off-by: Josep Puigdemont <josep.puigdemont@linaro.org>
=> [PATCH CLOUD-DEV v1] drv: driver: fix devio registration race condition

.travis.yml
after update tap pktio hangs. Back to stable image untill
we solve failure.
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
=> [PATCH v1] travis: back to stable image until issue is resolved

doc/Doxyfile_common
Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>
=> [PATCH v1] doxygen: remove drv types

.travis.yml, DEPENDENCIES, doc/application-api-guide/odp.dox, doc/helper-guide/odp.dox, platform/linux-generic/Makefile.am
=> [PATCH v3] doc: update GitHub repository links

platform/linux-generic/include/odp_atomic_internal.h, platform/linux-generic/include/odp_bitmap_internal.h, platform/linux-generic/include/odp_bitset.h, platform/linux-generic/include/odp_buffer_internal.h, platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/include/odp_classification_inlines.h, platform/linux-generic/include/odp_classification_internal.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/include/odp_schedule_if.h, platform/linux-generic/include/odp_timer_internal.h
Fix checkpatch code style warnings.
=> [PATCH v3] linux-gen: fix internal header code style warnings

test/validation/api/timer/timer.c
Previously, the test could fail if 'num_workers * NTIMERS' was larger than
the maximum number of timers. Also, added a check for timeout pool
capability.
V2: Added reviewed-by tag
=> [PATCH v2] validation: timer: calculate number of timers per thread using capability

platform/linux-generic/odp_ishm.c
fallocate() reserves required memory at call time, so out of memory
failures are easier to detect.
=> [PATCH v2] linux-gen: shm: replace ftruncate() with fallocate()

.shippable.yml, .travis.yml, scripts/ci/coverage.sh
=> [PATCH v2] ci: remove deleted configure option test-perf-proc

.travis.yml, DEPENDENCIES
=> [PATCH v2] linux-gen: netmap: bump tested version to v13.0

platform/linux-generic/odp_packet.c, test/validation/api/pktio/pktio.c
Improvements done during debugging issue with Linux IPv6 stack sending packets to veth interfaces during validation tests.
=> [PATCH v2] Improve debug information on packet and packet IO

Makefile.am, configure.ac, m4/odp_libconfig.m4, platform/Makefile.inc
Support platforms that do not use config file.
Change-Id: I9f82337bcd547e0757cc1b5b0c9cdbcf99758b63
Signed-off-by: Dmitry Eremin-Solenikov <deremin-solenikov@cavium.com>
=> [PATCH v7] build: support platforms that do not use config

platform/linux-generic/odp_crypto_openssl.c
OpenSSL 1.1.1b (and master branches) have changed semantics of
EVP_En/Decrypt operations by diallowing now to call EVP_Decrypt on the
context initialized with EVP_EncryptInit_ex (which was allowed before).
Fix this by calling corresponding function for data processing.
Signed-off-by: Dmitry Eremin-Solenikov <deremin-solenikov@cavium.com>
=> [PATCH v3] linux-gen: crypto: fix AES-GMAC with OpenSSL 1.1.1b

example/time/Makefile.am, example/time/time_global_test.c
Bug correction and increased pool size enable running the test from one to many threads. Run example as part of make check.
=> [PATCH v2] Example time fix

.travis.yml, configure.ac, example/ipfragreass/odp_ipfragreass_helpers.c, helper/chksum.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/pktio/socket.c, test/performance/odp_bench_packet.c, test/validation/api/classification/odp_classification_common.c, test/validation/api/ipsec/ipsec.c, test/validation/api/packet/packet.c, test/validation/api/pktio/pktio.c, test/validation/api/pool/pool.c, test/validation/api/traffic_mngr/traffic_mngr.c
Fixed warnings found by LTO build. Added --enable-lto option to ./configure and added test cases for Travis.
=> [PATCH v4] Enable link time optimization

platform/linux-generic/include/odp_schedule_if.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_sp.c
Prepare spread queue selection improvement with code clean ups.
=> [PATCH v1] Scheduler code readability clean ups

test/performance/odp_pool_perf.c
Added -n and -t options. -N controls how many bursts are allocated before freeing events back into the pool. -T enables testing with packet pools.
=> [PATCH v2] Pool perf options

CHANGELOG, configure.ac
=> [PATCH v2] changelog: updates for odp v1.22.0.0

.gitignore
=> [PATCH v1] gitignore: fix stamp-h1 path

config/odp-linux-generic.conf, example/timer/odp_timer_accuracy.c, platform/linux-generic/include/odp_timer_internal.h, platform/linux-generic/odp_timer.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/process-mode.conf
Clean up code. Fix accuracy issue with high resolution (<100us) timer pools. Add configuration option to select default poll interval in nsec.
=> [PATCH v4] Simplify inline timer

example/classifier/odp_classifier.c, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_test_pmr.c
Fix issues in CUSTOM_L3 and parallel PMRs matching. Added test cases for serial and parallel PMRs.
=> [PATCH v4] Fix classifier matching of parallel PMRs 

test/validation/api/scheduler/scheduler.c
Add new validation tests to verify that packet order is maintained when
events are enqueued and dequeued to/from a plain queue while maintaining
atomic/ordered scheduling context.
=> [PATCH v3] validation: scheduler: add scheduled and plain queue tests

platform/linux-generic/Makefile.am, platform/linux-generic/include-abi/odp/api/abi/buffer.h, platform/linux-generic/include/odp/api/plat/buffer_inline_types.h, platform/linux-generic/include/odp/api/plat/buffer_inlines.h, platform/linux-generic/include/odp/api/plat/event_inlines.h, platform/linux-generic/odp_buffer.c, platform/linux-generic/odp_buffer_api.c, platform/linux-generic/odp_event.c
Inline small buffer/event functions which may be called frequently by applications.
=> [PATCH v2] Inline buffer and event functions

CHANGELOG
=> [PATCH v2] changelog: updates for odp v1.23.0.0

platform/linux-generic/include/odp_config_internal.h, platform/linux-generic/odp_pool.c, test/validation/api/buffer/buffer.c, test/validation/api/packet/packet.c
Add validation tests for max packet and buffer pools. Re-writted buffer pool test for better API coverage.
=> [PATCH v2] Validation test for max pools

example/timer/odp_timer_accuracy.c
Added new options to enable testing timer reset and log test results into a file.
=> [PATCH v2] Timer accuracy test development

example/switch/odp_switch.c
Pure IPv4 hashing is not supported by all DPDK pktio drivers.
=> [PATCH v3] example: switch: disable IPv4 hashing

test/performance/odp_sched_perf.c
Added options to read / read+write data in event payload and queue context on every received event. This can be used to test how performance changes when application touches the data.
=> [PATCH v2] Added data touch options to sched perf

test/validation/api/scheduler/scheduler.c
Whenever order locks are used, user should ensure that he follows the
same sequence of ordered locks when processing events that have to be
ordered. That includes a drain loop when scheduler is paused.
Signed-off-by: Stanislaw Kardach <skardach@marvell.com>
=> [PATCH v3] test/validation/scheduler: fix plain+sched test

platform/linux-generic/odp_timer.c
Set highest_tp_idx only after timer pool has been fully initialized.
=> [PATCH v2] linux-gen: timer: fix timer pool create sync with inline timer scan

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_packet_gen.c, test/performance/odp_packet_gen_run.sh, test/performance/odp_timer_perf.c
Simple UDP/IP packet generator application which can test also loop interfaces.
=> [PATCH v4] New packet gen performance test application

example/l3fwd/odp_l3fwd.c, example/switch/odp_switch.c, test/performance/odp_l2fwd.c, test/performance/odp_pktio_ordered.c
=> [PATCH v2] example: don't enable input hashing with only one input queue

test/performance/odp_sched_perf.c
Changed scheduling performance test logic to always schedule the same
number of events to each worker. Previously, if some worker didn't receive
any events the printed total average results were invalid.
=> [PATCH v2] test: sched_perf: improve test reliability

test/performance/odp_sched_latency.c
Add new command line option (-f) to the scheduling latency test to select
event forwarding mode. The options are:
0: Target queue mapping table is randomized at startup (static seed)
1: Increment queue id by one
2: Back to the source queue
=> [PATCH v2] test: sched_latency: add option to select event forwarding mode

test/performance/odp_packet_gen.c
Added -v option to insert VLAN(s) into the packets. VLAN header
TPID and TCI fields (<tpid>:<tci>) are defined in hexadecimal.
Multiple VLANs may be stacked with a comma separated list,
starting from the outter most VLAN.
=> [PATCH v3] test: packet_gen: add VLAN option

platform/linux-generic/pktio/socket_mmap.c
Newer kernels (e.g. Ubuntu 19.10 - 5.3.0) may set packet timestamp bits
on causing the pktio to think the TX slot is not available. Fix this by
checking only the relevant TX ring header bits.
Reported-by: Jari Mustajärvi <jari.mustajarvi@nokia-bell-labs.com>
=> [PATCH v2] linux-gen: socket_mmap: check only relevant TX ring header status bits

test/performance/odp_l2fwd.c
Added -p option to enable performance testing with packet copy.
This stresses packet alloc and free operations, as well as CPU's
interconnection toward caches and memory.
=> [PATCH v2] test: l2fwd: add packet copy option

config/odp-linux-generic.conf, configure.ac, include/odp/api/spec/classification.h, include/odp/api/spec/cpu.h, include/odp/api/spec/crypto.h, include/odp/api/spec/pool.h, include/odp/api/spec/queue.h, include/odp/api/spec/queue_types.h, include/odp/api/spec/schedule.h, include/odp/api/spec/shared_memory.h, include/odp/api/spec/timer.h, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/include/odp_pool_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_pool.c, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c, test/validation/api/shmem/shmem.c, test/validation/api/system/system.c, test/validation/api/timer/timer.c
This patch set combines multiple fixes and clarifications on API specification text. Also couple of new features are added such as pool parameter to control thread local caching and ODP_SHM_HW_ACCESS flag for SHM reserve calls.
=> [PATCH v4] API updates and new features for v1.23.5

.checkpatch.conf, scripts/checkpatch.pl
Update checkpatch script to the latest version (571d54ed9). Max line length
has been increased to 100.
=> [PATCH v2] checkpatch: update to the latest version

example/l3fwd/odp_l3fwd.c, example/timer/odp_timer_accuracy.c, helper/cuckootable.c, helper/iplookuptable.c, platform/linux-generic/odp_crypto_openssl.c, platform/linux-generic/odp_pool.c
Fix a bunch of issues (both actual bugs and cosmetic issues) found by a static analyzer.
=> [PATCH v2] Miscellaneous fixes and clean up

.travis.yml
Add test for GCC-10 LTO build.
=> [PATCH v2] travis: add gcc 10 lto build test

CHANGELOG
Add latest API changes and fixed issues.
=> [PATCH v2] changelog: updates for odp v1.24.0.0

platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c
Updated list of ARM and Marvell part numbers. Improved ARM ISA version detection. Added ARM feature macros to sysinfo print. These can be used to check that compiler builds against the correct ARM ISA.
=> [PATCH v3] Update ARM system info

test/performance/odp_packet_gen.c
V2:
- Moved wait logic to rx threads (Janne)
=> [PATCH v3] test: packet_gen: misc fixes

DEPENDENCIES, platform/linux-generic/odp_random_null.c, platform/linux-generic/pktio/socket_common.c, platform/linux-generic/pktio/socket_mmap.c
V2:
- Added debug print about recreated TPID (Janne)
- Handle endianness in random_null (Janne)
- Updated Linux dependency (new commit)
V3:
- Added check that RAND_MAX is a power of two minus 1 and cleaned commit message (Janne)
=> [PATCH v3] Misc fixes to support older kernel versions

include/odp/api/spec/queue.h, platform/linux-generic/include/odp/api/plat/queue_inline_types.h, platform/linux-generic/include/odp_queue_lf.h, platform/linux-generic/include/odp_ring_mpmc_internal.h, platform/linux-generic/include/odp_ring_spsc_internal.h, platform/linux-generic/include/odp_ring_st_internal.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_if.c, platform/linux-generic/odp_queue_lf.c, platform/linux-generic/odp_queue_scalable.c, test/validation/api/queue/queue.c
Add new odp_queue_print() function for printing implementation defined
queue debug information.
=> [PATCH v2] api: queue: add odp_queue_print() function

test/validation/api/scheduler/scheduler.c
Add scheduler test case to check that queues enqueues work with pause on.
=> [PATCH v3] Master pause enq test

configure.ac, include/odp/api/spec/classification.h, include/odp/api/spec/packet.h, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_classification.c, platform/linux-generic/odp_packet.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/packet/packet.c, test/validation/api/pktio/pktio.c
This PR finalizes the mark API changes of https://github.com/OpenDataPlane/odp/pull/1010
=> [PATCH v2] api: CLS mark support (with implementation)

test/performance/odp_l2fwd.c
Fix l2fwd mode with ordered queues for schedulers with prefetch
capability. If prefetch is enabled, prefetched event is not received by
a worker as exit_threads is checked in l2fwd loop. The prefetched event
could block the forward progress of other workers because of ordering
constraints. This patch adds a loop to drain prefetched event before
entering barrier to wait for other threads.
Signed-off-by: Shijith Thotton <sthotton@marvell.com>
=> [PATCH v3] test: l2fwd: add loop to drain prefetched events

test/performance/odp_l2fwd.c
Ideally l2fwd should have promiscuous enabled.
This change is inline with example/l2fwd_simple application.
=> [PATCH v4] test: l2fwd: enable promisc mode for dev that support it

example/l2fwd_simple/l2fwd_simple_run.sh
Remove null pktio test which is linux-generic implementation specific.
Testing with this pktio type didn't provide much additional valua anyway.
=> [PATCH v2] example: l2fwd_simple: remove implementation specific null pktio test

example/classifier/odp_classifier.c
Add support for:
- Promisc mode
- ODP_PMR_DMAC
- ODP_PMR_DIP_ADDR
=> [PATCH v2] Classifier example improvements

test/performance/odp_l2fwd.c
Vector mode enables packets to be received as vectors.
Signed-off-by: Shijith Thotton <sthotton@marvell.com>
=> [PATCH v7] test: l2fwd: add packet vector support

example/generator/odp_generator.c, example/packet/odp_packet_dump.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, test/performance/odp_sched_latency.c, test/performance/odp_sched_perf.c
V2:
* Detect `print_packet()` failure (Jere)
=> [PATCH v3] Fix warnings reported by static code checkers

platform/linux-generic/odp_schedule_sp.c, test/validation/api/scheduler/scheduler.c
Threads were not informed about new group create or destroy. Threads were informed only when group join/leave was used. Added new test case to check that newly created group schedules events (without group join).
=> [PATCH v2] Fix strict priority scheduler group create

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c
V2:
- Increase out_discards statistics counter when packets are dropped (Jere)
=> [PATCH v3] linux-gen: pktio: support transmitting packet vectors using odp_queue_enq()

example/timer/odp_timer_accuracy.c
Added new options to timer accuracy test to control maximum timeout and clock source parameters.
=> [PATCH v4] Timer accuracy test options

test/performance/odp_sched_pktio.c
Cleanup prefetched events before worker exits. Also break before
schedule multi is called if exit is triggered.
=> [PATCH v5] test: sched_pktio: cleanup prefetched events before worker exit

platform/linux-generic/odp_ipsec.c
fix for issue with index oob for ipsec SA's #1152
=> [PATCH v6] Fix issue with index oob for ipsec SA's

test/validation/api/system/system.c
Update validation test for system info to check ISA versions
for ARM HW.
Signed-off-by: Gowrishankar Muthukrishnan <gmuthukrishn@marvell.com>
=> [PATCH v3] validation: system: update hw isa checks for arm

test/performance/odp_l2fwd.c
Present l2fwd consider packet length 1536 for pool creation, it limits
the packet length to X * 1536 when platform supports X number of segments.
This new command line argument along with pool capabilities will create
packet pool to support packets up to 64K MTU.
Signed-off-by: Satha Rao <skoteshwar@marvell.com>
=> [PATCH v8] example/l2fwd: add argument to get packet length

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_mem_perf.c
Added new test application that measures memory system
bandwidth.
=> [PATCH v4] test: mem_perf: add memory performance test

helper/Makefile.am, helper/include/odp/helper/ipsec.h, helper/ipsec.c, test/performance/odp_ipsec.c, test/validation/api/ipsec/ipsec.c
Add IPSEC capability check function in helper to check whether the specified
IPSEC configuration is supported.
=> [PATCH v4] helper: ipsec: add capability check function

config/odp-linux-generic.conf, include/odp/api/spec/schedule.h, include/odp/api/spec/schedule_types.h, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_scalable.c, platform/linux-generic/odp_schedule_sp.c, test/validation/api/Makefile.am, test/validation/api/scheduler/.gitignore, test/validation/api/scheduler/Makefile.am, test/validation/api/scheduler/scheduler.c, test/validation/api/scheduler/scheduler_no_predef_groups.c
V4:
- Rebase
- Reviewed-by tags
=> [PATCH v5] api: sched: pause and scheduling group configuration improvements

test/validation/api/classification/odp_classification_common.c
One GTP-u PMR test creates a GTP packet but then changes the UDP port
which makes cls_pkt_get_seq() treat the packet as a plain UDP packet,
causing it to read the test packet sequence number from a wrong location.
Fix the problem and simplify the sequence number functions by storing the
sequence number in the last bytes of the packet regardless of packet type.
Signed-off-by: Satheesh Paul <psatheesh@marvell.com>
=> validation: cls: fix GTP test by changing seqno location

test/performance/odp_mem_perf.c
Fixes theoretical array overflow found by Coverity
=> [PATCH v2] test: mem_perf: check num cpus with all workers option

example/debug/odp_debug.c, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_packet_io.c
Add calls to odp_pktio_print(), odp_packet_print_data(), odp_ipsec_print() and odp_sys_config_print().
=> [PATCH v2] example: debug: add debug print calls

.codecov.yml, .github/workflows/ci-pipeline.yml
Update Codecov GitHub Action to the latest version (v1.2.1).
V2:
- Modified Codecov configuration
=> [PATCH v3] github_ci: update codecov action version

test/common/odp_cunit_common.c
In existing test framework, all the tests in a test suite are always
run irrespective of individual test failures.
This patchset adds an option to run the test suites in a mode where
a test suite gets killed on the first test failure. This mode can be
activated by setting the environment variable ODP_CUNIT_FAIL_IMMEDIATE.
In this mode, before the start of any test in a test suite, it checks
for errors in previously ran tests and immediately triggers an exit if
an error is detected.
=> [PATCH v3] test: cunit: add cunit run mode for immediate test suite exit on failure

example/timer/odp_timer_accuracy.c
Added -R (--res_hz) option for passing resolution in hertz
to timer pool parameters. Changed long name of -r option
to "--res_ns".
=> [PATCH v2] example: timer_accuracy: add resolution in hertz option

include/odp/api/abi-default/atomic.h, include/odp/api/spec/atomic.h, include/odp/api/spec/std_types.h, platform/linux-generic/Makefile.am, platform/linux-generic/arch/aarch64/odp/api/abi/atomic.h, platform/linux-generic/arch/aarch64/odp_atomic.h, platform/linux-generic/include-abi/odp/api/abi/atomic.h, platform/linux-generic/odp_atomic.c, test/validation/api/atomic/atomic.c
Add 128 bit atomic compare-and-swap operations.
=> [PATCH v49] api: atomic: add 128 bit atomic apis

example/debug/odp_debug.c, include/odp/api/spec/timer.h, platform/linux-generic/include/odp_timer_internal.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
Add debug print functions and makes user pointer type const (bumped into that while writing new tests).
=> [PATCH v3] api: timer: debug print

example/debug/odp_debug.c, include/odp/api/spec/queue.h, platform/linux-generic/include/odp/api/plat/queue_inline_types.h, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_queue_if.c, platform/linux-generic/odp_queue_scalable.c, test/validation/api/queue/queue.c
Debug print function which can be used to check parameters of all created queues.
=> [PATCH v2] api: queue: print all queues

platform/linux-generic/odp_queue_scalable.c
Read sync and prio values correctly.
=> [PATCH v2] linux-gen: queue: fix scalable queue print

test/performance/odp_l2fwd.c, test/performance/odp_packet_gen.c
Add new command line option (-M, --mtu) for modifying link MTU value.
=> [PATCH v3] Add support for changing interface MTU for odp_l2fwd and odp_packet_gen examples

example/sysinfo/odp_sysinfo.c, include/odp/api/spec/system_info.h, platform/linux-generic/arch/aarch64/odp_sysinfo_parse.c, test/validation/api/system/system.c
ARM has published v8.7 ISA. Add enumeration for the new ISA version.
=> [PATCH v3] api: add enumeration for ARMv8.7 ISA

platform/linux-generic/odp_init.c, platform/linux-generic/odp_libconfig.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_traffic_mngr.c
Fix 6 warnings reported by Coverity
=> [PATCH v2] linux-gen: fix Coverity warnings

test/performance/odp_pool_perf.c
Add an option to set cache size in pool perf test.
=> [PATCH v3] test: pool_perf: add option to set cache size

include/odp/api/spec/packet_io_stats.h, platform/linux-generic/pktio/dpdk.c, platform/linux-generic/pktio/loop.c, platform/linux-generic/pktio/pcap.c, platform/linux-generic/pktio/stats/ethtool_stats.c, platform/linux-generic/pktio/stats/packet_io_stats.c, platform/linux-generic/pktio/stats/sysfs_stats.c, test/validation/api/pktio/pktio.c
V4:
- Clarified the term 'successful' (Yuri)
- Mention Ethernet in `in_ucast_pkts` and `out_ucast_pkts` documentation (Yuri)
- Add mention about pause frames (Yuri)
=> [PATCH v5] api: pktio: statistics: add in_packets/out_packets counters

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c
- Keep free SAs in a freelist
- Simplify SA states
- Remove unnecessary synchronization
- Fix a parameter handling bug in SA creation
=> [PATCH v2] linux-gen: ipsec: a couple of improvements and bug fixes

test/validation/api/scheduler/scheduler.c
Add a new atomicity validation test, which checks that only a single thread
is able to process events from an atomic queue at the same time.
V2:
- Added comment about releasing atomic context and prescheduled events (Janne)
=> [PATCH v2] validation: scheduler: add new atomicity test

.github/workflows/ci-pipeline.yml, platform/linux-generic/arch/x86/odp/api/abi/hash_crc32.h, test/validation/api/ipsec/ipsec.c
Small fixes required for odp-dpdk merge.
=> [PATCH v1] Misc fixes

platform/linux-generic/odp_schedule_basic.c, test/performance/odp_sched_perf.c
Add number of threads and queues per spread statistics as preparation for dynamic spread load balancing.
=> [PATCH v4] linux-gen: scheduler: prepare dynamic load balance

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, DEPENDENCIES, m4/odp_dpdk.m4, platform/linux-generic/libodp-linux.pc.in, platform/linux-generic/m4/odp_dpdk.m4, platform/linux-generic/pktio/dpdk_parse.c, scripts/ci/build_arm64.sh
V3:
- Replace global _GNU_SOURCE define with `#include <odp_posix_extensions.h>`
=> [PATCH v4] Update supported DPDK version to 20.11

include/odp/api/spec/std_types.h, include/odp/api/spec/timer.h, platform/linux-generic/Makefile.am, platform/linux-generic/odp_fractional.c, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
Add clock source enumeration options. Add tick info which can document precisely tick period in nsec, hz or input clock cycles.
=> [PATCH v4] api: timer tick info

test/performance/odp_sched_perf.c
Added -v option which outputs additional debug information.
At this point, verbose option adds a scheduler debug print
call to the end of the test.
=> [PATCH v2] test: sched_perf: add verbose option

platform/linux-generic/pktio/dpdk.c
dpdk_open() only allows netdev string to be a port number
This is to allow passing all other supported DPDK ports as well.
=> [PATCH v4] linux-gen: pktio: use names other than index also as dpdk ports

test/performance/odp_sched_perf.c
Added -L and -H options to allow usage of multiple queue priority levels.
=> [PATCH v2] test: sched_perf: add low and high prio options

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml, config/odp-linux-generic.conf, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf
Adds dynamic load balance of spread queues. It's enabled on default and can be disabled from config file.
=> [PATCH v7] linux-gen: sched: dynamic load balance

test/performance/odp_l2fwd.c
Multiple flows are disabled in default scheduler configuration. Using
max supported flows will improve the throughput of l2fwd.
Signed-off-by: Shijith Thotton <sthotton@marvell.com>
=> [PATCH v4] test: l2fwd: use max flow id to configure scheduler

example/debug/odp_debug.c, platform/linux-generic/include/odp_buffer_internal.h, platform/linux-generic/include/odp_queue_basic_internal.h, platform/linux-generic/include/odp_schedule_if.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_queue_basic.c, platform/linux-generic/odp_schedule_basic.c, platform/linux-generic/odp_schedule_if.c, platform/linux-generic/odp_traffic_mngr.c, test/performance/odp_sched_perf.c
Print queue group and spread as part of debug print calls. Align queue priority value on schedule and queue debug print calls.
=> [PATCH v2] linux-gen: improve queue debug print

platform/linux-generic/odp_ipsec.c
implementation of the api odp_ipsec_stats_multi which is currently
not present
=> [PATCH v5] linux-gen: ipsec: stats multi api addition

scripts/spelling.txt
Updated spelling file and added ODP specific section as Jere suggested.
=> [PATCH v2] Update spelling file

platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/odp_crypto_test_inp.c
Fix processing of multi-segment packets and do validation testing with multi-segment packets too.
=> [PATCH v2] crypto: fix processing of multi-segment packets

platform/linux-generic/odp_ipsec.c
If an IPsec-processed packet cannot be enqueued to the destination queue,
indicate the packet as consumed to the caller and free the packet. Since
the input packet has already been modified, it is not possible to report
it as not consumed. Previously the packet was both freed and reported as
not consumed.
Not generating a completion event for an async IPsec operation may not be
fully compliant with the current API spec, but it is probably better than
mangling or freeing a packet that is reported as not consumed.
Fix also the bug where inbound SA was not 'unused' after processing if
the destination queue enqueuing failed.
=> [PATCH v1] linux-gen: ipsec: fix handling of completion event enqueueing failure

helper/cli.c, helper/include/odp/helper/cli.h
Add new API function odph_cli_log_va() and a new member "hostname" to odph_cli_param_t to allow users to provide hostname.
=> [PATCH v7] Helper cli

test/performance/odp_sched_perf.c
Measure and display the number of events dequeued from each queue as a percentage of average. Add new command line option -a.
Events are counted using one atomic variable for each queue, which may slow the test down a little.
Example printout:
```
RESULTS - events per queue (percent of average):
------------------------------------------------
1      2      3      4      5      6      7      8      9     10
100.0  100.0  100.0   99.9  100.1  100.1  100.0  100.0 
```
v2:
- Rebase.
=> [PATCH v2] test: sched_perf: measure queue fairness

platform/linux-generic/pktio/dpdk_parse.c
Merge fixes done to the generic packet parsing code (ad9638fd9, 50fe59300,
adae181a7) into the DPDK specific packet parsing implementation.
=> [PATCH v2] linux-gen: dpdk: packet parsing fixes

test/performance/odp_l2fwd.c
- Never send vectors but just plain packets, even in vector mode. Sending vectors is not supported by ODP API.
- Accept plain packet events in addition to vectors in vector mode. ODP api does not promise that only vectors are received in vector mode.
- Reduce duplication of code
=> [PATCH v3] l2fwd fixes related to packet vectors

platform/linux-generic/odp_init.c
Add checks for detecting if odp_init_local() function has been called twice
or odp_term_local() was called without previous odp_init_local() call.
=> [PATCH v2] linux-gen: init: detect calling odp_init_local() twice

example/classifier/odp_classifier.c
Fix memory leak that would occur if pattern matching rule policy
parsing is stopped due to an error.
Signed-off-by: Tuomas Taipale <tuomas.taipale@nokia.com>
=> [PATCH v4] example: classifier: fix potential memory leaks

test/performance/odp_pktio_ordered.c
Add command line option '-P, --promisc_mode' to pktio ordered test
application, which allow to enable promiscuous mode for the devices that
supports it.
Signed-off-by: Volodymyr Fialko <vfialko@marvell.com>
=> [PATCH v3] test: pktio_ordered: add option to enable promisc mode

test/performance/odp_dma_perf.c
In addition to packet-type data, shared memory backed plain memory-type
data can now also be configured to be used as the test data.
Instead of always exiting when an error occurs, try cleaning up first
when possible.
v2:
- improve function names
=> [PATCH v2] test: performance: dma_perf: add plain memory-type transfer support

helper/threads.c, platform/linux-generic/include/odp_schedule_if.h, platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/ipc.c
A few minor fixes to make GCC 11.2 happy (on aarch64).
=> [PATCH v2] fixes for compiling with GCC-11

platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/odp_packet_io.c
Prepare for LSO with TM API change. Split LSO send into parts that can be reused with TM.
=> [PATCH v2] linux-gen: pktio: split LSO send function

test/validation/api/crypto/odp_crypto_test_inp.c
Test that hash result field that overlaps the authenticated range is handled according to the latest API spec: The field must be zeroed before hash verification in decode sessions and left alone before hash generation in encode sessions.
=> [PATCH v3] validation: crypto: test hash result within authenticated range

platform/linux-generic/pktio/dpdk.c
When freeing copied packets after zero-copy send, copy need was checked
by accessing the packet header. At this point, the data may or may not
be valid anymore. Fix this by saving the indices of copied packets
already beforehand and use those for later access.
Signed-off-by: Tuomas Taipale <tuomas.taipale@nokia.com>
v2:
=> [PATCH v2] linux-gen: dpdk: fix potential undefined behavior with zero-copy

config/odp-linux-generic.conf, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/include/odp_packet_io_internal.h, platform/linux-generic/m4/odp_libconfig.m4, platform/linux-generic/odp_event.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_packet_io.c, platform/linux-generic/odp_traffic_mngr.c, platform/linux-generic/test/inline-timer.conf, platform/linux-generic/test/packet_align.conf, platform/linux-generic/test/process-mode.conf, platform/linux-generic/test/sched-basic.conf, test/validation/api/pktio/pktio.c
Implement event completion for transmitted and dropped packets.
v2:
- address Petri's and Matias' comments
v5:
- rebase
- address Petri's comments
v6:
- address Petri's comments
v8:
- rebase
- address Matias' comment
- add reviewed-by tags
=> [PATCH v8] linux-gen: pktio: implement tx completion event

include/odp/api/spec/timer.h, include/odp/api/spec/timer_types.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
Adds periodic timer APIs and new start/restart functions for single shot timers.
=> [PATCH v10] api: timer: periodic timer

platform/linux-generic/pktio/dpdk.c
Remove conditional code that is not relevant anymore from DPDK 19.11
onwards.
v3:
- Add reviewed-by tag
=> [PATCH v3] linux-gen: dpdk: remove unsupported conditional code

test/performance/odp_ipsec.c
This PR has the following patches. @anoobj , maybe you could do the review since you are adding the burst support.
test: performance: ipsec: fix IPsec processing error checking
Do not use odp_packet_has_error() for checking whether outbound
IPsec processing succeeded. The flag is not supposed to indicate
any IPsec errors other than inner packet parse errors in IPsec
decapsulation.
Do not ignore the result status returned by odp_ipsec_result(),
but print an error message if the odp_ipsec_result() call fails
or indicates an error.
test: performance: ipsec: use schedule_multi and queue_deq_multi
Dequeue/schedule multiple IPsec-processed packets at a time by using
odp_queue_deq_multi() and odp_schedule_multi().
=> [PATCH v5] test: performance: ipsec: fix a minor bug and use schedule_multi

test/performance/odp_ipsec.c
Receive IPsec processed packets as a vector packet on supported
platforms.
ODP allows IPsec processed packets to be received as a vector packet
by aggregating events with similar ordering context. New option
'--vector' or '-v' can be used to enable vector aggregation post IPsec
processing. When specified without any arguments, vector size would be
set as 32. User can control vector size by specifying the optional
argument.
Usage: 'odp_ipsec --vector=32'
=> [PATCH v3] test: performance: ipsec: add vector packet support

include/odp/api/abi-default/traffic_mngr.h, include/odp/api/spec/traffic_mngr.h, platform/linux-generic/odp_traffic_mngr.c, test/validation/api/traffic_mngr/traffic_mngr.c
V3:
- Added validation tests for TM queue threshold
=> [PATCH v4] api: tm: split tm queue and node threshold capabilities

test/performance/odp_sched_latency.c
Added new -g and -i options which enable latency testing with multiple groups.
=> [PATCH v2] test: sched_latency: add group options

platform/linux-generic/include/odp_packet_internal.h
Copy also packet subtype and subtype specific metadata in
_odp_packet_copy_md().
=> [PATCH v2] linux-gen: packet: add missing subtype metadata to _odp_packet_copy_md()

test/performance/odp_l2fwd.c
New -I and -G options for testing group/priority scheduling.
=> [PATCH v4] test: l2fwd: new priority and group options

test/validation/api/timer/timer.c
Improvements to periodic timer test coverage.
=> [PATCH v2] validation: timer: improve periodic timer tests

include/odp/api/spec/classification.h, platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_test_pmr.c
Add new PMR enumeration for PCP bits in VLAN header
=> [PATCH v4] api: cls: add VLAN PCP PMR term

test/performance/odp_packet_gen.c
Add new option (-W, --wait_start) to wait for N seconds before starting
test traffic. The wait is performed after optional link status check. This
is useful for example when the opposing end of network link requires some
time to start properly.
=> [PATCH v2] test: packet_gen: add new wait option

test/performance/odp_l2fwd.c
Add new option (-q, --rx_queues) for configuring the number of RX queues
used per interface in scheduled mode.
=> [PATCH v4] test: l2fwd: add option for selecting rx queue count per interface

example/timer/Makefile.am, example/timer/odp_timer_accuracy_run.sh, test/validation/api/time/time.c
Make time validation test and timer_accuracy example complete faster to speed up make check
=> [PATCH v6] Speed up make check

.github/workflows/coverity.yml
Disable daily Coverity scan emails to the mailing list.
Reviewed-by: Tuomas Taipale <tuomas.taipale@nokia.com>
=> [PATCH v1] github_ci: disable coverity emails

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
Add new build only tests for GCC versions 11 and 12.
=> [PATCH v2] github_ci: add build test job for gcc versions

platform/linux-generic/pktio/socket_xdp.c
This patch fixes #1622 and freeze issue reported in #1623.
v2:
=> [PATCH v3] linux-gen: socket_xdp: add miscellaneous bug fixes

include/odp/api/spec/packet_io.h, platform/linux-generic/pktio/pcap.c, test/validation/api/pktio/pktio.c
Copy of #1614 with reviewed-by tags added.
=> [PATCH v2] api: pktio: promisc mode disabled by default

include/odp/api/spec/cpumask.h, platform/linux-generic/include/odp_global_data.h, platform/linux-generic/odp_cpumask.c, platform/linux-generic/odp_cpumask_task.c, test/validation/api/atomic/atomic.c, test/validation/api/barrier/barrier.c, test/validation/api/cpumask/cpumask.c, test/validation/api/lock/lock.c, test/validation/api/pool/pool.c, test/validation/api/queue/queue.c, test/validation/api/scheduler/scheduler.c, test/validation/api/shmem/shmem.c, test/validation/api/timer/timer.c
Copy of PR #1616 with reviewed-by tags added.
=> [PATCH v2] api: cpumask: default CPU mask may be NULL

DEPENDENCIES
v2:
- Wording changed
v3:
- Reviewed-by tag added
=> [PATCH v3] dependencies: clarify XDP and DPDK zero-copy exclusivity

platform/linux-generic/include/odp_llqueue.h
The cpu_pause while loop is added to handle the case that the dequeue happens when an enqueue is in progress and the llq->u.ui.head is being updated.
In some corner case, however, if the old.st.head is dequeued from llq and then enqueued into another queue before the while loop starts, then the dequeue can get stuck in the while loop until the queue is scheduled again.
Add a threshold of spin count, so we will re-check the llq head once max spin count is reached.
=> [PATCH v10] Avoid possible deadloop in llq dequeue

test/performance/odp_ipsecfwd.c
Fix two issues:
- Initialize configuration data structure earlier so that in certain
error cases teardown phase would not see uninitialized data.
- Free SA and FWD config file path strings in teardown phase so that
they don't leak if "--help" was passed with them.
- Handle `odp_ipsec_status()` return value in `wait_sas_disabled()`
to avoid potentially uninitialized `odp_ipsec_status_t` access
later.
v3:
=> [PATCH v3] test: ipsecfwd: fix bugs

test/validation/api/classification/odp_classification_basic.c
Added missing default value checks for CoS action and stats_enable.
=> [PATCH v2] validation: cls: add param default value checks

test/performance/odp_ipsecfwd.c
This patchset adds options to `odp_ipsecfwd` to configure input, SA completion and output queue counts.
Additionally, SA configuration error handling is now more pragmatic and queue naming is improved.
v3:
- Added hashing based on outgoing packet to choose output queue
v4:
- Increased maximum number of suported SAs
=> [PATCH v5] test: ipsecfwd: make queue counts configurable

helper/cli.c
If vsnprintf() fails, log an error and return error status.
v2:
- Rebase.
=> [PATCH v3] helper: cli: check for vsnprintf errors

platform/linux-generic/odp_classification.c, test/validation/api/classification/odp_classification_basic.c
Fix a few bugs related to class-of-service hash-queues:
- In `odp_cls_cos_create()`, use the passed queue parameters as per
the specification instead of local parameters and always set
`queue_group` flag based on number of queues.
- Destroy class-of-service hash-queues in `odp_cos_destroy()`.
- When printing class-of-service information in `odp_cls_print_all()`,
take potential hash-queues into account.
Additionally, give proper names to hash-queues created in
`odp_cls_cos_create()` to help in debugging.
v2:
- Rebased
- Fixed Matias' comments
v3:
- Rebased
- Fixed remaining comment
=> [PATCH v3] linux-gen: cls: fix cos hash-queue handling

platform/linux-generic/odp_schedule_basic.c
Change group mask variables to 64 bits in order to increase maximum number of supported groups from 32 to 64.
=> [PATCH v1] linux-gen: sched: increase max number of groups to 64

platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/odp_packet.c
Inline implementation of odp_packet_ts_set() function.
=> [PATCH v2] linux-gen: packet: inline odp_packet_ts_set() implementation

example/classifier/odp_classifier.c
Some improvements to the classifier example, mainly to enable performance testing.
v2:
- Rebase.
- Tuomas' comments.
v3:
- Rebase.
=> [PATCH v3] example: classifier: improvements for performance testing

platform/linux-generic/odp_ipsec.c
This patchset adds crypto burst support to IPsec inbound and outbound handling.
Patches 4f4da08 and 9f01b6c refactor the single packet inbound and outbound handling. Later patches then utilize reusable portions from them.
With suitable algorithms, bursting yields a notable performance increase (provided that the underlying crypto implementation supports bursting as well).
v2:
=> [PATCH v2] linux-gen: ipsec: add crypto burst support

test/performance/odp_packet_gen.c
Added -D option to select between scheduled and direct packet input modes.
=> [PATCH v1] test: packet_gen: add direct pktin mode option

platform/linux-generic/include/odp_classification_datamodel.h, platform/linux-generic/odp_classification.c
A few small performance improvements to packet classifier.
Branched from PR #1681.
v2:
- Rebase on master.
- Petri's comments.
v3:
- Rebase.
- Fix linked_cos.
=> [PATCH v3] linux-gen: cls: performance improvements

platform/linux-generic/include/odp_ipsec_internal.h, platform/linux-generic/odp_ipsec.c, platform/linux-generic/odp_ipsec_sad.c, test/validation/api/ipsec/ipsec.c, test/validation/api/ipsec/ipsec.h, test/validation/api/ipsec/ipsec_test_out.c
Add IPsec SA expiry tests in out suite.
=> [PATCH v14] validation: ipsec: add sa expiry test

test/performance/odp_dma_perf.c
This patchset adds a few improvements to `odp_dma_perf`:
- event wait period can now be configured
- DMA transfers are retried if they fail due to resources being unavailable
v2:
- Added a patch for DMA transfer retries
- Changed PR subject accordingly
v3:
- Added a patch to handle maximum retries
v4:
=> [PATCH v4] test: dma_perf: add a few improvements

example/sysinfo/odp_sysinfo.c, test/performance/odp_crypto.c
test: performance: crypto: check if crypto operations succeed
example: sysinfo: add missing crypto algorithm names
=> [PATCH v3] Crypto: small fixes to sysinfo and crypto perf test

test/validation/api/system/system.c
CPU cycle count may advance in steps that are not integer values. For example, implementation may measure time and convert it to CPU cycles, and multiplier between time units and CPU frequency may have decimals.
=> [PATCH v2] validation: system: relax CPU cycle count resolution tests

platform/linux-generic/odp_packet_io.c
When classifier is in use, only one packet I/O input queue should be configured. Currently, one packet I/O level input queue is configured but driver level input queue count will be whatever is passed via `odp_pktin_queue_param_t::num_queues` in `odp_pktin_queue_config()`.
Fix this by always overriding the parameter to correct value when applicable.
v2:
v3:
- Fixed queue count check
=> [PATCH v3] linux-gen: pktio: fix input queue count with classifier

platform/linux-generic/pktio/dpdk.c
For DPDK zero-copy pktio to work with VFIO the packet pool memory has to be mapped for DMA access.
Fixes: https://github.com/OpenDataPlane/odp/issues/1718
=> [PATCH v2] linux-gen: dpdk: fix zero-copy mode with vfio-pci driver

test/performance/odp_crypto.c
Fix typo in comments found by code review.
=> [PATCH v3] test: performance: crypto: fix typos

test/validation/api/timer/timer.c
Added test case to check periodic timer capability functionality with various values of base frequency, max multiplier and resolution.
=> [PATCH v4] test: timer: add periodic timer capability test

helper/include/odp/helper/ipsec.h, helper/ipsec.c, test/performance/odp_ipsec.c, test/performance/odp_ipsecfwd.c, test/performance/odp_l2fwd.c, test/validation/api/ipsec/ipsec.c
Fix a few cases reported by Coverity:
- helper: ipsec: fix pass-by-value
- test: l2fwd: fix pass-by-value
- test: ipsecfwd: add return value checks
v2:
=> [PATCH v2] add miscellaneous fixes

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_bench_timer.c
Added new benchmark test for call latency of (small) functions in timer API.
=> [PATCH v2] test: bench_timer: new performance test for timer API

test/performance/odp_dma_perf.c
Fix a few potential integer overflows reported by Coverity.
v2:
=> [PATCH v2] test: dma_perf: fix potential overflows

platform/linux-generic/arch/x86/cpu_flags.c
Update x86 CPU flags code from DPDK v23.03.
=> [PATCH v2] linux-gen: cpu: update x86 CPU flags code

test/validation/api/crypto/crypto_op_test.c, test/validation/api/crypto/crypto_op_test.h, test/validation/api/crypto/odp_crypto_test_inp.c
Crypto validation bug fixes separated from PR 1836.
=> [PATCH v1] crypto validation bug fixes

include/odp/api/spec/timer.h
Improved timer alloc and restart documentation. Functionality is not changed.
v3: rebased
=> [PATCH v4] api: timer: improve documentation

platform/linux-generic/arch/aarch64/cpu_flags.c
Add missing HWCAP2 flags and simplify the code checking the flags.
=> [PATCH v3] linux-gen: update ARM HWCAP2 flags

test/performance/odp_dma_perf.c
Wait for transfers to complete in asynchronous poll mode before
tearing down the associated memory.
Reviewed-by: Tuomas Taipale <tuomas.taipale@nokia.com>
=> [PATCH v6] test: dma_perf: drain poll transfers before teardown

test/performance/odp_queue_perf.c
Depending on the ODP implementation odp_queue_enq_multi() may not be able to always enqueue all events, so add retry for the remaining events.
Print the total number of dequeue/enqueue retries in results as the average value per seconds easily rounds down to zero.
=> [PATCH v2] test: queue_perf: add retry to odp_queue_enq_multi() operations

test/performance/odp_timer_perf.c
Add new mode (-m 2), which measures odp_schedule() overhead while continuously restarting expiring timers.
=> [PATCH v4] test: timer_perf: add new mode which starts timers again as they expire

test/performance/odp_ipsecfwd.c
Fix checks for zero-case packet pool capabilities and improve post-test statistics summary.
v2:
- Reworded commit message of second patch to be more easily parseable by humans
=> [PATCH v2] test: ipsecfwd: add miscellaneous fixes

test/performance/odp_l2fwd_run.sh
Shorten test script run from 30 sec to 5 sec.
=> [PATCH v2] test: l2fwd: shorten tests run length

example/sysinfo/odp_sysinfo.c
V2:
- Removed extra newlines
- Print clock source ID for all timer clock sources
=> [PATCH v3] example: sysinfo: print more capabilities

example/sysinfo/odp_sysinfo.c
Print timer pool tick info from odp_timer_pool_info().
=> [PATCH v2] example: sysinfo: print timer pool tick information

test/performance/.gitignore, test/performance/Makefile.am, test/performance/odp_stash_perf.c
Add stash perf test case to benchmark stash performance.
=> [PATCH v8] test: performance: add stash perf test

test/validation/api/buffer/buffer.c, test/validation/api/dma/dma.c, test/validation/api/ipsec/ipsec.c, test/validation/api/timer/timer.c
Fix compilation errors due to uninitialized variables.
=> [PATCH v2] validation: fix compilation error

platform/linux-generic/odp_packet_io.c, platform/linux-generic/pktio/dpdk.c, test/performance/odp_packet_gen.c
Modify packet_gen to support don't free. Implement don't free option to linux-gen DPDK pktio to test that application works.
=> [PATCH v3] test: packet_gen: add don't free packet output option

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
Enable usage of GitHub merge queue feature.
=> [PATCH v2] github_ci: enable using github merge queue

include/odp/api/spec/timer.h, platform/linux-generic/odp_timer.c, test/validation/api/timer/timer.c
V2:
- Added implementation and validation tests
=> [PATCH v4] api: timer: add timeout alloc/free multi functions

test/performance/odp_l2fwd.c
Ease application usage by always printing interface MAC addresses. Also, clean and unify prints in create_pktio() function.
Move application options print to the beginning of main(), so that options are printed also in case of setup failures.
=> [PATCH v2] test: l2fwd: always print interface mac addresses

.github/workflows/ci-pipeline-arm64.yml, .github/workflows/ci-pipeline.yml
Ubuntu 18.04 is already EOL, so remove the OS specific tests from CI.
=> [PATCH v2] github_ci: remove ubuntu 18.04 tests

test/validation/api/pool/pool.c
When testing odp_pool_stats(), check thread.cache_available[] counters only for the number of threads requested. Also, added statistics struct initialization to catch more robustly output errors in the functions.
=> [PATCH v2] validation: pool: check only requested thread statistics

test/performance/bench_common.c
Run a warmup round for each test just before the actual test run instead of running it for all tests before any actual test runs. This way other tests do not run between the warmup and the actual test run and the code becomes a bit cleaner too.
Test specific init functions are still run after the warmup, which may skew the results.
=> [PATCH v4] test: performance: improve warmup in common test bench

example/debug/odp_debug.c
In pktio case, call extra statistics print in addition to pktio print.
=> [PATCH v2] example: debug: call odp_pktio_extra_stats_print()

include/odp/api/spec/packet.h, include/odp/api/spec/timer.h
Clarify time specification of packet IO time and timer tick
=> [PATCH v3] api: time: clarify packet IO time and timer tick

test/validation/api/pktio/pktio.c
Check that odp_packet_tx_compl_done() returns initially zero and that it does not clear completion status.
=> [PATCH v2] validation: pktio: add tx completion index checks

example/timer/odp_timer_test.c, test/performance/odp_bench_timer.c
Add missing timer free return value checks into various timer test applications.
=> [PATCH v2] test: timer: add timer free return value checks

test/performance/odp_bench_misc.c
Added test cases for odp_prefetch() and odp_prefetch_store().
=> [PATCH v2] test: bench_misc: add prefetch tests

test/validation/api/pool/pool.c
Values of per thread counters (odp_pool_stats_t.thread.cache_available[]) are undefined if these counters are not supported/enabled.
=> [PATCH v2] validation: pool: fix pool statistics test

example/debug/odp_debug.c
Print pktio link info and enable pktio interface name as option.
=> [PATCH v3] example: debug: pktio link info

test/performance/odp_bench_buffer.c
Add test cases for recently added event and buffer API calls.
=> [PATCH v3] test: bench_buffer: add new test cases

platform/linux-generic/include/odp/api/plat/event_inline_types.h, platform/linux-generic/include/odp/api/plat/event_inlines.h, platform/linux-generic/include/odp/api/plat/packet_inline_types.h, platform/linux-generic/include/odp/api/plat/packet_inlines.h, platform/linux-generic/include/odp_event_internal.h, platform/linux-generic/include/odp_packet_internal.h, platform/linux-generic/odp_event.c, platform/linux-generic/odp_packet.c, platform/linux-generic/odp_pool.c
Move event subtype field from packet header to event header
=> [PATCH v2] linux-gen: event: move subtype field

test/performance/odp_dma_perf.c
Swap to use `odp_time_local_strict()` for timestamping for less overhead. Additionally, drop some redundant calculations with synchronous DMA and memory copy options.
v2:
- Copyright year bumped
=> [PATCH v3] test: dma_perf: refactor timestamping

test/performance/odp_pool_latency.c
Fix a potential integer overflow reported by Coverity.
v2:
=> [PATCH v2] test: pool_latency: fix potential overflow

test/performance/odp_bench_packet.c
Add missing tests for odp_packet_user_flag() and odp_packet_user_flag_set() APIs.
=> [PATCH v3] test: bench_packet: add tests for user flag functions

test/performance/odp_sched_perf.c
Add signal handler for SIGINT for closing the application. Also, run the application indefinitely if the number of events to schedule is set to zero.
=> [PATCH v2] test: sched_perf: add signal handler

platform/linux-generic/odp_ishmpool.c, test/performance/odp_scheduling.c
Remove a couple of warnings by gcc 14 (unreleased experimental version).
=> [PATCH v3] remove a couple of compiler warnings

test/performance/odp_pool_latency.c
Add possibility to run tester indefinitely with special round count value. This enables longer and more robust test runs.
v2:
- Rebased
v3:
- Reworded error message
=> [PATCH v4] test: pool_latency: add possibility to run indefinitely

.github/workflows/ci-pipeline-arm64.yml
Update arm64 GitHub checkout action into the latest release version.
=> [PATCH v2] github_ci: update checkout github action

test/performance/odp_l2fwd.c
Add new -O option for changing the default output port mapping for interfaces. This can be used for e.g. configuring interfaces to loopback received packets or forwarding all received packets to a single output port.
The new option also enables a scenario where an interface does not have any output queues so refactor packet I/O creation to disable affected directions.
v2:
- Rebased
=> [PATCH v3] test: l2fwd: add option to change default output port mapping

test/performance/odp_l2fwd.c
Add new -C option for configuring packet transmit completion. Both poll and event completions are supported at least partially: event completion is currently supported only with scheduled queues.
Transmit completion can be configured to be attempted to be done for every nth packet within limitations of the completion resources.
v2:
- Rebased
v3:
- Fixed poll mode handling with a single completion ID
v4:
- Rebased
- Added handling for discarded packets that had transmit completion set
v5:
=> [PATCH v5] test: l2fwd: add transmit completion support

test/performance/odp_l2fwd.c
Add new command line option ('-X, --flow_control') for enabling reception and/or transmission of Ethernet pause frames.
=> [PATCH v3] test: l2fwd: add option for enabling ethernet flow control

platform/linux-generic/odp_ishm.c
Classify debug messages from fallocate() failures as warnings when trying to use huge pages, as the SHM implementation will fall back to using normal pages and the error messages can confuse application users.
=> [PATCH v3] linux-gen: shm: reclassify fallocate failure debug message

platform/linux-generic/odp_ml.c
In check_io_shape(), called from odp_ml_model_create(), don't require a non-zero max size for dynamic dimensions. This avoids an error when loading the batch_add.onnx model with model_explorer. Onnx doesn't have minimums or maximums for dynamic dimensions.
Instead, check that batch type shapes have exactly one dynamic dimension.
=> [PATCH v3] linux-gen: ml: don't require non-zero max size for dynamic dimension

test/performance/odp_random.c
Parse ODP helper options to enable possibility to choose ODP thread memory model.
v2:
=> [PATCH v2] test: random: add possibility to choose memory model

test/validation/api/timer/timer.c
In some implementations, the maximum timeout parameters in odp_timer_capability_t.max_tmo are excessively long. Consequently, the assert that tests the timeout length in the
timer_test_max_tmo_min_tmo_sched function is triggered. To ensure the timer validation test passes on all platforms, we need to modify this logic. The assert needs to be removed and a new conditional function should be added to check the maximum value of the minimum timeout. If the test is expected to run for an extended duration, it will be skipped.
=> [PATCH v6] validation: timer: skip test if expected runtime is long

test/performance/odp_dmafwd.c
dmafwd sends the packets in multiple of burst size. If the number of
packets to be sent are not in multiple of burst size,
(num pkts to send % burst size) packets are not sent.
This patch adds a stats counter "pkt_cleanup" for the packets that are
not sent.
Signed-off-by: Amit Prakash Shukla <amitprakashs@marvell.com>
Reviewed-by: Tuomas Taipale <tuomas.taipale@nokia.com>
=> test: dmafwd: packet cleanup counter add

test/common/export_results.c
Previously the path of the output file was written into the output file. Now the command with which the test was run with is written instead. Writing the path in the output is meant to indicate which application the results were acquired from.
=> [PATCH v3] test: export: fix written path in output files

configure.ac, platform/linux-generic/include/odp/api/plat/atomic_inlines.h
=> [PATCH v3] atomic: small improvements to locked atomics

helper/Makefile.am, platform/linux-generic/Makefile.am, platform/linux-generic/arch/x86/odp_sysinfo_parse.c
A couple of small changes to fix make check in 32-bit x86.
=> [PATCH v3] Fix make check in i386

include/odp/api/spec/cpu.h, platform/linux-generic/arch/aarch64/odp/api/abi/cpu_inlines.h, platform/linux-generic/arch/arm/odp/api/abi/cpu_inlines.h, platform/linux-generic/arch/default/odp/api/abi/cpu_inlines.h, platform/linux-generic/arch/x86/odp/api/abi/cpu_inlines.h, platform/linux-generic/include/odp/api/plat/cpu_inlines.h, test/performance/odp_icache_perf.c, test/validation/api/cpu/cpu.c
v6: rebase, add icache prefetch options to icache_perf test to demonstrate usage of the new API
v7: rebase, add review tag
v8: rebase, add review tag
=> [PATCH v8] api: cpu: instruction cache prefetch

test/performance/odp_packet_gen.c
Add new -X option to enable L4 checksum offloading. This can boost performance in cases where checksum can be offloaded to be done by HW.
v2:
- Rebased
v3:
- Updated enabling logic
v4:
=> [PATCH v4] test: packet_gen: add possibility to enable L4 checksum offloading

test/validation/api/dma/dma.c
Add new test for verifying DMA transfer correctness from several source packets to a single destination packet with multiple offsets.
v2:
=> [PATCH v3] validation: dma: add test for multiple offsets

.gitreview
Remove leftover .gitreview file from time project was still using Gerrit.
=> [PATCH v2] remove unused .gitreview file

test/performance/odp_crypto.c
Use the basic crypto operation type instead of the to-be-deprecated legacy operation type. Since other op types than legacy do not support explicit in-place operations, remove the --inplace flag.
=> [PATCH v2] test: performance: crypto: use basic op type and remove in-place option

include/odp/api/spec/crypto_types.h, platform/linux-generic/arch/aarch64/odp_crypto_armv8.c, platform/linux-generic/odp_crypto_ipsecmb.c, platform/linux-generic/odp_crypto_null.c, platform/linux-generic/odp_crypto_openssl.c, test/validation/api/crypto/crypto_op_test.c, test/validation/api/crypto/odp_crypto_test_inp.c
Deprecate ODP_CRYPTO_OP_TYPE_LEGACY.
=> [PATCH v4] api: crypto: deprecate 'legacy' crypto op type

platform/linux-generic/odp_timer.c, test/performance/odp_stress.c
Fixes timer bug and adds new option into stress test. The option is used to select between shared and worker thread private timer pools.
=> [PATCH v2] test: stress: add timer mode option

test/validation/api/classification/odp_classification_basic.c, test/validation/api/classification/odp_classification_common.c, test/validation/api/classification/odp_classification_test_pmr.c, test/validation/api/classification/odp_classification_tests.c, test/validation/api/classification/odp_classification_testsuites.h
Reduce code duplication, add missing default value checks and speed up the test.
=> [PATCH v3] validation: cls: misc minor improvements

platform/linux-generic/test/validation/api/pktio/pktio_run_tap.sh, test/performance/odp_l2fwd_perf_run.sh, test/performance/odp_l2fwd_run.sh, test/performance/odp_packet_gen.c, test/performance/odp_packet_gen_run.sh, test/performance/odp_sched_pktio_run.sh, test/validation/api/pktio/pktio.c
Speed up test run by shortening or removing several wait times.
=> [PATCH v2] Speed up tests

test/performance/odp_sched_latency.c
Add '-W, --wait-ns <num>' option to odp_sched_latency test application to simulate application work between schedule and queue enqueue calls. Wait time is defined in nanoseconds.
=> [PATCH v2] test: sched_latency: add wait option to simulate work
